return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#05080a",
				bg = "#05080a",
				dark_bg = "#040608",
				darker_bg = "#030506",
				lighter_bg = "#141719",
				selection = "#ffc2df",
				selection_background = "#ffc2df",
				selection_foreground = "#05080a",
				foreground = "#fff6ff",
				fg = "#fff6ff",
				light_fg = "#fff7ff",
				bright_fg = "#ffe1e1",
				dark_fg = "#8e8b91",
				muted = "#4b4c4d",
				cursor = "#b2fff3",
				accent = "#b2fff3",
				red = "#ff9fbc",
				green = "#baf7b5",
				yellow = "#fff6c3",
				blue = "#b2fff3",
				purple = "#dfbaff",
				magenta = "#dfbaff",
				cyan = "#ffc79b",
				orange = "#ffaecb",
				brown = "#cc8ba2",
				bright_red = "#ffaecb",
				bright_green = "#baf7b5",
				bright_yellow = "#fff6c3",
				bright_blue = "#b2fff3",
				bright_purple = "#dfbaff",
				bright_cyan = "#ffc79b",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
