accent = "#e75a50"
cursor = "#C0AF7F"
foreground = "#efebdc"
background = "#1B1B1B"
selection_foreground = "#1B1B1B"
selection_background = "#e75a50"

color0 = "#1B1B1B"
color1 = "#F44336"
color2 = "#e75a50"
color3 = "#a99b7a"
color4 = "#e58980"
color5 = "#77838a"
color6 = "#6d6d6d"
color7 = "#E1CE98"
color8 = "#817f68"
color9 = "#e75a50"
color10 = "#77838a"
color11 = "#a99b7a"
color12 = "#e58980"
color13 = "#9ba2a6"
color14 = "#888888"
color15 = "#efebdc"
