accent = "#b4756b"
cursor = "#f0e9ec"
foreground = "#f0e9ec"
background = "#1e2125"
selection_foreground = "#1e2125"
selection_background = "#f0e9ec"

color0 = "#1e2125"
color1 = "#976870"
color2 = "#B4756B"
color3 = "#C17A6A"
color4 = "#9B826B"
color5 = "#B48162"
color6 = "#706B82"
color7 = "#c5aeb9"
color8 = "#897981"
color9 = "#c1a4a9"
color10 = "#d6b4af"
color11 = "#dfbab2"
color12 = "#c4b5a8"
color13 = "#d5b8a7"
color14 = "#a5a1b2"
color15 = "#f0e9ec"
