# Theme: soho-dusk

# Main bg
theme[main_bg]="#1a1721"

# Main text color
theme[main_fg]="#d0cbd8"

# Title color for boxes
theme[title]="#d0cbd8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#6dd8ce"

# Background color of selected item in processes box
theme[selected_bg]="#4d3a5a"

# Foreground color of selected item in processes box
theme[selected_fg]="#d0cbd8"

# Color of inactive/disabled text
theme[inactive_fg]="#928da0"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#6dd8ce"

# Cpu box outline color
theme[cpu_box]="#4d465a"

# Memory/disks box outline color
theme[mem_box]="#4d465a"

# Net up/down box outline color
theme[net_box]="#4d465a"

# Processes box outline color
theme[proc_box]="#4d465a"

# Box divider line and small boxes line color
theme[div_line]="#4d465a"

# Temperature graph colors
theme[temp_start]="#96e0b8"
theme[temp_mid]="#edc97a"
theme[temp_end]="#f09aae"

# CPU graph colors
theme[cpu_start]="#6dd8ce"
theme[cpu_mid]="#96bef0"
theme[cpu_end]="#d8a0e8"

# Mem/Disk free meter
theme[free_start]="#96e0b8"
theme[free_mid]="#6dd8ce"
theme[free_end]="#96bef0"

# Mem/Disk cached meter
theme[cached_start]="#96bef0"
theme[cached_mid]="#c48ad5"
theme[cached_end]="#d8a0e8"

# Mem/Disk available meter
theme[available_start]="#6dd8ce"
theme[available_mid]="#7cc9a0"
theme[available_end]="#96e0b8"

# Mem/Disk used meter
theme[used_start]="#d9b464"
theme[used_mid]="#d4956e"
theme[used_end]="#e87b97"

# Download graph colors
theme[download_start]="#7ba5dd"
theme[download_mid]="#96bef0"
theme[download_end]="#6dd8ce"

# Upload graph colors
theme[upload_start]="#c48ad5"
theme[upload_mid]="#e89bc1"
theme[upload_end]="#f09aae"
