return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#1a1721",
				bg = "#1a1721",
				dark_bg = "#141119",
				darker_bg = "#100e14",
				lighter_bg = "#28252e",
				selection = "#4d3a5a",
				selection_background = "#4d3a5a",
				selection_foreground = "#e0dbea",
				foreground = "#d0cbd8",
				fg = "#d0cbd8",
				light_fg = "#d5d0dc",
				bright_fg = "#bdb8cb",
				dark_fg = "#7e7a86",
				muted = "#4d465a",
				cursor = "#e0dbea",
				accent = "#e89bc1",
				red = "#e87b97",
				green = "#7cc9a0",
				yellow = "#d9b464",
				blue = "#7ba5dd",
				purple = "#c48ad5",
				magenta = "#c48ad5",
				cyan = "#57bfb5",
				orange = "#f09aae",
				brown = "#c07b8b",
				bright_red = "#f09aae",
				bright_green = "#96e0b8",
				bright_yellow = "#edc97a",
				bright_blue = "#96bef0",
				bright_purple = "#d8a0e8",
				bright_cyan = "#6dd8ce",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
