# UI Colors (extended)
accent = "#849be3"
cursor = "#8dffd5"

# Primary colors
foreground = "#8dffd5"
background = "#313132"

# Selection colors
selection_foreground = "#313132"
selection_background = "#8dffd5"

# Normal colors (ANSI 0-7)
color0 = "#313132"
color1 = "#d68679"
color2 = "#47ae83"
color3 = "#46b287"
color4 = "#849be3"
color5 = "#c086c6"
color6 = "#6ca48f"
color7 = "#8dffd5"

# Bright colors (ANSI 8-15)
color8 = "#84838a"
color9 = "#ffa998"
color10 = "#63d89f"
color11 = "#61dca3"
color12 = "#a8beff"
color13 = "#eca6f8"
color14 = "#8bccb0"
color15 = "#7effcd"
