accent = "#4c566a"
cursor = "#dcd6d6"
foreground = "#dcd6d6"
background = "#232529"
selection_foreground = "#dcd6d6"
selection_background = "#4c4c4f"

color0 = "#232529"
color1 = "#b18786"
color2 = "#98b398"
color3 = "#bab292"
color4 = "#9e9eb8"
color5 = "#bea7b7"
color6 = "#95a8b0"
color7 = "#d6d8dc"
color8 = "#787c87"
color9 = "#bb9391"
color10 = "#b39898"
color11 = "#bcb48f"
color12 = "#d2d2df"
color13 = "#e5dbe2"
color14 = "#98acb3"
color15 = "#dcd6d6"
