.pragma library

function percentToUnit(v) {
    if (v === undefined || v === null) return undefined;
    return v > 1 ? v / 100 : v;
}

function nonEmptyStringOr(def) {
    return function(v) {
        if (v === undefined || v === null) return def;
        if (String(v).trim() === "") return def;
        return String(v);
    }
}

var SPEC = {
    currentThemeName: { def: "coppernight", onChange: "applyStoredTheme" },
    currentThemeCategory: { def: "vgs" },
    favoriteThemes: { def: [] },
    matugenScheme: { def: "scheme-tonal-spot", onChange: "regenSystemThemes" },
    matugenContrast: { def: 0, onChange: "regenSystemThemes" },
    matugenMode: { def: "auto" },
    matugenTargetMonitor: { def: "", onChange: "regenSystemThemes" },

    popupTransparency: { def: 1.0, coerce: percentToUnit },
    popupBlurStrength: { def: 0.65, coerce: percentToUnit },
    popupGlassEffect: { def: false },
    dockTransparency: { def: 1.0, coerce: percentToUnit },

    widgetBackgroundColor: { def: "sch" },
    widgetBackgroundCustomColor: { def: "#6750A4" },
    widgetBackgroundCustomStrength: { def: 0.50, coerce: percentToUnit },
    widgetColorMode: { def: "default" },
    controlCenterTileColorMode: { def: "primary" },
    buttonColorMode: { def: "primary" },
    surfaceGeometryTarget: { def: "sync", onChange: "updateCompositorLayout" },
    surfaceBorderWidth: { def: 1, onChange: "updateCompositorLayout" },
    cornerRadius: { def: 15, onChange: "updateCompositorLayout" },
    controlRadius: { def: 10 },
    niriLayoutGapsOverride: { def: -1, onChange: "updateCompositorLayout" },
    niriLayoutRadiusOverride: { def: -1, onChange: "updateCompositorLayout" },
    niriLayoutBorderSize: { def: -1, onChange: "updateCompositorLayout" },
    hyprlandLayoutGapsOverride: { def: -1, onChange: "updateCompositorLayout" },
    hyprlandLayoutGapsOutOverride: { def: -1, onChange: "updateCompositorLayout" },
    hyprlandLayoutRadiusOverride: { def: -1, onChange: "updateCompositorLayout" },
    hyprlandLayoutBorderSize: { def: -1, onChange: "updateCompositorLayout" },
    hyprlandResizeOnBorder: { def: true, onChange: "updateCompositorLayout" },
    mangoLayoutGapsOverride: { def: -1, onChange: "updateCompositorLayout" },
    mangoLayoutGapsOutOverride: { def: -1, onChange: "updateCompositorLayout" },
    mangoLayoutRadiusOverride: { def: -1, onChange: "updateCompositorLayout" },
    mangoLayoutBorderSize: { def: -1, onChange: "updateCompositorLayout" },
    mangoTrackpadNaturalScrolling: { def: true, onChange: "updateCompositorCursor" },

    firstDayOfWeek: { def: -1 },
    showWeekNumber: { def: false },
    calendarBackend: { def: "auto" },
    use24HourClock: { def: true },
    showSeconds: { def: false },
    padHours12Hour: { def: false },
    useFahrenheit: { def: false },
    windSpeedUnit: { def: "kmh" },
    nightModeEnabled: { def: false },
    animationSpeed: { def: 1 },
    customAnimationDuration: { def: 500 },
    syncComponentAnimationSpeeds: { def: true },
    popoutAnimationSpeed: { def: 1 },
    popoutCustomAnimationDuration: { def: 150 },
    modalAnimationSpeed: { def: 1 },
    modalCustomAnimationDuration: { def: 150 },
    enableRippleEffects: { def: true },
    animationVariant: { def: 0 },
    motionEffect: { def: 0 },
    m3ElevationEnabled: { def: true },
    m3ElevationIntensity: { def: 12 },
    m3ElevationOpacity: { def: 30 },
    m3ElevationColorMode: { def: "default" },
    m3ElevationLightDirection: { def: "top" },
    m3ElevationCustomColor: { def: "#000000" },
    modalElevationEnabled: { def: true },
    popoutElevationEnabled: { def: true },
    barElevationEnabled: { def: true },
    blurEnabled: { def: false },
    blurForegroundLayers: { def: true },
    blurLayerOutlineOpacity: { def: 0.12, coerce: percentToUnit },
    blurBorderColor: { def: "outline" },
    blurBorderCustomColor: { def: "#ffffff" },
    blurBorderOpacity: { def: 0.35, coerce: percentToUnit },
    wallpaperFillMode: { def: "Fill" },
    wallpaperSource: { def: "theme" },
    wallpaperFolder: { def: "" },
    blurredWallpaperLayer: { def: false },
    blurWallpaperOnOverview: { def: false },
    wallpaperBackgroundColorMode: { def: "black" },
    wallpaperBackgroundCustomColor: { def: "#000000" },

    showWorkspaceSwitcher: { def: true },
    showFocusedWindow: { def: true },
    showWeather: { def: true },
    showMusic: { def: true },
    showClipboard: { def: true },
    showCpuUsage: { def: true },
    showMemUsage: { def: true },
    showCpuTemp: { def: true },
    showGpuTemp: { def: true },
    selectedGpuIndex: { def: 0 },
    enabledGpuPciIds: { def: [] },
    showSystemTray: { def: true },
    systemTrayIconTintMode: { def: "none" },
    systemTrayIconTintSaturation: { def: 50 },
    systemTrayIconTintStrength: { def: 135 },
    showClock: { def: true },
    showNotificationButton: { def: true },
    showBattery: { def: true },
    showBatteryPercent: { def: true },
    showBatteryPercentOnlyOnBattery: { def: false },
    showBatteryTime: { def: false },
    showBatteryTimeOnlyOnBattery: { def: false },
    showControlCenterButton: { def: true },
    showCapsLockIndicator: { def: true },

    controlCenterShowNetworkIcon: { def: true },
    controlCenterShowBluetoothIcon: { def: true },
    controlCenterShowAudioIcon: { def: true },
    controlCenterShowAudioPercent: { def: false },
    controlCenterShowVpnIcon: { def: true },
    controlCenterShowBrightnessIcon: { def: false },
    controlCenterShowBrightnessPercent: { def: false },
    controlCenterShowMicIcon: { def: false },
    controlCenterShowMicPercent: { def: false },
    controlCenterShowBatteryIcon: { def: false },
    controlCenterShowPrinterIcon: { def: false },
    controlCenterShowScreenSharingIcon: { def: true },
    controlCenterShowIdleInhibitorIcon: { def: false },
    controlCenterShowDoNotDisturbIcon: { def: false },

    showPrivacyButton: { def: true },
    privacyShowMicIcon: { def: false },
    privacyShowCameraIcon: { def: false },
    privacyShowScreenShareIcon: { def: false },

    controlCenterWidgets: {
        def: [
            { id: "volumeSlider", enabled: true, width: 50 },
            { id: "brightnessSlider", enabled: true, width: 50 },
            { id: "wifi", enabled: true, width: 50 },
            { id: "bluetooth", enabled: true, width: 50 },
            { id: "audioOutput", enabled: true, width: 50 },
            { id: "audioInput", enabled: true, width: 50 },
            { id: "nightMode", enabled: true, width: 50 },
            { id: "darkMode", enabled: true, width: 50 }
        ]
    },

    showWorkspaceIndex: { def: false },
    showWorkspaceName: { def: false },
    showWorkspacePadding: { def: false },
    workspaceScrolling: { def: false },
    showWorkspaceApps: { def: false },
    workspaceDragReorder: { def: true },
    maxWorkspaceIcons: { def: 3 },
    workspaceAppIconSizeOffset: { def: 0 },
    groupWorkspaceApps: { def: true },
    groupActiveWorkspaceApps: { def: false },
    workspaceFollowFocus: { def: false },
    showOccupiedWorkspacesOnly: { def: false },
    reverseScrolling: { def: false },
    dwlShowAllTags: { def: false },
    workspaceActiveAppHighlightEnabled: { def: false },
    workspaceColorMode: { def: "default" },
    workspaceFocusedCustomColor: { def: "#6750A4" },
    workspaceOccupiedColorMode: { def: "none" },
    workspaceOccupiedCustomColor: { def: "#625B71" },
    workspaceUnfocusedColorMode: { def: "default" },
    workspaceUnfocusedCustomColor: { def: "#49454E" },
    workspaceUrgentColorMode: { def: "default" },
    workspaceUrgentCustomColor: { def: "#B3261E" },
    workspaceFocusedBorderEnabled: { def: false },
    workspaceFocusedBorderColor: { def: "primary" },
    workspaceFocusedBorderCustomColor: { def: "#6750A4" },
    workspaceFocusedBorderThickness: { def: 2 },
    workspaceUnfocusedMonitorSeparateAppearance: { def: false },
    workspaceUnfocusedMonitorColorMode: { def: "default" },
    workspaceUnfocusedMonitorFocusedCustomColor: { def: "#6750A4" },
    workspaceUnfocusedMonitorOccupiedColorMode: { def: "none" },
    workspaceUnfocusedMonitorOccupiedCustomColor: { def: "#625B71" },
    workspaceUnfocusedMonitorUnfocusedColorMode: { def: "default" },
    workspaceUnfocusedMonitorUnfocusedCustomColor: { def: "#49454E" },
    workspaceUnfocusedMonitorUrgentColorMode: { def: "default" },
    workspaceUnfocusedMonitorUrgentCustomColor: { def: "#B3261E" },
    workspaceUnfocusedMonitorBorderEnabled: { def: false },
    workspaceUnfocusedMonitorBorderColor: { def: "primary" },
    workspaceUnfocusedMonitorBorderCustomColor: { def: "#6750A4" },
    workspaceUnfocusedMonitorBorderThickness: { def: 2 },
    workspaceNameIcons: { def: {} },
    waveProgressEnabled: { def: true },
    scrollTitleEnabled: { def: true },
    mediaAdaptiveWidthEnabled: { def: true },
    audioVisualizerEnabled: { def: true },
    audioScrollMode: { def: "volume" },
    audioWheelScrollAmount: { def: 5 },
    audioDeviceScrollVolumeEnabled: { def: false },
    mediaExcludePlayers: { def: [] },
    clockCompactMode: { def: false },
    focusedWindowCompactMode: { def: false },
    focusedWindowSize: { def: 1 },
    runningAppsCompactMode: { def: true },
    barMaxVisibleApps: { def: 0 },
    barMaxVisibleRunningApps: { def: 0 },
    barShowOverflowBadge: { def: true },
    trayAutoOverflow: { def: true },
    trayPopupSingleLine: { def: true },
    trayMaxVisibleItems: { def: 0 },
    appsDockHideIndicators: { def: false },
    appsDockColorizeActive: { def: false },
    appsDockActiveColorMode: { def: "primary" },
    appsDockEnlargeOnHover: { def: false },
    appsDockEnlargePercentage: { def: 125 },
    appsDockIconSizePercentage: { def: 100 },
    keyboardLayoutNameCompactMode: { def: false },
    keyboardLayoutNameShowIcon: { def: false},
    runningAppsCurrentWorkspace: { def: true },
    runningAppsGroupByApp: { def: false },
    runningAppsCurrentMonitor: { def: false },
    appIdSubstitutions: {
        def: [
            { pattern: "Spotify", replacement: "spotify", type: "exact" },
            { pattern: "beepertexts", replacement: "beeper", type: "exact" },
            { pattern: "home assistant desktop", replacement: "homeassistant-desktop", type: "exact" },
            { pattern: "com.transmissionbt.transmission", replacement: "transmission-gtk", type: "contains" },
            { pattern: "^steam_app_(\\d+)$", replacement: "steam_icon_$1", type: "regex" }
        ]
    },
    centeringMode: { def: "index" },
    clockDateFormat: { def: "" },
    lockDateFormat: { def: "" },
    greeterRememberLastSession: { def: true, onChange: "markGreeterSyncPending" },
    greeterRememberLastUser: { def: true, onChange: "markGreeterSyncPending" },
    greeterAutoLogin: { def: false, onChange: "scheduleGreeterAutoLoginSync" },
    greeterAutoLoginKeyringMode: { def: "keep", onChange: "scheduleGreeterAutoLoginSync" },
    greeterPrimaryMonitor: { def: "", onChange: "markGreeterSyncPending" },
    greeterEnableFprint: { def: false, onChange: "scheduleAuthApply" },
    greeterEnableU2f: { def: false, onChange: "scheduleAuthApply" },
    greeterWallpaperPath: { def: "", onChange: "markGreeterSyncPending" },
    greeterUse24HourClock: { def: true, onChange: "markGreeterSyncPending" },
    greeterShowSeconds: { def: false, onChange: "markGreeterSyncPending" },
    greeterPadHours12Hour: { def: false, onChange: "markGreeterSyncPending" },
    greeterLockDateFormat: { def: "", onChange: "markGreeterSyncPending" },
    greeterFontFamily: { def: "", onChange: "markGreeterSyncPending" },
    greeterWallpaperFillMode: { def: "", onChange: "markGreeterSyncPending" },
    greeterSyncPending: { def: false },
    greeterSyncBaseline: { def: {} },
    mediaSize: { def: 1 },

    browserPickerViewMode: { def: "grid" },
    browserUsageHistory: { def: {} },
    appPickerViewMode: { def: "grid" },
    filePickerUsageHistory: { def: {} },
    sortAppsAlphabetically: { def: false },
    appLauncherGridColumns: { def: 4 },
    overviewSearchCloseNiriOverview: { def: true },
    overviewSearchSectionViewModes: { def: {} },
    niriOverviewOverlayEnabled: { def: true },
    launcherSize: { def: "compact" },
    launcherShowSourceBadges: { def: true },
    launcherShowFooter: { def: true },
    launcherIncludeFilesInAll: { def: false },
    launcherIncludeFoldersInAll: { def: false },
    launcherSidebarShowByDefault: { def: true },
    launcherSearchRoots: { def: ["~"] },
    launcherSearchIgnored: { def: [".git", "node_modules", ".cache", ".local/share/Trash"] },
    launcherSearchIgnoreMounts: { def: true },
    launcherFolderOpenCommand: { def: "" },
    launcherMenuUsageHistory: { def: {} },
    launcherMenuViewMode: { def: "list" },
    keybindsFloatingWindow: { def: false },

    useAutoLocation: { def: false },
    weatherEnabled: { def: true },
    dashTabs: { def: [{ id: "overview", enabled: true }, { id: "media", enabled: true }, { id: "themes", enabled: true }, { id: "wallpaper", enabled: true }, { id: "weather", enabled: true }, { id: "settings", enabled: true }] },

    networkPreference: { def: "auto" },

    iconThemeDark: { def: "System Default", onChange: "applyStoredIconTheme" },
    iconThemeLight: { def: "System Default", onChange: "applyStoredIconTheme" },
    iconThemePerMode: { def: false, onChange: "applyStoredIconTheme" },
    lastAppliedIconTheme: { def: "" },
    availableIconThemes: { def: ["System Default"], persist: false },
    systemDefaultIconTheme: { def: "", persist: false },
    qt5ctAvailable: { def: false, persist: false },
    qt6ctAvailable: { def: false, persist: false },
    gtkAvailable: { def: false, persist: false },

    cursorSettings: { def: { theme: "System Default", size: 24, niri: { hideWhenTyping: false, hideAfterInactiveMs: 0 }, hyprland: { hideOnKeyPress: false, hideOnTouch: false, inactiveTimeout: 0 }, dwl: { cursorHideTimeout: 0 }, mango: { cursorHideTimeout: 0 } }, onChange: "updateCompositorCursor" },
    availableCursorThemes: { def: ["System Default"], persist: false },
    systemDefaultCursorTheme: { def: "", persist: false },

    launcherLogoMode: { def: "apps" },
    launcherLogoCustomPath: { def: "" },
    launcherLogoColorOverride: { def: "" },
    launcherLogoColorInvertOnMode: { def: false },
    launcherLogoBrightness: { def: 0.5 },
    launcherLogoContrast: { def: 1 },
    launcherLogoSizeOffset: { def: 0 },

    fontFamily: { def: "Inter Variable" },
    monoFontFamily: { def: "Fira Code" },
    fontWeight: { def: 400 },
    fontScale: { def: 1.0 },
    textRenderType: { def: 1 },
    textRenderQuality: { def: 0 },
    textHintingPreference: { def: 0 },
    textAntialiasing: { def: true },
    textKerning: { def: true },
    textLetterSpacing: { def: 0 },
    textWordSpacing: { def: 0 },
    textLineHeight: { def: 1.0 },
    textLineHeightMode: { def: "proportional" },
    textUseVariableWeight: { def: false },
    textVariableWeight: { def: 400 },
    textUseOpticalSize: { def: false },
    textOpticalSize: { def: 14 },
    textFeatureLigatures: { def: true },
    textFeatureTabularNumbers: { def: false },
    textFeatureStylisticSet: { def: 0 },
    systemFontsManaged: { def: true, onChange: "applySystemFonts" },
    systemFontInterfaceFamily: { def: "", onChange: "applySystemFonts" },
    systemFontMonoFamily: { def: "", onChange: "applySystemFonts" },
    systemFontSize: { def: 11, onChange: "applySystemFonts" },
    hyprlandFontFamily: { def: "", onChange: "applySystemFonts" },
    systemFontInterfaceAntialias: { def: true, onChange: "applySystemFonts" },
    systemFontInterfaceHinting: { def: "slight", onChange: "applySystemFonts" },
    systemFontInterfaceSubpixel: { def: "none", onChange: "applySystemFonts" },
    systemFontInterfaceLcdFilter: { def: "default", onChange: "applySystemFonts" },
    systemFontInterfaceAutohint: { def: false, onChange: "applySystemFonts" },
    systemFontMonoAntialias: { def: true, onChange: "applySystemFonts" },
    systemFontMonoHinting: { def: "slight", onChange: "applySystemFonts" },
    systemFontMonoSubpixel: { def: "none", onChange: "applySystemFonts" },
    systemFontMonoLcdFilter: { def: "default", onChange: "applySystemFonts" },
    systemFontMonoAutohint: { def: false, onChange: "applySystemFonts" },

    notepadUseMonospace: { def: true },
    notepadFontFamily: { def: "" },
    notepadFontSize: { def: 14 },
    notificationSummaryFontSize: { def: 0 },
    notificationBodyFontSize: { def: 0 },
    notepadShowLineNumbers: { def: false },
    notepadAutoSave: { def: false },
    notepadSlideoutSide: { def: "right" },
    notepadDefaultMode: { def: "slideout" },
    notepadTransparencyOverride: { def: -1 },
    notepadLastCustomTransparency: { def: 0.7 },
    notepadUseCompositorGap: { def: false },
    notepadEdgeGap: { def: 0 },

    soundsEnabled: { def: true },
    useSystemSoundTheme: { def: false },
    soundLogin: { def: false },
    soundNewNotification: { def: true, onChange: "runNotificationSoundHook" },
    soundVolumeChanged: { def: true },
    soundPluggedIn: { def: true },
    muteSoundsWhenMediaPlaying: { def: true },

    acMonitorTimeout: { def: 0 },
    acLockTimeout: { def: 0 },
    acSuspendTimeout: { def: 0 },
    acSuspendBehavior: { def: 0 },
    acProfileName: { def: "" },
    acPostLockMonitorTimeout: { def: 0 },
    batteryMonitorTimeout: { def: 0 },
    batteryLockTimeout: { def: 0 },
    batterySuspendTimeout: { def: 0 },
    batterySuspendBehavior: { def: 0 },
    batteryProfileName: { def: "" },
    batteryPostLockMonitorTimeout: { def: 0 },
    batteryChargeLimit: { def: 100 },
    batteryNotifyChargeLimit: { def: false },
    batteryCriticalThreshold: { def: 10 },
    batteryNotifyCritical: { def: true },
    batteryLowThreshold: { def: 20 },
    batteryNotifyLow: { def: false },
    batteryNotificationType: { def: 0 },
    batteryAutoPowerSaver: { def: false },
    lockBeforeSuspend: { def: false },
    loginctlLockIntegration: { def: true },
    mediaInhibitsIdle: { def: true },
    screensaverEnabled: { def: false },
    screensaverTimeout: { def: 240 },
    screensaverType: { def: "ascii" },
    screensaverVideoPath: { def: "" },
    // Empty selects the bundled screensaver logo without storing its installation path.
    screensaverAsciiImagePath: { def: "" },
    fadeToLockEnabled: { def: true },
    fadeToLockGracePeriod: { def: 5 },
    fadeToDpmsEnabled: { def: true },
    fadeToDpmsGracePeriod: { def: 5 },
    launchPrefix: { def: "" },
    brightnessDevicePins: { def: {} },
    wifiNetworkPins: { def: {} },
    bluetoothDevicePins: { def: {} },
    audioInputDevicePins: { def: {} },
    audioOutputDevicePins: { def: {} },

    gtkThemingEnabled: { def: false, onChange: "regenSystemThemes" },
    qtThemingEnabled: { def: false, onChange: "regenSystemThemes" },
    syncModeWithPortal: { def: true },
    terminalsAlwaysDark: { def: false, onChange: "regenSystemThemes" },

    muxType: { def: "tmux" },
    muxUseCustomCommand: { def: false },
    muxCustomCommand: { def: "" },
    muxSessionFilter: { def: "" },

    // Per-app theme generation toggles keyed by target app id (see
    // themes/targets/*/config.json). Absent key = default from app detection.
    themeApps: { def: {} },

    showDock: { def: false },
    dockAutoHide: { def: false },
    dockSmartAutoHide: { def: false },
    dockUseOverlayLayer: { def: false },
    dockGroupByApp: { def: false },
    dockRestoreSpecialWorkspaceOnClick: { def: false },
    dockScratchpadBadge: { def: true },
    dockOpenOnOverview: { def: false },
    dockPosition: { def: 1 },
    dockSpacing: { def: 4 },
    dockBottomGap: { def: 0 },
    dockMargin: { def: 0 },
    dockIconSize: { def: 40 },
    dockIndicatorStyle: { def: "circle" },
    dockBorderEnabled: { def: false },
    dockBorderColor: { def: "surfaceText" },
    dockBorderOpacity: { def: 1.0, coerce: percentToUnit },
    dockBorderThickness: { def: 1 },
    dockIsolateDisplays: { def: false },
    dockLauncherEnabled: { def: false },
    dockLauncherLogoMode: { def: "apps" },
    dockLauncherLogoCustomPath: { def: "" },
    dockLauncherLogoColorOverride: { def: "" },
    dockLauncherLogoSizeOffset: { def: 0 },
    dockLauncherLogoBrightness: { def: 0.5, coerce: percentToUnit },
    dockLauncherLogoContrast: { def: 1, coerce: percentToUnit },
    dockMaxVisibleApps: { def: 0 },
    dockMaxVisibleRunningApps: { def: 0 },
    dockShowOverflowBadge: { def: true },
    dockShowTrash: { def: false },
    dockTrashFileManager: { def: "default" },
    dockTrashCustomCommand: { def: "" },

    notificationOverlayEnabled: { def: false },
    notificationPopupShadowEnabled: { def: true },
    notificationPopupPrivacyMode: { def: false },
    overviewRows: { def: 2, persist: false },
    overviewColumns: { def: 5, persist: false },
    overviewScale: { def: 0.16, persist: false },

    modalDarkenBackground: { def: true },

    lockScreenShowPowerActions: { def: true },
    lockScreenShowSystemIcons: { def: true },
    lockScreenShowTime: { def: true },
    lockScreenShowDate: { def: true },
    lockScreenShowProfileImage: { def: true },
    lockScreenShowPasswordField: { def: true },
    lockScreenShowMediaPlayer: { def: true },
    lockScreenPowerOffMonitorsOnLock: { def: false },
    lockScreenBlankEnabled: { def: true },
    hideCursorWhenBlanked: { def: true },
    lockScreenBlankTimeout: { def: 300 },
    lockAtStartup: { def: false },
    enableFprint: { def: false },
    maxFprintTries: { def: 15 },
    enableU2f: { def: false, onChange: "scheduleAuthApply" },
    u2fMode: { def: "or" },
    lockScreenActiveMonitor: { def: "all", coerce: nonEmptyStringOr("all") },
    lockScreenInactiveColor: { def: "#000000" },
    lockScreenNotificationMode: { def: 0 },
    lockScreenVideoEnabled: { def: false },
    lockScreenVideoPath: { def: "" },
    lockScreenVideoCycling: { def: false },
    lockScreenWallpaperPath: { def: "" },
    lockScreenWallpaperFillMode: { def: "" },
    lockScreenFontFamily: { def: "" },
    hideBrightnessSlider: { def: false },

    notificationTimeoutLow: { def: 5000 },
    notificationTimeoutNormal: { def: 5000 },
    notificationTimeoutCritical: { def: 0 },
    notificationCompactMode: { def: false },
    notificationShowTimeoutBar: { def: false },
    notificationDedupeEnabled: { def: true },
    notificationServerEnabled: { def: true },
    notificationFirstRunTakeoverDone: { def: false },
    notificationPopupPosition: { def: 0 },
    notificationAnimationSpeed: { def: 1 },
    notificationCustomAnimationDuration: { def: 400 },
    notificationHistoryEnabled: { def: true },
    notificationHistoryMaxCount: { def: 50 },
    notificationHistoryMaxAgeDays: { def: 7 },
    notificationHistorySaveLow: { def: true },
    notificationHistorySaveNormal: { def: true },
    notificationHistorySaveCritical: { def: true },
    notificationRules: { def: [] },
    notificationFocusedMonitor: { def: false },

    osdAlwaysShowValue: { def: false },
    osdPosition: { def: 5 },
    osdVolumeEnabled: { def: true },
    osdMediaVolumeEnabled: { def: true },
    osdMediaPlaybackEnabled: { def: false },
    osdBrightnessEnabled: { def: true },
    osdIdleInhibitorEnabled: { def: true },
    osdMicMuteEnabled: { def: true },
    osdCapsLockEnabled: { def: true },
    osdPowerProfileEnabled: { def: false },
    osdAudioOutputEnabled: { def: true },

    powerActionConfirm: { def: true },
    powerActionHoldDuration: { def: 0.5 },
    powerMenuActions: { def: ["reboot", "logout", "poweroff", "lock", "suspend", "restart"] },
    powerMenuDefaultAction: { def: "logout" },
    powerMenuGridLayout: { def: false },
    customPowerActionLock: { def: "" },
    customPowerActionLogout: { def: "" },
    customPowerActionSuspend: { def: "" },
    customPowerActionHibernate: { def: "" },
    customPowerActionReboot: { def: "" },
    customPowerActionPowerOff: { def: "" },

    updaterCheckOnStart: { def: false },
    updaterIntervalSeconds: { def: 1800 },

    displayNameMode: { def: "system" },
    screenPreferences: { def: {} },
    showOnLastDisplay: { def: {} },
    niriOutputSettings: { def: {} },
    hyprlandOutputSettings: { def: {} },
    displayProfiles: { def: {} },
    activeDisplayProfile: { def: {} },
    displayProfileAutoSelect: { def: false },
    displayShowDisconnected: { def: false },
    displaySnapToEdge: { def: true },

    barConfigs: {
        def: [{
            id: "default",
            name: "Main Bar",
            enabled: true,
            position: 0,
            screenPreferences: ["all"],
            showOnLastDisplay: true,
            leftWidgets: ["launcherButton", "workspaceSwitcher", "focusedWindow"],
            centerWidgets: ["music", "clock", "weather"],
            rightWidgets: ["systemTray", "clipboard", "cpuUsage", "memUsage", "notificationButton", "battery", "controlCenterButton"],
            spacing: 4,
            innerPadding: 4,
            bottomGap: 0,
            transparency: 1.0,
            widgetTransparency: 1.0,
            squareCorners: false,
            noBackground: false,
            maximizeWidgetIcons: false,
            maximizeWidgetText: false,
            removeWidgetPadding: false,
            widgetPadding: 8,
            gothCornersEnabled: false,
            gothCornerRadiusOverride: false,
            gothCornerRadiusValue: 12,
            borderEnabled: false,
            borderColor: "surfaceText",
            borderOpacity: 1.0,
            borderThickness: 1,
            widgetOutlineEnabled: false,
            widgetOutlineColor: "primary",
            widgetOutlineOpacity: 1.0,
            widgetOutlineThickness: 1,
            fontScale: 1.0,
            iconScale: 1.0,
            autoHide: false,
            autoHideStrict: false,
            autoHideDelay: 250,
            showOnWindowsOpen: false,
            openOnOverview: false,
            visible: true,
            popupGapsAuto: true,
            popupGapsManual: 4,
            maximizeDetection: true,
            useOverlayLayer: false,
            scrollEnabled: true,
            scrollXBehavior: "column",
            scrollYBehavior: "workspace",
            shadowIntensity: 0,
            shadowOpacity: 60,
            shadowColorMode: "default",
            shadowCustomColor: "#000000",
            clickThrough: false,
            hoverPopouts: false,
            hoverPopoutDelay: 150
        }], onChange: "updateBarConfigs"
    },

    // Bar widget ids the user explicitly removed. Without this, "removed" and
    // "never mentioned" are the same absence, and a barConfigs authored on a
    // desktop can never be told apart from a deliberate choice — see
    // settings/BarWidgets.js.
    removedBarWidgets: { def: [] },

    // Scratchpad records use the schema in the helper, which renders compositor rules.
    // ScratchpadService reads shared compositor focus to apply dismissOnFocusLoss.
    scratchpads: { def: [], onChange: "updateScratchpads" },

    desktopClockEnabled: { def: false },
    desktopClockStyle: { def: "analog" },
    desktopClockTransparency: { def: 0.8, coerce: percentToUnit },
    desktopClockColorMode: { def: "primary" },
    desktopClockCustomColor: { def: "#ffffff" },
    desktopClockShowDate: { def: true },
    desktopClockShowAnalogNumbers: { def: false },
    desktopClockShowAnalogSeconds: { def: true },
    desktopClockX: { def: -1 },
    desktopClockY: { def: -1 },
    desktopClockWidth: { def: 280 },
    desktopClockHeight: { def: 180 },
    desktopClockDisplayPreferences: { def: ["all"] },

    systemMonitorEnabled: { def: false },
    systemMonitorShowHeader: { def: true },
    systemMonitorTransparency: { def: 0.8, coerce: percentToUnit },
    systemMonitorColorMode: { def: "primary" },
    systemMonitorCustomColor: { def: "#ffffff" },
    systemMonitorShowCpu: { def: true },
    systemMonitorShowCpuGraph: { def: true },
    systemMonitorShowCpuTemp: { def: true },
    systemMonitorShowGpuTemp: { def: false },
    systemMonitorGpuPciId: { def: "" },
    systemMonitorShowMemory: { def: true },
    systemMonitorShowMemoryGraph: { def: true },
    systemMonitorShowNetwork: { def: true },
    systemMonitorShowNetworkGraph: { def: true },
    systemMonitorShowDisk: { def: true },
    systemMonitorShowTopProcesses: { def: false },
    systemMonitorTopProcessCount: { def: 3 },
    systemMonitorTopProcessSortBy: { def: "cpu" },
    systemMonitorGraphInterval: { def: 60 },
    systemMonitorLayoutMode: { def: "auto" },
    systemMonitorX: { def: -1 },
    systemMonitorY: { def: -1 },
    systemMonitorWidth: { def: 320 },
    systemMonitorHeight: { def: 480 },
    systemMonitorDisplayPreferences: { def: ["all"] },
    systemMonitorVariants: { def: [] },
    desktopWidgetPositions: { def: {} },
    desktopWidgetGridSettings: { def: {} },

    desktopWidgetInstances: { def: [] },

    desktopWidgetGroups: { def: [] },

    builtInPluginSettings: { def: {} },
    clipboardClickToPaste: { def: false },
    clipboardEnterToPaste: { def: false },
    clipboardRememberTypeFilter: { def: false },
    clipboardTypeFilter: { def: "all" },
    clipboardVisibleEntryActions: { def: ["pin", "edit", "delete"] },

    launcherPluginVisibility: { def: {} },
    launcherPluginOrder: { def: [] },

    // Suppresses the sudoToggle grant-confirmation modal. A top-level key, not
    // plugin data, so it is visible and resettable next to every other setting
    // rather than buried in `builtInPluginSettings`. Default false: the grant
    // is confirmed until the user opts out of being asked.
    sudoToggleSkipGrantConfirm: { def: false },

    barInsetPaddingShared: { def: -1 },
    barInsetPaddingSyncAll: { def: false }
};

function getValidKeys() {
    return Object.keys(SPEC).filter(function (k) { return SPEC[k].persist !== false; }).concat(["configVersion"]);
}

function set(root, key, value, saveFn, hooks) {
    if (!(key in SPEC)) return;
    if (value === undefined || value === null) value = SPEC[key].def;
    var oldValue = root[key];
    root[key] = value;
    var hookName = SPEC[key].onChange;
    if (hookName && hooks && hooks[hookName]) {
        hooks[hookName](root, key, oldValue);
    }
    saveFn();
}
