# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

PYTHON_COMPAT=( python3_{12..15} )

inherit optfeature python-single-r1

DESCRIPTION="VanillaGreen desktop shell for Hyprland and Niri"
HOMEPAGE="https://github.com/vanillagreencom/vgs"
SRC_URI="https://github.com/vanillagreencom/vgs/releases/download/v${PV}/vgs-${PV}-source.tar.gz"
S="${WORKDIR}/vgs-${PV}"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~arm64"
IUSE="+extra-themes"
REQUIRED_USE="${PYTHON_REQUIRED_USE}"

# RDEPEND is generated by scripts/gen-package-metadata.py from
# config/vshell/dependencies.json and packaging/optional-packages.json.
# Run scripts/gen-package-metadata.py --write after changing either file.
RDEPEND="
	${PYTHON_DEPS}
	app-misc/jq
	gui-apps/quickshell
	gui-apps/grim
	gui-apps/slurp
	gui-apps/wl-clipboard
	x11-libs/libnotify
	dev-libs/glib
	app-admin/sudo
	!gui-apps/mako
	!x11-misc/dunst
"
BDEPEND="dev-lang/go"

src_prepare() {
	default
	sed -i 's|^#!/bin/env bash$|#!/usr/bin/env bash|' \
		config/vshell/nvim/colorschemes/tokyonight.nvim/scripts/{build,docs} || die
}

src_compile() {
	cd backend || die
	go build -mod=vendor -buildvcs=false -trimpath \
		-ldflags="-s -w -X vshell/backend/internal/registry.cliVersion=${PV}" \
		-o "${T}/vshell-backend" ./cmd/vshell-backend || die
}

src_install() {
	DESTDIR="${D}" PREFIX=/usr VGS_THEME_BUNDLE=core \
		VGS_BACKEND_BINARY="${T}/vshell-backend" \
		"${S}/packaging/install-system.sh" || die

	if use extra-themes; then
		DESTDIR="${D}" PREFIX=/usr VGS_THEME_BUNDLE=extras \
			"${S}/packaging/install-system.sh" || die
	fi
}

pkg_postinst() {
	elog "VGS installs the user service but does not enable it automatically."
	elog "Start it for the current user with:"
	elog
	elog "  systemctl --user enable --now vshell.service"
	elog
	elog "Run 'vshell deps status' to inspect optional feature dependencies."
	elog

	# BEGIN GENERATED OPTIONAL DEPENDENCIES
	# Generated by scripts/gen-package-metadata.py from
	# config/vshell/dependencies.json and packaging/optional-packages.json.
	# Run scripts/gen-package-metadata.py --write after changing either file.
	optfeature "terminal file manager for the launcher Yazi folder opener" app-misc/yazi
	optfeature "launcher recent-directory search" app-shells/zoxide
	optfeature "region OCR" app-text/tesseract
	optfeature "ICC colour profiles" dev-python/pillow[lcms]
	optfeature "desktop-entry cache refresh after installing a web app" dev-util/desktop-file-utils
	optfeature "greeter and keyring integration" gnome-base/gnome-keyring
	optfeature "file manager for the launcher folder opener" gnome-base/nautilus
	optfeature "terminal for VGS terminal actions" gui-apps/foot
	optfeature "launcher type-out into the focused window" gui-apps/wtype
	optfeature "greeter and keyring integration" gui-libs/greetd
	optfeature "file manager for the launcher folder opener" kde-apps/dolphin
	optfeature "terminal for VGS terminal actions" kde-apps/konsole
	optfeature "font cache refresh after a font change" media-libs/fontconfig
	optfeature "Bluetooth audio codec selection" media-libs/libpulse
	optfeature "audio visualizer widget" media-sound/cava
	optfeature "screen recording" media-video/ffmpeg
	optfeature "file thumbnails" media-video/ffmpegthumbnailer
	optfeature "per-interface network usage" net-analyzer/bandwhich
	optfeature "AI usage widget" net-misc/curl
	optfeature "cloud file sync" net-misc/rclone
	optfeature "Tailscale widget" net-vpn/tailscale
	optfeature "launcher file and folder search" sys-apps/fd
	optfeature "launcher text search" sys-apps/ripgrep
	optfeature "fingerprint unlock" sys-auth/fprintd
	optfeature "privileged actions run from the shell (user management, some system settings)" sys-auth/polkit
	optfeature "cloud sync streaming mounts" sys-fs/fuse
	optfeature "Qt 5 application theming" x11-misc/qt5ct
	optfeature "Qt 6 application theming" x11-misc/qt6ct
	optfeature "default-application queries, opening files and URLs in their default application" x11-misc/xdg-utils
	optfeature "terminal for VGS terminal actions" x11-terms/alacritty
	optfeature "terminal for VGS terminal actions" x11-terms/gnome-terminal
	optfeature "terminal for VGS terminal actions" x11-terms/kitty
	optfeature "terminal for VGS terminal actions" x11-terms/xterm
	optfeature "file manager for the launcher folder opener" xfce-base/thunar
	# END GENERATED OPTIONAL DEPENDENCIES
}
