# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

PYTHON_COMPAT=( python3_{12..15} )

inherit optfeature python-single-r1

DESCRIPTION="VanillaGreen desktop shell for Hyprland and Niri"
HOMEPAGE="https://github.com/vanillagreencom/vgs"
SRC_URI="https://github.com/vanillagreencom/vgs/releases/download/v${PV}/vgs-${PV}-source.tar.gz"
S="${WORKDIR}/vgs-${PV}"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~arm64"
IUSE="+extra-themes"
REQUIRED_USE="${PYTHON_REQUIRED_USE}"

RDEPEND="
	${PYTHON_DEPS}
	app-misc/jq
	gui-apps/quickshell
"
BDEPEND="dev-lang/go"

src_prepare() {
	default
	sed -i 's|^#!/bin/env bash$|#!/usr/bin/env bash|' \
		config/vshell/nvim/colorschemes/tokyonight.nvim/scripts/{build,docs} || die
}

src_compile() {
	cd backend || die
	go build -mod=vendor -buildvcs=false -trimpath \
		-ldflags="-s -w -X vshell/backend/internal/registry.cliVersion=${PV}" \
		-o "${T}/vshell-backend" ./cmd/vshell-backend || die
}

src_install() {
	DESTDIR="${D}" PREFIX=/usr VGS_THEME_BUNDLE=core \
		VGS_BACKEND_BINARY="${T}/vshell-backend" \
		"${S}/packaging/install-system.sh" || die

	if use extra-themes; then
		DESTDIR="${D}" PREFIX=/usr VGS_THEME_BUNDLE=extras \
			"${S}/packaging/install-system.sh" || die
	fi
}

pkg_postinst() {
	elog "VGS installs the user service but does not enable it automatically."
	elog "Start it for the current user with:"
	elog
	elog "  systemctl --user enable --now vshell.service"
	elog
	elog "Run 'vshell deps status' to inspect optional feature dependencies."
	elog

	# BEGIN GENERATED OPTIONAL DEPENDENCIES
	# Generated by scripts/gen-package-metadata.py from
	# config/vshell/dependencies.json and packaging/optional-packages.json.
	# Run scripts/gen-package-metadata.py --write after changing either file.
	optfeature "launcher recent-directory search" app-shells/zoxide
	optfeature "region OCR" app-text/tesseract
	optfeature "GTK theme, icon theme and color-scheme application, trash instead of deleting files, launcher default folder opener" dev-libs/glib
	optfeature "greeter and keyring integration" gnome-base/gnome-keyring
	optfeature "screenshots, region OCR" gui-apps/grim
	optfeature "screenshots, region OCR, screen recording" gui-apps/slurp
	optfeature "clipboard history, screenshots, region OCR, screen recording" gui-apps/wl-clipboard
	optfeature "greeter and keyring integration" gui-libs/greetd
	optfeature "font cache refresh after a font change" media-libs/fontconfig
	optfeature "screen recording" media-video/ffmpeg
	optfeature "file thumbnails" media-video/ffmpegthumbnailer
	optfeature "per-interface network usage" net-analyzer/bandwhich
	optfeature "AI usage widget" net-misc/curl
	optfeature "cloud file sync" net-misc/rclone
	optfeature "Tailscale widget" net-vpn/tailscale
	optfeature "faster launcher file search" sys-apps/fd
	optfeature "launcher text search" sys-apps/ripgrep
	optfeature "cloud sync streaming mounts" sys-fs/fuse
	optfeature "screenshots, region OCR, screen recording" x11-libs/libnotify
	# END GENERATED OPTIONAL DEPENDENCIES
}
