return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#1c1e26",
				bg = "#1c1e26",
				dark_bg = "#15161c",
				darker_bg = "#111217",
				lighter_bg = "#2a2c33",
				selection = "#26bbd9",
				selection_background = "#26bbd9",
				selection_foreground = "#1c1e26",
				foreground = "#fadad1",
				fg = "#fadad1",
				light_fg = "#faded6",
				bright_fg = "#fadad1",
				dark_fg = "#968584",
				muted = "#6c6f93",
				cursor = "#fadad1",
				accent = "#26bbd9",
				red = "#e95678",
				green = "#29d398",
				yellow = "#fab795",
				blue = "#26bbd9",
				purple = "#ee64ac",
				magenta = "#ee64ac",
				cyan = "#59e3e3",
				orange = "#ec6a88",
				brown = "#bd556d",
				bright_red = "#ec6a88",
				bright_green = "#3fdaa4",
				bright_yellow = "#fbc3a7",
				bright_blue = "#3fc4de",
				bright_purple = "#f075b5",
				bright_cyan = "#6be4e6",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
