[colors.primary]
background = "{background}"
foreground = "{foreground}"

[colors.normal]
black = "{terminal_black}"
red = "{terminal_red}"
green = "{terminal_green}"
yellow = "{terminal_yellow}"
blue = "{terminal_blue}"
magenta = "{terminal_magenta}"
cyan = "{terminal_cyan}"
white = "{terminal_white}"

[colors.bright]
black = "{terminal_bright_black}"
red = "{terminal_bright_red}"
green = "{terminal_bright_green}"
yellow = "{terminal_bright_yellow}"
blue = "{terminal_bright_blue}"
magenta = "{terminal_bright_magenta}"
cyan = "{terminal_bright_cyan}"
white = "{terminal_bright_white}"

[colors.cursor]
text = "{background}"
cursor = "{cursor}"

[colors.selection]
text = "{selection_foreground}"
background = "{selection_background}"
