# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1c1e26"

# Main text color
theme[main_fg]="#d5d8da"

# Title color for boxes
theme[title]="#d5d8da"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e95678"

# Background color of selected item in processes box
theme[selected_bg]="#2e303e"

# Foreground color of selected item in processes box
theme[selected_fg]="#d5d8da"

# Color of inactive/disabled text
theme[inactive_fg]="#6c6f93"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d5d8da"

# Background color of the percentage meters
theme[meter_bg]="#2e303e"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d5d8da"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#ee64ac"
theme[mem_box]="#29d398"
theme[net_box]="#e95678"
theme[proc_box]="#e95678"

# Box divider line and small boxes line color
theme[div_line]="#6c6f93"

# Temperature graph color
theme[temp_start]="#29d398"
theme[temp_mid]="#fab795"
theme[temp_end]="#e95678"

# CPU graph colors
theme[cpu_start]="#59e1e3"
theme[cpu_mid]="#26bbd9"
theme[cpu_end]="#ee64ac"

# Mem/Disk free meter
theme[free_start]="#ee64ac"
theme[free_mid]="#26bbd9"
theme[free_end]="#59e1e3"

# Mem/Disk cached meter
theme[cached_start]="#26bbd9"
theme[cached_mid]="#59e1e3"
theme[cached_end]="#ee64ac"

# Mem/Disk available meter
theme[available_start]="#fab795"
theme[available_mid]="#e95678"
theme[available_end]="#e95678"

# Mem/Disk used meter
theme[used_start]="#29d398"
theme[used_mid]="#59e1e3"
theme[used_end]="#26bbd9"

# Download graph colors
theme[download_start]="#fab795"
theme[download_mid]="#e95678"
theme[download_end]="#e95678"

# Upload graph colors
theme[upload_start]="#29d398"
theme[upload_mid]="#59e1e3"
theme[upload_end]="#26bbd9"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#59e1e3"
theme[process_mid]="#26bbd9"
theme[process_end]="#ee64ac"
