accent = "#9279aa"
cursor = "#F4B999"
foreground = "#F4B999"
background = "#0E1E36"
selection_foreground = "#F4B999"
selection_background = "#9279AA"

color0 = "#0E1E36"
color1 = "#D2495B"
color2 = "#BE6F76"
color3 = "#F4B999"
color4 = "#574F72"
color5 = "#763C5D"
color6 = "#9279AA"
color7 = "#FA7E75"
color8 = "#4A2036"
color9 = "#FA7E75"
color10 = "#C85670"
color11 = "#F4B999"
color12 = "#9279AA"
color13 = "#BE6F76"
color14 = "#C85670"
color15 = "#F4B999"
