accent = "#706e6b"
cursor = "#f0e4c5"
foreground = "#f0e4c5"
background = "#1c1b19"
selection_foreground = "#f0e4c5"
selection_background = "#706e6b"

color0 = "#1c1b19"
color1 = "#c5564a"
color2 = "#a89984"
color3 = "#ebdbb2"
color4 = "#908d88"
color5 = "#afa499"
color6 = "#d4bd99"
color7 = "#fbf1c7"
color8 = "#6b655c"
color9 = "#d94e38"
color10 = "#c2a571"
color11 = "#f7df97"
color12 = "#aaa090"
color13 = "#cbae8e"
color14 = "#e7c07c"
color15 = "#fff8e8"
