return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#292323",
				bg = "#292323",
				dark_bg = "#1f1a1a",
				darker_bg = "#191515",
				lighter_bg = "#363030",
				selection = "#a39eb8",
				selection_background = "#a39eb8",
				selection_foreground = "#dcd7d6",
				foreground = "#dcd7d6",
				fg = "#dcd7d6",
				light_fg = "#e0dbda",
				bright_fg = "#dcd7d6",
				dark_fg = "#8b8685",
				muted = "#877878",
				cursor = "#dcd7d6",
				accent = "#cb8c6d",
				red = "#a48484",
				green = "#af8a79",
				yellow = "#a88373",
				blue = "#a39eb8",
				purple = "#bea7bd",
				magenta = "#bea7bd",
				cyan = "#b0b7c5",
				orange = "#ccb8b8",
				brown = "#a39393",
				bright_red = "#ccb8b8",
				bright_green = "#be9c8e",
				bright_yellow = "#bd9c8f",
				bright_blue = "#d5d2df",
				bright_purple = "#e5dbe5",
				bright_cyan = "#e5e7ec",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
