return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#0c0b0c",
				bg = "#0c0b0c",
				dark_bg = "#090809",
				darker_bg = "#070707",
				lighter_bg = "#1b1a1b",
				selection = "#fafcfb",
				selection_background = "#fafcfb",
				selection_foreground = "#0c0b0c",
				foreground = "#fafcfb",
				fg = "#fafcfb",
				light_fg = "#fafcfb",
				bright_fg = "#e2dddc",
				dark_fg = "#8f908f",
				muted = "#584e51",
				cursor = "#e2dddc",
				accent = "#b59790",
				red = "#c38b7b",
				green = "#87a9b0",
				yellow = "#6b5e73",
				blue = "#b59790",
				purple = "#c4d8e2",
				magenta = "#c4d8e2",
				cyan = "#a5a0b6",
				orange = "#c38b7b",
				brown = "#9c6f62",
				bright_red = "#c38b7b",
				bright_green = "#87a9b0",
				bright_yellow = "#6b5e73",
				bright_blue = "#b59790",
				bright_purple = "#c4d8e2",
				bright_cyan = "#a5a0b6",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
