# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282a36"

theme[main_fg]="#f8f8f2"

theme[title]="#f8f8f2"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#6272a4"

# Background color of selected item in processes box
theme[selected_bg]="#ff79c6"

# Foreground color of selected item in processes box
theme[selected_fg]="#f8f8f2"

theme[inactive_fg]="#44475a"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#f8f8f2"

theme[meter_bg]="#44475a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#bd93f9"

theme[cpu_box]="#bd93f9"

theme[mem_box]="#50fa7b"

theme[net_box]="#ff5555"

theme[proc_box]="#8be9fd"

theme[div_line]="#44475a"

theme[temp_start]="#bd93f9"
theme[temp_mid]="#ff79c6"
theme[temp_end]="#ff33a8"

theme[cpu_start]="#bd93f9"
theme[cpu_mid]="#8be9fd"
theme[cpu_end]="#50fa7b"

theme[free_start]="#ffa6d9"
theme[free_mid]="#ff79c6"
theme[free_end]="#ff33a8"

theme[cached_start]="#b1f0fd"
theme[cached_mid]="#8be9fd"
theme[cached_end]="#26d7fd"

theme[available_start]="#ffd4a6"
theme[available_mid]="#ffb86c"
theme[available_end]="#ff9c33"

theme[used_start]="#96faaf"
theme[used_mid]="#50fa7b"
theme[used_end]="#0dfa49"

theme[download_start]="#bd93f9"
theme[download_mid]="#50fa7b"
theme[download_end]="#8be9fd"

theme[upload_start]="#8c42ab"
theme[upload_mid]="#ff79c6"
theme[upload_end]="#ff33a8"

theme[process_start]="#50fa7b"
theme[process_mid]="#59b690"
theme[process_end]="#6272a4"
