;;; vgs-theme-theme.el --- Enhanced theme using VGS theme roles with VGS ANSI colors -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Generated (Enhanced)
;; Version: 1.3
;; Package-Requires: ((emacs "24.1"))
;; Keywords: faces

;;; Commentary:

;; Emacs theme rendered from VGS theme roles and ANSI colors.

;;; Code:

(deftheme vgs-theme "Enhanced theme using VGS theme roles with VGS ANSI color integration.")

(let* ((bg "{background}")
      (err "{color1}")
      (err-container "{errorContainer}")
      (on-background "{foreground}")
      (on-err "{onError}")
      (on-err-container "{onErrorContainer}")
      (on-primary "{onPrimary}")
      (on-primary-container "{onPrimaryContainer}")
      (on-secondary "{onSecondary}")
      (on-secondary-container "{onSecondaryContainer}")
      (on-surface "{foreground}")
      (on-surface-variant "{muted}")
      (on-tertiary "{onTertiary}")
      (on-tertiary-container "{onTertiaryContainer}")
      (outline-color "{outline}")
      (outline-variant "{outlineVariant}")
      (primary "{primary}")
      (primary-container "{primaryContainer}")
      (secondary "{secondary}")
      (secondary-container "{secondaryContainer}")
      (shadow "{shadow}")
      (surface "{surface}")
      (surface-container "{surfaceContainerHigh}")
      (surface-container-high "{surfaceContainerHighest}")
      (surface-container-highest "{surfaceContainerHigh}")
      (surface-container-low "{surfaceContainerLow}")
      (surface-container-lowest "{surfaceContainerLowest}")
      (surface-variant "{surfaceVariant}")
      (tertiary "{tertiary}")
      (tertiary-container "{tertiaryContainer}")

      (vgs-red "{color1}")
      (vgs-red-alt "{color9}")
      (vgs-green "{color2}")
      (vgs-green-bright "{color10}")
      (vgs-yellow "{color3}")
      (vgs-yellow-bright "{color11}")
      (vgs-blue "{color4}")
      (vgs-magenta "{color5}")
      (vgs-cyan "{color6}")
      (vgs-cyan-bright "{color12}")
      (vgs-cyan-dark "{color13}")
      (vgs-teal "{color14}")
      (vgs-fg "{color7}")
      (vgs-gray "{color8}")
      (vgs-white "{color15}")

      (success "{color2}")
      (on-success "{onTertiary}")
      (success-container "{tertiaryContainer}")
      (on-success-container "{onTertiaryContainer}")

      (primary-fixed "{primaryContainer}")
      (primary-fixed-dim "{primary}")
      (secondary-fixed "{secondaryContainer}")
      (secondary-fixed-dim "{secondary}")
      (tertiary-fixed "{tertiaryContainer}")
      (tertiary-fixed-dim "{tertiary}")
      (on-primary-fixed "{onPrimaryContainer}")
      (on-primary-fixed-variant "{onPrimaryContainer}")
      (on-secondary-fixed "{onSecondaryContainer}")
      (on-secondary-fixed-variant "{onSecondaryContainer}")
      (on-tertiary-fixed "{onTertiaryContainer}")
      (on-tertiary-fixed-variant "{onTertiaryContainer}")

      (inverse-on-surface "{inverseOnSurface}")
      (inverse-primary "{inversePrimary}")
      (inverse-surface "{inverseSurface}")

      (term0 "{color0}")
      (term1 "{color1}")
      (term2 "{color2}")
      (term3 "{color3}")
      (term4 "{color4}")
      (term5 "{color5}")
      (term6 "{color6}")
      (term7 "{color7}")
      (term8 "{color8}")
      (term9 "{color9}")
      (term10 "{color10}")
      (term11 "{color11}")
      (term12 "{color12}")
      (term13 "{color13}")
      (term14 "{color14}")
      (term15 "{color15}"))

  (custom-theme-set-faces
   'vgs-theme
   `(default ((t (:background ,bg :foreground ,on-background))))
   `(cursor ((t (:background ,vgs-cyan-bright))))
   `(highlight ((t (:background ,primary-container :foreground ,on-primary-container))))
   `(region ((t (:background ,primary-container :foreground ,vgs-cyan-bright :extend t))))
   `(secondary-selection ((t (:background ,secondary-container :foreground ,on-secondary-container :extend t))))
   `(isearch ((t (:background ,vgs-yellow :foreground ,bg :weight bold))))
   `(lazy-highlight ((t (:background ,secondary-container :foreground ,vgs-yellow-bright))))
   `(vertical-border ((t (:foreground ,surface-variant))))
   `(border ((t (:background ,surface-variant :foreground ,surface-variant))))
   `(fringe ((t (:background ,surface :foreground ,vgs-gray))))
   `(shadow ((t (:foreground ,vgs-gray))))
   `(link ((t (:foreground ,vgs-cyan-bright :underline t))))
   `(link-visited ((t (:foreground ,vgs-magenta :underline t))))
   `(success ((t (:foreground ,success))))
   `(warning ((t (:foreground ,vgs-yellow))))
   `(error ((t (:foreground ,err))))
   `(match ((t (:background ,vgs-yellow :foreground ,bg :weight bold))))

   `(font-lock-builtin-face ((t (:foreground ,vgs-cyan-bright))))
   `(font-lock-comment-face ((t (:foreground ,vgs-gray :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,outline-variant))))
   `(font-lock-constant-face ((t (:foreground ,vgs-yellow-bright :weight bold))))
   `(font-lock-doc-face ((t (:foreground ,vgs-fg :slant italic))))
   `(font-lock-function-name-face ((t (:foreground ,vgs-cyan :weight bold))))
   `(font-lock-keyword-face ((t (:foreground ,vgs-red-alt :weight bold))))
   `(font-lock-string-face ((t (:foreground ,vgs-green))))
   `(font-lock-type-face ((t (:foreground ,vgs-yellow))))
   `(font-lock-variable-name-face ((t (:foreground ,vgs-fg))))
   `(font-lock-warning-face ((t (:foreground ,err :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,vgs-teal))))
   `(font-lock-negation-char-face ((t (:foreground ,vgs-red))))

   `(show-paren-match ((t (:background ,primary-container :foreground ,vgs-cyan-bright :weight bold))))
   `(show-paren-mismatch ((t (:background ,err-container :foreground ,on-err-container :weight bold))))

   `(mode-line ((t (:background ,surface-container :foreground ,on-surface :box nil))))
   `(mode-line-inactive ((t (:background ,surface :foreground ,vgs-gray :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,vgs-cyan :weight bold))))
   `(mode-line-emphasis ((t (:foreground ,vgs-cyan :weight bold))))
   `(mode-line-highlight ((t (:foreground ,vgs-cyan-bright :box nil))))

   `(org-block ((t (:background ,surface-container-low :extend t :inherit fixed-pitch))))
   `(org-block-begin-line ((t (:background ,surface-container-low :foreground ,vgs-teal :extend t :slant italic :inherit fixed-pitch))))
   `(org-block-end-line ((t (:background ,surface-container-low :foreground ,vgs-teal :extend t :slant italic :inherit fixed-pitch))))
   `(org-code ((t (:background ,surface-container-low :foreground ,vgs-yellow-bright :inherit fixed-pitch))))
   `(org-verbatim ((t (:background ,surface-container-low :foreground ,vgs-cyan :inherit fixed-pitch))))
   `(org-meta-line ((t (:foreground ,vgs-gray :slant italic))))

   `(org-level-1 ((t (:foreground ,vgs-cyan :weight bold :height 1.2))))
   `(org-level-2 ((t (:foreground ,vgs-blue :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,vgs-magenta :weight bold))))
   `(org-level-4 ((t (:foreground ,vgs-green :weight bold))))
   `(org-level-5 ((t (:foreground ,vgs-yellow :weight bold))))
   `(org-level-6 ((t (:foreground ,vgs-cyan-bright :weight bold))))
   `(org-level-7 ((t (:foreground ,vgs-red-alt :weight bold))))
   `(org-level-8 ((t (:foreground ,vgs-teal :weight bold))))
   `(org-document-title ((t (:foreground ,vgs-cyan :weight bold :height 1.3))))
   `(org-document-info ((t (:foreground ,vgs-blue))))
   `(org-todo ((t (:foreground ,vgs-red :weight bold))))
   `(org-done ((t (:foreground ,success :weight bold))))
   `(org-headline-done ((t (:foreground ,vgs-gray))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-ellipsis ((t (:foreground ,vgs-blue :underline nil))))
   `(org-table ((t (:foreground ,vgs-magenta :inherit fixed-pitch))))
   `(org-formula ((t (:foreground ,vgs-yellow-bright :inherit fixed-pitch))))
   `(org-checkbox ((t (:foreground ,vgs-cyan :weight bold :inherit fixed-pitch))))
   `(org-date ((t (:foreground ,vgs-teal :underline t))))
   `(org-special-keyword ((t (:foreground ,vgs-gray :slant italic))))
   `(org-tag ((t (:foreground ,vgs-gray :weight normal))))

   `(magit-section-highlight ((t (:background ,surface-container-low))))
   `(magit-diff-hunk-heading ((t (:background ,surface-container :foreground ,vgs-gray))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,surface-container-high :foreground ,on-surface))))
   `(magit-diff-context ((t (:foreground ,vgs-gray))))
   `(magit-diff-context-highlight ((t (:background ,surface-container-low :foreground ,on-surface))))
   `(magit-diff-added ((t (:background ,success-container :foreground ,vgs-green-bright))))
   `(magit-diff-added-highlight ((t (:background ,success-container :foreground ,vgs-green-bright :weight bold))))
   `(magit-diff-removed ((t (:background ,err-container :foreground ,vgs-red-alt))))
   `(magit-diff-removed-highlight ((t (:background ,err-container :foreground ,vgs-red-alt :weight bold))))
   `(magit-hash ((t (:foreground ,vgs-gray))))
   `(magit-branch-local ((t (:foreground ,vgs-blue :weight bold))))
   `(magit-branch-remote ((t (:foreground ,vgs-cyan :weight bold))))

   `(company-tooltip ((t (:background ,surface-container :foreground ,on-surface))))
   `(company-tooltip-selection ((t (:background ,primary-container :foreground ,vgs-cyan-bright))))
   `(company-tooltip-common ((t (:foreground ,vgs-cyan))))
   `(company-tooltip-common-selection ((t (:foreground ,vgs-cyan-bright :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,vgs-yellow))))
   `(company-scrollbar-fg ((t (:background ,vgs-cyan))))
   `(company-scrollbar-bg ((t (:background ,surface-variant))))
   `(company-preview ((t (:foreground ,vgs-gray :slant italic))))
   `(company-preview-common ((t (:foreground ,vgs-cyan :slant italic))))

   `(ido-first-match ((t (:foreground ,vgs-cyan :weight bold))))
   `(ido-only-match ((t (:foreground ,vgs-green :weight bold))))
   `(ido-subdir ((t (:foreground ,vgs-blue))))
   `(ido-indicator ((t (:foreground ,vgs-red))))
   `(ido-virtual ((t (:foreground ,vgs-gray))))

   `(helm-selection ((t (:background ,primary-container :foreground ,vgs-cyan-bright))))
   `(helm-match ((t (:foreground ,vgs-cyan :weight bold))))
   `(helm-source-header ((t (:background ,surface-container-high :foreground ,vgs-cyan :weight bold :height 1.1))))
   `(helm-candidate-number ((t (:foreground ,vgs-yellow :weight bold))))
   `(helm-ff-directory ((t (:foreground ,vgs-cyan :weight bold))))
   `(helm-ff-file ((t (:foreground ,on-surface))))
   `(helm-ff-executable ((t (:foreground ,vgs-green))))

   `(corfu-default ((t (:background ,surface-container :foreground ,on-surface))))
   `(corfu-current ((t (:background ,primary-container :foreground ,vgs-cyan-bright))))

   `(which-key-key-face ((t (:foreground ,vgs-cyan :weight bold))))
   `(which-key-separator-face ((t (:foreground ,outline-variant))))
   `(which-key-command-description-face ((t (:foreground ,on-surface))))
   `(which-key-group-description-face ((t (:foreground ,vgs-blue))))
   `(which-key-special-key-face ((t (:foreground ,vgs-yellow :weight bold))))

   `(line-number ((t (:foreground ,vgs-gray :inherit default))))
   `(line-number-current-line ((t (:foreground ,vgs-cyan :weight bold :inherit default))))

   `(sp-show-pair-match-face ((t (:background ,primary-container :foreground ,vgs-cyan-bright))))
   `(sp-show-pair-mismatch-face ((t (:background ,err-container :foreground ,on-err-container))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground ,vgs-cyan))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,vgs-yellow))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,vgs-green))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,vgs-blue))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,vgs-magenta))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,vgs-cyan-bright))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,vgs-yellow-bright))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,vgs-green-bright))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,vgs-red-alt))))
   `(rainbow-delimiters-mismatched-face ((t (:foreground ,err :weight bold))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,err :weight bold))))

   `(dired-directory ((t (:foreground ,vgs-cyan :weight bold))))
   `(dired-ignored ((t (:foreground ,vgs-gray))))
   `(dired-flagged ((t (:foreground ,vgs-red))))
   `(dired-marked ((t (:foreground ,vgs-yellow :weight bold))))
   `(dired-symlink ((t (:foreground ,vgs-magenta :slant italic))))
   `(dired-header ((t (:foreground ,vgs-cyan :weight bold :height 1.1))))

   `(term-color-black ((t (:foreground ,term0 :background ,term0))))
   `(term-color-red ((t (:foreground ,term1 :background ,term1))))
   `(term-color-green ((t (:foreground ,term2 :background ,term2))))
   `(term-color-yellow ((t (:foreground ,term3 :background ,term3))))
   `(term-color-blue ((t (:foreground ,term4 :background ,term4))))
   `(term-color-magenta ((t (:foreground ,term5 :background ,term5))))
   `(term-color-cyan ((t (:foreground ,term6 :background ,term6))))
   `(term-color-white ((t (:foreground ,term7 :background ,term7))))

   `(eshell-prompt ((t (:foreground ,vgs-cyan :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,vgs-cyan :weight bold))))
   `(eshell-ls-symlink ((t (:foreground ,vgs-magenta :slant italic))))
   `(eshell-ls-executable ((t (:foreground ,vgs-green))))
   `(eshell-ls-archive ((t (:foreground ,vgs-yellow))))
   `(eshell-ls-backup ((t (:foreground ,vgs-gray))))
   `(eshell-ls-clutter ((t (:foreground ,vgs-red))))
   `(eshell-ls-missing ((t (:foreground ,vgs-red))))
   `(eshell-ls-product ((t (:foreground ,on-surface-variant))))
   `(eshell-ls-readonly ((t (:foreground ,vgs-gray))))
   `(eshell-ls-special ((t (:foreground ,vgs-blue))))
   `(eshell-ls-unreadable ((t (:foreground ,vgs-gray))))

   `(markdown-header-face ((t (:foreground ,vgs-cyan :weight bold))))
   `(markdown-header-face-1 ((t (:foreground ,vgs-cyan :weight bold :height 1.2))))
   `(markdown-header-face-2 ((t (:foreground ,vgs-blue :weight bold :height 1.1))))
   `(markdown-header-face-3 ((t (:foreground ,vgs-magenta :weight bold))))
   `(markdown-header-face-4 ((t (:foreground ,vgs-green :weight bold))))
   `(markdown-inline-code-face ((t (:foreground ,vgs-yellow-bright :background ,surface-container-low :inherit fixed-pitch))))
   `(markdown-code-face ((t (:background ,surface-container-low :extend t :inherit fixed-pitch))))
   `(markdown-pre-face ((t (:background ,surface-container-low :inherit fixed-pitch))))
   `(markdown-table-face ((t (:foreground ,vgs-magenta :inherit fixed-pitch))))

   `(web-mode-html-tag-face ((t (:foreground ,vgs-cyan))))
   `(web-mode-html-tag-bracket-face ((t (:foreground ,vgs-gray))))
   `(web-mode-html-attr-name-face ((t (:foreground ,vgs-yellow))))
   `(web-mode-html-attr-value-face ((t (:foreground ,vgs-green))))
   `(web-mode-css-selector-face ((t (:foreground ,vgs-cyan))))
   `(web-mode-css-property-name-face ((t (:foreground ,vgs-blue))))
   `(web-mode-css-string-face ((t (:foreground ,vgs-green))))

   `(flycheck-error ((t (:underline (:style wave :color ,err)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,vgs-yellow)))))
   `(flycheck-info ((t (:underline (:style wave :color ,vgs-blue)))))
   `(flycheck-fringe-error ((t (:foreground ,err))))
   `(flycheck-fringe-warning ((t (:foreground ,vgs-yellow))))
   `(flycheck-fringe-info ((t (:foreground ,vgs-blue))))

   `(minibuffer-prompt ((t (:foreground ,vgs-cyan :weight bold))))

   `(lsp-face-highlight-textual ((t (:background ,primary-container :foreground ,vgs-cyan-bright :weight bold))))
   `(lsp-face-highlight-read ((t (:background ,secondary-container :foreground ,vgs-yellow-bright :weight bold))))
   `(lsp-face-highlight-write ((t (:background ,tertiary-container :foreground ,vgs-green-bright :weight bold))))

   `(info-title-1 ((t (:foreground ,vgs-cyan :weight bold :height 1.3))))
   `(info-title-2 ((t (:foreground ,vgs-blue :weight bold :height 1.2))))
   `(info-title-3 ((t (:foreground ,vgs-magenta :weight bold :height 1.1))))
   `(info-title-4 ((t (:foreground ,vgs-green :weight bold))))
   `(Info-quoted ((t (:foreground ,vgs-yellow))))
   `(info-menu-header ((t (:foreground ,vgs-cyan :weight bold))))
   `(info-menu-star ((t (:foreground ,vgs-cyan))))
   `(info-node ((t (:foreground ,vgs-blue :weight bold))))

   `(tab-bar ((t (:background ,surface-container :foreground ,on-surface :box nil))))
   `(tab-bar-tab ((t (:background ,surface-container-high :foreground ,vgs-cyan :weight bold :box nil))))
   `(tab-bar-tab-inactive ((t (:background ,surface :foreground ,vgs-gray :box nil))))

   `(tab-line ((t (:background ,surface-container :foreground ,on-surface :box nil))))
   `(tab-line-tab ((t (:background ,surface :foreground ,vgs-gray :box nil))))
   `(tab-line-tab-current ((t (:background ,surface-container-high :foreground ,vgs-cyan :weight bold :box nil))))
   `(tab-line-tab-inactive ((t (:background ,surface :foreground ,vgs-gray :box nil))))
   `(tab-line-highlight ((t (:background ,surface-container-highest :foreground ,vgs-cyan-bright))))

   `(centaur-tabs-default ((t (:background ,surface-container :foreground ,on-surface))))
   `(centaur-tabs-selected ((t (:background ,surface-container-high :foreground ,vgs-cyan :weight bold))))
   `(centaur-tabs-unselected ((t (:background ,surface :foreground ,vgs-gray))))
   `(centaur-tabs-selected-modified ((t (:background ,surface-container-high :foreground ,vgs-yellow :weight bold))))
   `(centaur-tabs-unselected-modified ((t (:background ,surface :foreground ,vgs-yellow))))
   `(centaur-tabs-active-bar-face ((t (:background ,vgs-cyan))))

   `(fixed-pitch ((t (:family "monospace"))))
   `(fixed-pitch-serif ((t (:family "monospace serif"))))

   `(variable-pitch ((t (:family "sans serif"))))
   ))

(with-eval-after-load 'org
  (setq org-hide-leading-stars t)
  (setq org-startup-indented t))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'vgs-theme)
;;; vgs-theme-theme.el ends here
