theme[main_bg]="#FFFCF0"

theme[main_fg]="#100F0F"

theme[title]="#100F0F"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#205EA6"

# Background color of selected item in processes box
theme[selected_bg]="#414868"

# Foreground color of selected item in processes box
theme[selected_fg]="#100F0F"

theme[inactive_fg]="#6F6E69"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#205EA6"

theme[cpu_box]="#6F6E69"

theme[mem_box]="#6F6E69"

theme[net_box]="#6F6E69"

theme[proc_box]="#6F6E69"

theme[div_line]="#6F6E69"

theme[temp_start]="#66800B"
theme[temp_mid]="#BC5215"
theme[temp_end]="#AF3029"

theme[cpu_start]="#66800B"
theme[cpu_mid]="#BC5215"
theme[cpu_end]="#AF3029"

theme[free_start]="#66800B"
theme[free_mid]="#BC5215"
theme[free_end]="#AF3029"

theme[cached_start]="#66800B"
theme[cached_mid]="#BC5215"
theme[cached_end]="#AF3029"

theme[available_start]="#66800B"
theme[available_mid]="#BC5215"
theme[available_end]="#AF3029"

theme[used_start]="#66800B"
theme[used_mid]="#BC5215"
theme[used_end]="#AF3029"

theme[download_start]="#66800B"
theme[download_mid]="#BC5215"
theme[download_end]="#AF3029"

theme[upload_start]="#66800B"
theme[upload_mid]="#BC5215"
theme[upload_end]="#AF3029"
