accent = "#bd93f9"
cursor = "#BD93F9"
foreground = "#E9E4F5"
background = "#1F1A2E"
selection_foreground = "#E9E4F5"
selection_background = "#3A3457"

color0 = "#1A1625"
color1 = "#FF5555"
color2 = "#6FB3A8"
color3 = "#EADDA6"
color4 = "#5B8FB9"
color5 = "#BD93F9"
color6 = "#406E82"
color7 = "#E9E4F5"
color8 = "#4D4266"
color9 = "#FF79C6"
color10 = "#8BD0C1"
color11 = "#F1FA8C"
color12 = "#8BE9FD"
color13 = "#FF79C6"
color14 = "#4C84A0"
color15 = "#FFFFFF"
