accent = "#b44a4a"
cursor = "#eaeaea"
foreground = "#F2E8E8"
background = "#1b1112"
selection_foreground = "#F2E8E8"
selection_background = "#372223"

color0 = "#1A0E0E"
color1 = "#B44A4A"
color2 = "#C05A5A"
color3 = "#D66B6B"
color4 = "#D66B6B"
color5 = "#D66B6B"
color6 = "#F48A8A"
color7 = "#F2E8E8"
color8 = "#2B1818"
color9 = "#C85C5C"
color10 = "#D97171"
color11 = "#E87F7F"
color12 = "#E59393"
color13 = "#F2A3A3"
color14 = "#F7B3B3"
color15 = "#FFF1F1"
