theme[main_bg]="#111c18"

theme[main_fg]="#F7E8B2"

theme[title]="#D6D5BC"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#E67D64"

# Background color of selected items
theme[selected_bg]="#364538"

# Foreground color of selected items
theme[selected_fg]="#DEB266"

theme[inactive_fg]="#32473B"  

# Color of text appearing on top of graphs
theme[graph_text]="#E6D8BA"

theme[proc_misc]="#E6D8BA"

theme[cpu_box]="#81B8A8"

theme[mem_box]="#81B8A8"

theme[net_box]="#81B8A8"

theme[proc_box]="#81B8A8"

theme[div_line]="#81B8A8"

theme[temp_start]="#BFD99A"
theme[temp_mid]="#E1B55E"
theme[temp_end]="#DBB05C"

theme[cpu_start]="#5F8C86"
theme[cpu_mid]="#629C89"
theme[cpu_end]="#76AD98"

theme[free_start]="#5F8C86"
theme[free_mid]="#629C89"
theme[free_end]="#76AD98"

theme[cached_start]="#5F8C86"
theme[cached_mid]="#629C89"
theme[cached_end]="#76AD98"

theme[available_start]="#5F8C86"
theme[available_mid]="#629C89"
theme[available_end]="#76AD98"

theme[used_start]="#5F8C86"
theme[used_mid]="#629C89"
theme[used_end]="#76AD98"

theme[download_start]="#75BBB3"
theme[download_mid]="#61949A"
theme[download_end]="#215866"

theme[upload_start]="#215866"
theme[upload_mid]="#91C080"
theme[upload_end]="#549E6A"

theme[process_start]="#72CFA3"
theme[process_mid]="#D0D494"
theme[process_end]="#DB9F9C"

