return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#2c2e27",
				bg = "#2c2e27",
				dark_bg = "#21221d",
				darker_bg = "#1a1c17",
				lighter_bg = "#393b34",
				selection = "#c6d0b6",
				selection_background = "#c6d0b6",
				selection_foreground = "#2c2e27",
				foreground = "#fdfefd",
				fg = "#fdfefd",
				light_fg = "#fdfefd",
				bright_fg = "#fdfefd",
				dark_fg = "#9fa09d",
				muted = "#a2a49a",
				cursor = "#fdfefd",
				accent = "#c6d0b6",
				red = "#d9bc87",
				green = "#d2dfc1",
				yellow = "#dfdfb9",
				blue = "#c6d0b6",
				purple = "#cfc9af",
				magenta = "#cfc9af",
				cyan = "#c1cead",
				orange = "#eedec3",
				brown = "#beb29c",
				bright_red = "#eedec3",
				bright_green = "#f6f9f3",
				bright_yellow = "#f8f8ee",
				bright_blue = "#ebefe5",
				bright_purple = "#eceae0",
				bright_cyan = "#e6ecdd",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
