%global debug_package %{nil}

Name:           vgs-shell
Version:        0.1.0
Release:        1%{?dist}
Summary:        VanillaGreen desktop shell for Hyprland and Niri
AutoReqProv:     no
License:        MIT
URL:            https://github.com/vanillagreencom/vgs
Source0:        %{url}/releases/download/v%{version}/vgs-%{version}-source.tar.gz
BuildRequires:  golang
Requires:       quickshell
Requires:       jq
Requires:       python3
Requires:       bash
Requires:       coreutils
Requires:       systemd

# BEGIN GENERATED OPTIONAL DEPENDENCIES
# Generated by scripts/gen-package-metadata.py from
# config/vshell/dependencies.json and packaging/optional-packages.json.
# Run scripts/gen-package-metadata.py --write after changing either file.
# terminal for VGS password prompts
Suggests:       alacritty
# AI usage widget
Suggests:       curl
# faster launcher file search
Suggests:       fd-find
# screen recording
Suggests:       ffmpeg-free
# file thumbnails
Suggests:       ffmpegthumbnailer
# font cache refresh after a font change
Suggests:       fontconfig
# terminal for VGS password prompts
Suggests:       foot
# cloud sync streaming mounts
Suggests:       fuse3
# GTK theme, icon theme and color-scheme application, trash instead of deleting files, launcher default folder opener
Suggests:       glib2
# greeter and keyring integration
Suggests:       gnome-keyring
# greeter and keyring integration
Suggests:       greetd
# screenshots, region OCR
Suggests:       grim
# Hyprland compositor support
Suggests:       hyprland
# screenshots, region OCR, screen recording
Suggests:       hyprpicker
# terminal for VGS password prompts
Suggests:       kitty
# screenshots, region OCR, screen recording
Suggests:       libnotify
# Niri compositor support
Suggests:       niri
# cloud file sync
Suggests:       rclone
# launcher text search
Suggests:       ripgrep
# screenshots, region OCR, screen recording
Suggests:       slurp
# privileged actions run from the shell, sudoers validation before a drop-in is installed
Suggests:       sudo
# Tailscale widget
Suggests:       tailscale
# region OCR
Suggests:       tesseract
# region OCR
Suggests:       tesseract-langpack-eng
# clipboard history, screenshots, region OCR, screen recording
Suggests:       wl-clipboard
# night light
Suggests:       wlsunset
# terminal for VGS password prompts
Suggests:       xterm
# launcher recent-directory search
Suggests:       zoxide
# END GENERATED OPTIONAL DEPENDENCIES

%description
VGS is a Quickshell desktop shell for Hyprland and Niri.
Optional features stay inert until their tool is installed; run
"vshell deps status" to see which feature groups are unsatisfied.

%package        assets
Summary:        Optional VGS themes, wallpapers, and bundled icon themes
Requires:       %{name} = %{version}-%{release}

%description    assets
The vgs-shell package ships the coppernight default theme only. This package
adds every other bundled theme, its wallpapers, and the vendored icon themes.

%prep
%autosetup -n vgs-%{version}
sed -i 's|^#!/bin/env bash$|#!/usr/bin/env bash|' \
  config/vshell/nvim/colorschemes/tokyonight.nvim/scripts/{build,docs}

%build
cd backend
CGO_ENABLED=0 go build -mod=vendor -buildvcs=false -trimpath -ldflags='-s -w -X vshell/backend/internal/registry.cliVersion=%{version}' -o ../vshell-backend ./cmd/vshell-backend

%install
DESTDIR=%{buildroot} VGS_THEME_BUNDLE=core VGS_BACKEND_BINARY="$PWD/vshell-backend" packaging/install-system.sh
DESTDIR=%{buildroot} VGS_THEME_BUNDLE=extras packaging/install-system.sh

%post
cat <<'EOF'
VGS installs the user service but does not enable it automatically.
Start it for the current user with:

  systemctl --user enable --now vshell.service

Run vshell deps status to inspect optional feature dependencies.
EOF

%files
%license LICENSE
%doc README.md
%{_bindir}/vshell
%dir /usr/lib/vshell
/usr/lib/vshell/bin/
/usr/lib/vshell/quickshell/
/usr/lib/vshell/third_party/
/usr/lib/vshell/config/
%exclude /usr/lib/vshell/config/vshell/icons
/usr/lib/vshell/README.md
/usr/lib/vshell/LICENSE
/usr/lib/vshell/VERSION
%dir /usr/lib/vshell/themes
/usr/lib/vshell/themes/coppernight/
/usr/lib/vshell/themes/targets/
/usr/lib/vshell/themes/BACKGROUNDS-ATTRIBUTION.md
/usr/lib/vshell/themes/THEMES-ATTRIBUTION.md
/usr/lib/systemd/user/vshell.service

%files assets
/usr/lib/vshell/config/vshell/icons/
/usr/lib/vshell/themes/*
%exclude /usr/lib/vshell/themes/coppernight
%exclude /usr/lib/vshell/themes/targets
%exclude /usr/lib/vshell/themes/BACKGROUNDS-ATTRIBUTION.md
%exclude /usr/lib/vshell/themes/THEMES-ATTRIBUTION.md

%changelog
* Sun Jul 26 2026 Brad <brad@vanillagreen> - 0.1.0-1
- Initial package