accent = "#add7ff"
cursor = "#e4f0fb"
foreground = "#a6accd"
background = "#1b1e28"
selection_foreground = "#f8f8f2"
selection_background = "#2a2e3f"

color0 = "#1b1e28"
color1 = "#d0679d"
color2 = "#5de4c7"
color3 = "#fffac2"
color4 = "#89ddff"
color5 = "#d2a6ff"
color6 = "#add7ff"
color7 = "#ffffff"
color8 = "#6c6f93"
color9 = "#d0679d"
color10 = "#5de4c7"
color11 = "#fffac2"
color12 = "#89ddff"
color13 = "#d2a6ff"
color14 = "#add7ff"
color15 = "#ffffff"
