return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#050111",
				bg = "#050111",
				dark_bg = "#04010d",
				darker_bg = "#03010a",
				lighter_bg = "#14101f",
				selection = "#c9ffff",
				selection_background = "#c9ffff",
				selection_foreground = "#050111",
				foreground = "#c9ffff",
				fg = "#c9ffff",
				light_fg = "#ceffff",
				bright_fg = "#c9ffff",
				dark_fg = "#718d94",
				muted = "#2e2158",
				cursor = "#c9ffff",
				accent = "#450090",
				red = "#9f34f3",
				green = "#4efaff",
				yellow = "#46d6fd",
				blue = "#7d7bdb",
				purple = "#ae7aeb",
				magenta = "#ae7aeb",
				cyan = "#39d4fe",
				orange = "#c985fe",
				brown = "#a16acb",
				bright_red = "#c985fe",
				bright_green = "#aafdff",
				bright_yellow = "#a0ebff",
				bright_blue = "#c2c1f1",
				bright_purple = "#dec8f9",
				bright_cyan = "#94e8ff",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
