local Util = require("aether.utils")

local M = {}

---@type aether.HighlightsFn
function M.get(c, opts)
  -- stylua: ignore
  return {
    Comment                     = { fg = c.muted, style = opts.styles.comments }, -- any comment
    ColorColumn                 = { bg = c.black }, -- used for the columns set with 'colorcolumn'
    Conceal                     = { fg = c.dark_fg }, -- placeholder characters substituted for concealed text
    Cursor                      = { fg = c.bg, bg = c.fg }, -- character under the cursor
    lCursor                     = { fg = c.bg, bg = c.fg },
    CursorIM                    = { fg = c.bg, bg = c.fg },
    CursorColumn                = { bg = c.lighter_bg },
    CursorLine                  = { bg = c.cursorline_bg },
    Directory                   = { fg = c.blue, bold = true },
    DiffAdd                     = { bg = c.diff.add },
    DiffChange                  = { bg = c.diff.change },
    DiffDelete                  = { bg = c.diff.delete },
    DiffText                    = { bg = c.diff.text },
    EndOfBuffer                 = { fg = c.bg },
    ErrorMsg                    = { fg = c.bright_red, bold = true },
    VertSplit                   = { fg = c.border },
    WinSeparator                = { fg = c.border, bold = true },
    Folded                      = { fg = c.bright_blue, bg = Util.blend_bg(c.fg, 0.1), style = opts.styles.comments },
    FoldColumn                  = { bg = opts.transparent and c.none or c.bg, fg = c.muted },
    SignColumn                  = { bg = opts.transparent and c.none or c.bg, fg = c.muted },
    SignColumnSB                = { bg = c.bg_sidebar, fg = c.muted },
    Substitute                  = { bg = c.red, fg = c.bg },
    LineNr                      = { fg = c.muted },
    CursorLineNr                = { fg = c.orange, bold = true },
    LineNrAbove                 = { fg = c.muted },
    LineNrBelow                 = { fg = c.muted },
    MatchParen                  = { fg = c.orange, bold = true },
    ModeMsg                     = { fg = c.dark_fg, bold = true },
    MsgArea                     = { fg = c.dark_fg },
    MoreMsg                     = { fg = c.blue, bold = true },
    NonText                     = { fg = c.muted },
    Normal                      = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    NormalNC                    = { fg = c.fg, bg = opts.transparent and c.none or opts.dim_inactive and c.dark_bg or c.bg },
    NormalSB                    = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NormalFloat                 = { fg = c.fg_float, bg = c.bg_float },
    FloatBorder                 = { fg = c.border_highlight, bg = c.bg_float },
    FloatTitle                  = { fg = c.border_highlight, bg = c.bg_float, bold = true },
    Pmenu                       = { bg = c.bg_popup, fg = c.fg },
    PmenuMatch                  = { bg = c.bg_popup, fg = c.blue },
    PmenuSel                    = { bg = Util.blend_bg(c.muted, 0.8) },
    PmenuMatchSel               = { bg = Util.blend_bg(c.muted, 0.8), fg = c.blue },
    PmenuSbar                   = { bg = Util.blend_fg(c.bg_popup, 0.95) },
    PmenuThumb                  = { bg = c.muted },
    Question                    = { fg = c.blue, bold = true },
    QuickFixLine                = { bg = c.bg_visual, bold = true },
    Search                      = { bg = c.bg_search, fg = c.fg, bold = true },
    IncSearch                   = { bg = c.orange, fg = c.black, bold = true },
    CurSearch                   = "IncSearch",
    SpecialKey                  = { fg = c.muted },
    SpellBad                    = { sp = c.error, undercurl = true },
    SpellCap                    = { sp = c.warning, undercurl = true },
    SpellLocal                  = { sp = c.info, undercurl = true },
    SpellRare                   = { sp = c.hint, undercurl = true },
    StatusLine                  = { fg = c.fg_sidebar, bg = c.bg_statusline },
    StatusLineNC                = { fg = c.muted, bg = c.bg_statusline },
    TabLine                     = { bg = c.bg_statusline, fg = c.muted },
    TabLineFill                 = { bg = c.black },
    TabLineSel                  = { fg = c.black, bg = c.blue },
    Title                       = { fg = c.blue, bold = true },
    Visual                      = { bg = c.bg_visual },
    VisualNOS                   = { bg = c.bg_visual },
    WarningMsg                  = { fg = c.warning, bold = true },
    Whitespace                  = { fg = c.muted },
    WildMenu                    = { bg = c.bg_visual },
    WinBar                      = { link = "StatusLine" },
    WinBarNC                    = { link = "StatusLineNC" },

    -- Syntax
    Constant                    = { fg = c.bright_yellow },
    String                      = { fg = c.green },
    Character                   = { fg = c.green },
    Number                      = { fg = c.orange },
    Boolean                     = { fg = c.orange },
    Float                       = { fg = c.orange },
    Identifier                  = { fg = c.bright_cyan, style = opts.styles.variables },
    Function                    = { fg = c.blue, bold = true, style = opts.styles.functions },
    Statement                   = { fg = c.blue, bold = true },
    Conditional                 = { fg = c.bright_purple },
    Repeat                      = { fg = c.bright_purple },
    Label                       = { fg = c.yellow },
    Operator                    = { fg = c.fg },
    Keyword                     = { fg = c.bright_purple, bold = true, style = opts.styles.keywords },
    Exception                   = { fg = c.bright_purple },
    PreProc                     = { fg = c.cyan },
    Include                     = { fg = c.blue },
    Define                      = { fg = c.bright_purple },
    Macro                       = { fg = c.cyan },
    PreCondit                   = { fg = c.cyan },
    Type                        = { fg = c.yellow, bold = true },
    StorageClass                = { fg = c.yellow },
    Structure                   = { fg = c.yellow },
    Typedef                     = { fg = c.yellow },
    Special                     = { fg = c.cyan },
    SpecialChar                 = { fg = c.bright_red },
    Tag                         = { fg = c.bright_red },
    Delimiter                   = { fg = c.fg },
    SpecialComment              = { fg = c.muted, style = opts.styles.comments },
    Debug                       = { fg = c.bright_red },
    Underlined                  = { underline = true },
    Ignore                      = { fg = c.muted },
    Error                       = { fg = c.bright_red, bold = true },
    Todo                        = { bg = c.yellow, fg = c.bg, bold = true },

    debugBreakpoint             = { bg = Util.blend_bg(c.info, 0.1), fg = c.info },
    debugPC                     = { bg = c.bg_sidebar },
    dosIniLabel                 = "@property",
    helpCommand                 = { bg = c.subtle_bg, fg = c.blue },
    htmlH1                      = { fg = c.bright_purple, bold = true },
    htmlH2                      = { fg = c.blue, bold = true },
    qfFileName                  = { fg = c.blue },
    qfLineNr                    = { fg = c.dark_fg },

    -- LSP info border (the rest of LSP and Diagnostic groups live in lsp.lua)
    LspInfoBorder               = { fg = c.border_highlight, bg = c.bg_float },

    -- Health
    healthError                 = { fg = c.bright_red },
    healthSuccess               = { fg = c.green },
    healthWarning               = { fg = c.warning },

    -- Git
    diffAdded                   = { bg = c.diff.add, fg = c.bright_green },
    diffRemoved                 = { bg = c.diff.delete, fg = c.bright_red },
    diffChanged                 = { bg = c.diff.change, fg = c.git.change },
    diffOldFile                 = { fg = c.blue, bg = c.diff.delete },
    diffNewFile                 = { fg = c.blue, bg = c.diff.add },
    diffFile                    = { fg = c.blue },
    diffLine                    = { fg = c.muted },
    diffIndexLine               = { fg = c.bright_purple },
  }
end

return M
