# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#181c1f"

# Main text color
theme[main_fg]="#e1e4e8"

# Title color for boxes
theme[title]="#f9826c"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#f9826c"

# Background color of selected item in processes box
theme[selected_bg]="#598DEFE6"

# Foreground color of selected item in processes box
theme[selected_fg]="#e1e4e8"

# Color of inactive/disabled text
theme[inactive_fg]="#676E9599"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f9826c"

# Box outline and divider line color
theme[cpu_box]="#79b8ff"
theme[mem_box]="#79b8ff"
theme[net_box]="#79b8ff"
theme[proc_box]="#79b8ff"
theme[div_line]="#676E9599"

# Gradient for all meters and graphs
theme[temp_start]="#79b8ff"
theme[temp_mid]="#598DEFE6"
theme[temp_end]="#34d058"


theme[cpu_start]="#79b8ff"
theme[cpu_mid]="#598DEFE6"
theme[cpu_end]="#34d058"


theme[free_start]="#598DEFE6"
theme[free_mid]="#79b8ff"
theme[free_end]="#79b8ff"


theme[cached_start]="#79b8ff"
theme[cached_mid]="#79b8ff"
theme[cached_end]="#79b8ff"


theme[available_start]="#79b8ff"
theme[available_mid]="#79b8ff"
theme[available_end]="#79b8ff"


theme[used_start]="#34d058"
theme[used_mid]="#34d058"
theme[used_end]="#34d058"


theme[download_start]="#79b8ff"
theme[download_mid]="#598DEFE6"
theme[download_end]="#f9826c"


theme[upload_start]="#79b8ff"
theme[upload_mid]="#598DEFE6"
theme[upload_end]="#f9826c"