return function()
  return {
    htmlEndTag = { link = "htmlTag" },
    htmlLink = { link = "Underlined" },
    javaScriptBraces = { link = "Delimiter" },
    javaScript = { link = "Normal" },
    lessVariableValue = { link = "Normal" },
    markdownCodeBlock = { link = "String" },
    markdownCodeDelimiter = { link = "NonText" },
    markdownHeadingRule = { link = "NonText" },
    markdownLinkDelimiter = { link = "Delimiter" },
    markdownURLDelimiter = { link = "Delimiter" },
    NERDTreeExecFile = { link = "String" },
    NERDTreeHelp = { link = "Comment" },
    NvimArrow = { link = "Delimiter" },
    NvimColon = { link = "Delimiter" },
    NvimComma = { link = "Delimiter" },
    NvimFigureBrace = { link = "NvimInternalError" },
    NvimIdentifier = { link = "Identifier" },
    NvimInvalid = { link = "Error" },
    NvimInvalidSingleQuotedUnknownEscape = { link = "NvimInternalError" },
    NvimInvalidSpacing = { link = "ErrorMsg" },
    NvimNumber = { link = "Number" },
    NvimNumberPrefix = { link = "Type" },
    NvimOptionSigil = { link = "Type" },
    NvimParenthesis = { link = "Delimiter" },
    NvimSingleQuotedUnknownEscape = { link = "NvimInternalError" },
    NvimSpacing = { link = "Normal" },
    NvimString = { link = "String" },
    phpDefine = { link = "Statement" },
    phpHereDoc = { link = "String" },
    phpVarSelector = { link = "phpIdentifier" },
    rubyConstant = { link = "Constant" },
    rubyDefine = { link = "Statement" },
    rubyInstanceVariable = { link = "Identifier" },
    rubyLocalVariableOrMethod = { link = "Identifier" },
    shDerefVar = { link = "shDerefSimple" },
    vimContinue = { link = "Delimiter" },
    vimHiAttrib = { link = "Constant" },
    vimSetSep = { link = "Delimiter" },
    xmlAttrib = { link = "xmlTag" },
    xmlEndTag = { link = "xmlTag" },
    xmlEqual = { link = "xmlTag" },
    xmlString = { link = "xmlTagName" },
  }
end
