return function()
  return {
    ["@boolean"] = { link = "Boolean" },
    ["@comment"] = { link = "Comment" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant"] = { link = "Constant" },
    ["@constructor"] = { link = "Special" },
    ["@field"] = { link = "Identifier" },
    ["@function.builtin"] = { link = "Special" },
    ["@function"] = { link = "Function" },
    ["@keyword"] = { link = "Keyword" },
    ["@method"] = { link = "Function" },
    ["@namespace"] = { link = "Identifier" },
    ["@number"] = { link = "Number" },
    ["@parameter"] = { link = "Identifier" },
    ["@preproc"] = { link = "PreProc" },
    ["@property"] = { link = "Identifier" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    ["@text.literal"] = { link = "Comment" },
    ["@text.reference"] = { link = "Identifier" },
    ["@text.title"] = { link = "Title" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.underline"] = { link = "Underlined" },
    ["@text.uri"] = { link = "Underlined" },
    ["@type"] = { link = "Type" },
    ["@variable"] = { link = "Identifier" },
  }
end
