accent = "#9e4f5b"
cursor = "#DEA193"
foreground = "#35302a"
background = "#F5E6D3"
selection_foreground = "#35302a"
selection_background = "#c68d95"

color0 = "#F5E6D3"
color1 = "#a02b16"
color2 = "#9e4f5b"
color3 = "#644535"
color4 = "#76634c"
color5 = "#78292e"
color6 = "#713a56"
color7 = "#a94a34"
color8 = "#C8AC86"
color9 = "#a02b16"
color10 = "#9e4f5b"
color11 = "#694C45"
color12 = "#76634c"
color13 = "#78292e"
color14 = "#713a56"
color15 = "#a94a34"
