accent = "#da103f"
cursor = "#e84a72"
foreground = "#06060c"
background = "#fdf0ed"
selection_foreground = "#06060c"
selection_background = "#f9cbbe"
color0 = "#fdf0ed"
color1 = "#da103f"
color2 = "#1eb980"
color3 = "#af5427"
color4 = "#8a31b9"
color5 = "#e73665"
color6 = "#1d8991"
color7 = "#333333"
color8 = "#8a31b9"
color9 = "#dc3318"
color10 = "#07da8c"
color11 = "#f77d26"
color12 = "#8a31b9"
color13 = "#e84a72"
color14 = "#1eaeae"
color15 = "#333333"
