statusBg = "#fadad1"
surfaceVariant = "#fadad1"
surfaceContainerLow = "#fadad1"
surfaceContainer = "#fadad1"
surfaceContainerHigh = "#f9cbbe"
surfaceContainerHighest = "#f9cbbe"
outline = "#1a1c23"
outlineVariant = "#16161c"
