return function(palette)
  return {
    GitSignsAdd = { fg = palette.accent_secondary, bg = palette.surface },
    GitSignsAddInline = { fg = palette.base, bg = palette.accent_secondary, style = "bold" },
    GitSignsAddPreview = { fg = palette.base, bg = palette.accent_secondary },
    GitSignsChange = { fg = palette.warning, bg = palette.surface },
    GitSignsChangeInline = { fg = palette.base, bg = palette.orange, style = "bold" },
    GitSignsCurrentLineBlame = { fg = palette.text_muted, style = "italic" },
    GitSignsDelete = { fg = palette.error, bg = palette.surface },
    GitSignsDeleteInline = { fg = palette.base, bg = palette.error, style = "bold" },
    GitSignsDeletePreview = { fg = palette.base, bg = palette.error },
    IblIndent = { fg = palette.indent, style = "nocombine" },
    IblScope = { fg = palette.surface_highlight, style = "nocombine" },
    IblWhitespace = { fg = palette.indent, style = "nocombine" },

    LazyButtonActive = { fg = palette.base, bg = palette.accent_primary },
    LazyButton = { bg = palette.base },
    LazyComment = { fg = palette.text_muted },
    LazyCommit = { fg = palette.text },
    LazyCommitIssue = { fg = palette.amber },
    LazyCommitScope = { fg = palette.accent_secondary },
    LazyCommitType = { fg = palette.orange },
    LazyDimmed = { fg = palette.text_muted },
    LazyDir = { fg = palette.accent_primary },
    LazyH1 = { fg = palette.accent_primary, bg = palette.base },
    LazyH2 = { fg = palette.accent_primary, bg = palette.base },
    LazyLocal = { fg = palette.amber },
    LazyNoCond = { fg = palette.error },
    LazyNormal = { bg = palette.surface },
    LazyProgressDone = { fg = palette.accent_primary },
    LazyProgressTodo = { fg = palette.text_muted },
    LazyProp = { fg = palette.text_muted },
    LazyReasonCmd = { fg = palette.orange },
    LazyReasonEvent = { fg = palette.accent_secondary },
    LazyReasonFt = { fg = palette.accent_primary },
    LazyReasonImport = { fg = palette.orange },
    LazyReasonKeys = { fg = palette.amber },
    LazyReasonPlugin = { fg = palette.text },
    LazyReasonRuntime = { fg = palette.warning },
    LazyReasonSource = { fg = palette.text_muted },
    LazyReasonStart = { fg = palette.accent_primary },
    LazySpecial = { fg = palette.amber },
    LazyTaskError = { fg = palette.error },
    LazyTaskOutput = { fg = palette.text_muted },
    LazyUrl = { fg = palette.accent_secondary, style = "underline" },
    LazyValue = { fg = palette.text },

    MasonError = { fg = palette.error },
    MasonHeader = { fg = palette.text, bg = palette.surface },
    MasonHeading = { fg = palette.text, style = "bold" },
    MasonHighlight = { fg = palette.accent_primary, bg = palette.base },
    MasonHighlightSecondary = { fg = palette.amber },
    MasonHighlightBlockSecondary = { fg = palette.base, bg = palette.orange },
    MasonHighlightBlockBoldSecondary = { fg = palette.base, bg = palette.orange, style = "bold" },
    MasonMuted = { fg = palette.amber, bg = palette.surface },
    MasonWarning = { fg = palette.orange },

    ScrollbarCursor = { fg = palette.base },
    ScrollbarCursorHandle = { fg = palette.base, bg = palette.surface, blend = 0 },
    ScrollbarError = { fg = palette.warning },
    ScrollbarErrorHandle = { fg = palette.warning, bg = palette.surface, blend = 0 },
    ScrollbarGitAdd = { fg = palette.accent_secondary },
    ScrollbarGitAddHandle = { fg = palette.accent_secondary, bg = palette.surface, blend = 0 },
    ScrollbarGitChange = { fg = palette.warning },
    ScrollbarGitChangeHandle = { fg = palette.warning, bg = palette.surface, blend = 0 },
    ScrollbarGitDelete = { fg = palette.error },
    ScrollbarGitDeleteHandle = { fg = palette.error, bg = palette.surface, blend = 0 },
    ScrollbarHandle = { bg = palette.surface, blend = 0 },
    ScrollbarHint = { fg = palette.accent_secondary },
    ScrollbarHintHandle = { fg = palette.accent_secondary, bg = palette.surface, blend = 0 },
    ScrollbarInfo = { fg = palette.accent_secondary },
    ScrollbarInfoHandle = { fg = palette.accent_secondary, bg = palette.surface, blend = 0 },
    ScrollbarMisc = { fg = palette.orange },
    ScrollbarMiscHandle = { fg = palette.orange, bg = palette.surface, blend = 0 },
    ScrollbarSearch = { fg = palette.amber },
    ScrollbarSearchHandle = { fg = palette.amber, bg = palette.surface, blend = 0 },
    ScrollbarWarn = { fg = palette.error },
    ScrollbarWarnHandle = { fg = palette.error, bg = palette.surface, blend = 0 },

    TelescopeBorder = { fg = palette.warning, bg = palette.surface },
    TelescopeMultiIcon = { fg = palette.amber },
    TelescopeMultiSelection = { fg = palette.text },
    TelescopeNormal = { fg = palette.text, bg = palette.surface },
    TelescopePreviewBlock = { fg = palette.orange },
    TelescopePreviewCharDev = { fg = palette.orange },
    TelescopePreviewDate = { fg = palette.amber },
    TelescopePreviewDirectory = { fg = palette.accent_primary },
    TelescopePreviewExecute = { fg = palette.accent_secondary },
    TelescopePreviewGroup = { fg = palette.text_muted },
    TelescopePreviewHyphen = { fg = palette.text_muted },
    TelescopePreviewLink = { fg = palette.accent_secondary, style = "underline" },
    TelescopePreviewMatch = { fg = palette.text, bg = palette.surface_highlight, style = "bold" },
    TelescopePreviewMessageFillchar = { fg = palette.text_muted },
    TelescopePreviewMessage = { fg = palette.text_muted },
    TelescopePreviewNormal = { fg = palette.text, bg = palette.surface },
    TelescopePreviewPipe = { fg = palette.text_muted },
    TelescopePreviewRead = { fg = palette.accent_secondary },
    TelescopePreviewSize = { fg = palette.amber },
    TelescopePreviewSocket = { fg = palette.warning },
    TelescopePreviewSticky = { fg = palette.orange },
    TelescopePreviewUser = { fg = palette.text },
    TelescopePreviewWrite = { fg = palette.orange },
    TelescopePromptBorder = { fg = palette.error, bg = palette.surface },
    TelescopePromptNormal = { fg = palette.text, bg = palette.surface },
    TelescopeResultsClass = { fg = palette.accent_primary },
    TelescopeResultsComment = { fg = palette.text_muted },
    TelescopeResultsConstant = { fg = palette.orange },
    TelescopeResultsDiffUntracked = { fg = palette.warning },
    TelescopeResultsField = { fg = palette.text },
    TelescopeResultsFunction = { fg = palette.accent_primary },
    TelescopeResultsIdentifier = { fg = palette.text },
    TelescopeResultsLineNr = { fg = palette.text_muted },
    TelescopeResultsMethod = { fg = palette.accent_primary },
    TelescopeResultsNormal = { fg = palette.text, bg = palette.surface },
    TelescopeResultsNumber = { fg = palette.type },
    TelescopeResultsOperator = { fg = palette.text },
    TelescopeResultsSpecialComment = { fg = palette.text_muted },
    TelescopeResultsStruct = { fg = palette.accent_primary },
    TelescopeResultsVariable = { fg = palette.text },
    TelescopeSelectionCaret = { fg = palette.text, bg = palette.accent_primary },
    TelescopeTitle = { fg = palette.accent_secondary, bg = palette.surface },

    WhichKeyBorder = { bg = palette.surface },
    WhichKeyDesc = { fg = palette.accent_secondary, bg = palette.surface },
    WhichKeyFloat = { bg = palette.surface },
    WhichKeyGroup = { fg = palette.orange, bg = palette.surface },
    WhichKey = { fg = palette.text, bg = palette.surface },
    WhichKeySeparator = { fg = palette.amber, bg = palette.surface },
    WhichKeyValue = { fg = palette.amber },
  }
end
