return function(palette)
  return {
    BlinkCmpDoc = { fg = palette.text, bg = palette.base },
    BlinkCmpDocBorder = { fg = palette.orange, bg = palette.base },
    BlinkCmpLabel = { fg = palette.text },
    BlinkCmpLabelDeprecated = { fg = palette.text_muted, style = "strikethrough" },
    BlinkCmpLabelDescription = { fg = palette.text_muted },
    BlinkCmpLabelDetail = { fg = palette.text_muted },
    BlinkCmpLabelMatch = { fg = palette.text_bright, style = "bold" },
    BlinkCmpMenu = { fg = palette.text, bg = palette.surface },
    BlinkCmpMenuBorder = { fg = palette.orange, bg = palette.surface },
    BlinkCmpMenuSelection = { fg = palette.text_bright, bg = palette.accent_primary, style = "bold" },
    BlinkCmpScrollBarGutter = { bg = palette.text_muted },
    BlinkCmpScrollBarThumb = { bg = palette.text },
    BlinkCmpSignatureHelpBorder = { fg = palette.orange, bg = palette.base },

    CmpItemAbbr = { fg = palette.text },
    CmpItemAbbrDeprecated = { fg = palette.text_muted, style = "strikethrough" },
    CmpItemAbbrMatch = { fg = palette.text_bright, style = "bold" },
    CmpItemAbbrMatchFuzzy = { fg = palette.amber, style = "bold" },
    CmpItemKind = { fg = palette.accent_primary },
    CmpItemKindClass = { fg = palette.accent_primary, style = "bold" },
    CmpItemKindColor = { fg = palette.error },
    CmpItemKindConstant = { fg = palette.orange },
    CmpItemKindConstructor = { fg = palette.accent_primary },
    CmpItemKindEnum = { fg = palette.accent_primary, style = "bold" },
    CmpItemKindEnumMember = { fg = palette.amber },
    CmpItemKindEvent = { fg = palette.accent_secondary },
    CmpItemKindField = { fg = palette.text },
    CmpItemKindFile = { fg = palette.accent_secondary },
    CmpItemKindFolder = { fg = palette.accent_primary },
    CmpItemKindFunction = { fg = palette.accent_primary },
    CmpItemKindInterface = { fg = palette.accent_primary, style = "bold" },
    CmpItemKindKeyword = { fg = palette.accent_secondary, style = "bold" },
    CmpItemKindMenu = { fg = palette.text_muted },
    CmpItemKindMethod = { fg = palette.accent_primary },
    CmpItemKindModule = { fg = palette.accent_secondary },
    CmpItemKindOperator = { fg = palette.text },
    CmpItemKindProperty = { fg = palette.text },
    CmpItemKindReference = { fg = palette.error },
    CmpItemKindSnippet = { fg = palette.amber },
    CmpItemKindStruct = { fg = palette.accent_primary, style = "bold" },
    CmpItemKindText = { fg = palette.text },
    CmpItemKindTypeParameter = { fg = palette.amber },
    CmpItemKindUnit = { fg = palette.accent_primary },
    CmpItemKindValue = { fg = palette.orange },
    CmpItemKindVariable = { fg = palette.text },
    CmpItemMenu = { fg = palette.text_muted },
  }
end
