return function(palette)
  return {
    DapBreakpoint = { fg = palette.error },
    DapBreakpointCondition = { fg = palette.orange },
    DapBreakpointRejected = { fg = palette.amber },
    DapLogPoint = { fg = palette.accent_secondary },
    DapStopped = { fg = palette.text, style = "bold" },
    DapUIBreakpointsCurrentLine = { fg = palette.accent_primary, style = "bold" },
    DapUIBreakpointsDisabledLine = { fg = palette.text_muted },
    DapUIBreakpointsInfo = { fg = palette.accent_primary },
    DapUIBreakpointsPath = { fg = palette.accent_secondary },
    DapUIDecoration = { fg = palette.accent_secondary },
    DapUIFloatBorder = { fg = palette.orange, bg = palette.base },
    DapUILineNumber = { fg = palette.amber },
    DapUIModifiedValue = { fg = palette.orange, style = "bold" },
    DapUIPlayPause = { fg = palette.accent_primary, style = "bold" },
    DapUIPlayPauseNC = { fg = palette.accent_primary },
    DapUIRestart = { fg = palette.accent_primary, style = "bold" },
    DapUIRestartNC = { fg = palette.accent_primary },
    DapUIScope = { fg = palette.accent_secondary },
    DapUISource = { fg = palette.amber },
    DapUIStepBack = { fg = palette.accent_secondary },
    DapUIStepBackNC = { fg = palette.accent_secondary },
    DapUIStepInto = { fg = palette.accent_secondary },
    DapUIStepIntoNC = { fg = palette.accent_secondary },
    DapUIStepOut = { fg = palette.accent_secondary },
    DapUIStepOutNC = { fg = palette.accent_secondary },
    DapUIStepOver = { fg = palette.accent_secondary },
    DapUIStepOverNC = { fg = palette.accent_secondary },
    DapUIStop = { fg = palette.error, style = "bold" },
    DapUIStopNC = { fg = palette.error },
    DapUIStoppedThread = { fg = palette.accent_secondary, style = "bold" },
    DapUIThread = { fg = palette.accent_primary },
    DapUIType = { fg = palette.accent_primary, style = "bold" },
    DapUIUnavailable = { fg = palette.text_muted },
    DapUIUnavailableNC = { fg = palette.text_muted },
    DapUIValue = { fg = palette.accent_secondary },
    DapUIVariable = { fg = palette.text },
    DapUIWatchesEmpty = { fg = palette.error },
    DapUIWatchesError = { fg = palette.error },
    DapUIWatchesValue = { fg = palette.accent_primary },
    DapUIWinSelect = { fg = palette.amber, style = "bold" },

    DiffviewDim1 = { fg = palette.text_muted },
    DiffviewFilePanelConflicts = { fg = palette.orange, style = "bold" },
    DiffviewFilePanelCounter = { fg = palette.text },
    DiffviewFilePanelDeletions = { fg = palette.error },
    DiffviewFilePanelFileName = { fg = palette.text },
    DiffviewFilePanelInsertions = { fg = palette.accent_secondary },
    DiffviewFilePanelPath = { fg = palette.text_muted },
    DiffviewFilePanelRootPath = { fg = palette.text, style = "bold" },
    DiffviewFilePanelSelected = { fg = palette.amber, style = "bold" },
    DiffviewFilePanelTitle = { fg = palette.accent_secondary, style = "bold" },
    DiffviewFolderName = { fg = palette.accent_primary, style = "bold" },
    DiffviewFolderSign = { fg = palette.accent_primary },
    DiffviewHash = { fg = palette.amber },
    DiffviewNormal = { fg = palette.text, bg = palette.base },
    DiffviewPrimary = { fg = palette.accent_secondary },
    DiffviewReference = { fg = palette.accent_primary, style = "bold" },
    DiffviewReflogSelector = { fg = palette.amber },
    DiffviewSecondary = { fg = palette.accent_primary },
    DiffviewStatusAdded = { fg = palette.accent_secondary },
    DiffviewStatusBroken = { fg = palette.error },
    DiffviewStatusCopied = { fg = palette.orange },
    DiffviewStatusDeleted = { fg = palette.error },
    DiffviewStatusIgnored = { fg = palette.text_muted },
    DiffviewStatusModified = { fg = palette.orange },
    DiffviewStatusRenamed = { fg = palette.amber },
    DiffviewStatusTypeChange = { fg = palette.amber },
    DiffviewStatusUnknown = { fg = palette.error },
    DiffviewStatusUnmerged = { fg = palette.orange, style = "bold" },
    DiffviewStatusUntracked = { fg = palette.accent_secondary },
    DiffviewWinSeparator = { fg = palette.surface_highlight, bg = palette.base },

    NeogitBranch = { fg = palette.orange, style = "bold" },
    NeogitChangeAdded = { fg = palette.accent_secondary, style = "bold" },
    NeogitChangeBothModified = { fg = palette.orange, style = "bold" },
    NeogitChangeCopied = { fg = palette.amber, style = "bold" },
    NeogitChangeDeleted = { fg = palette.error, style = "bold" },
    NeogitChangeModified = { fg = palette.orange, style = "bold" },
    NeogitChangeNewFile = { fg = palette.accent_secondary, style = "bold" },
    NeogitChangeRenamed = { fg = palette.amber, style = "bold" },
    NeogitChangeUpdated = { fg = palette.amber, style = "bold" },
    NeogitCommitViewHeader = { fg = palette.text, bg = palette.surface, style = "bold" },
    NeogitDiffAdd = { fg = palette.accent_secondary, bg = palette.surface },
    NeogitDiffAddHighlight = { fg = palette.text, bg = palette.accent_secondary },
    NeogitDiffContext = { fg = palette.text, bg = palette.base },
    NeogitDiffContextHighlight = { fg = palette.text_bright, bg = palette.surface },
    NeogitDiffDelete = { fg = palette.error, bg = palette.surface },
    NeogitDiffDeleteHighlight = { fg = palette.text, bg = palette.error },
    NeogitDiffHeader = { fg = palette.accent_secondary, bg = palette.base, style = "bold" },
    NeogitDiffHeaderHighlight = { fg = palette.orange, bg = palette.base, style = "bold" },
    NeogitFilePath = { fg = palette.accent_secondary, style = "italic" },
    NeogitGraphBlue = { fg = palette.accent_secondary },
    NeogitGraphBoldBlue = { fg = palette.accent_secondary, style = "bold" },
    NeogitGraphBoldCyan = { fg = palette.accent_secondary, style = "bold" },
    NeogitGraphBoldGray = { fg = palette.text_muted, style = "bold" },
    NeogitGraphBoldGreen = { fg = palette.accent_primary, style = "bold" },
    NeogitGraphBoldOrange = { fg = palette.orange, style = "bold" },
    NeogitGraphBoldPurple = { fg = palette.amber, style = "bold" },
    NeogitGraphBoldRed = { fg = palette.error, style = "bold" },
    NeogitGraphBoldWhite = { fg = palette.text, style = "bold" },
    NeogitGraphBoldYellow = { fg = palette.amber, style = "bold" },
    NeogitGraphCyan = { fg = palette.accent_secondary },
    NeogitGraphGray = { fg = palette.text_muted },
    NeogitGraphGreen = { fg = palette.accent_primary },
    NeogitGraphOrange = { fg = palette.orange },
    NeogitGraphPurple = { fg = palette.amber },
    NeogitGraphRed = { fg = palette.error },
    NeogitGraphWhite = { fg = palette.text },
    NeogitGraphYellow = { fg = palette.amber },
    NeogitHunkHeader = { fg = palette.text_muted, bg = palette.surface },
    NeogitHunkHeaderHighlight = { fg = palette.text, bg = palette.surface_highlight, style = "bold" },
    NeogitNotificationError = { fg = palette.error },
    NeogitNotificationInfo = { fg = palette.accent_secondary },
    NeogitNotificationWarning = { fg = palette.orange },
    NeogitObjectId = { fg = palette.text_muted },
    NeogitPopupActionKey = { fg = palette.amber },
    NeogitPopupBold = { fg = palette.text, style = "bold" },
    NeogitPopupConfigKey = { fg = palette.amber },
    NeogitPopupOptionKey = { fg = palette.amber },
    NeogitPopupSwitchKey = { fg = palette.amber },
    NeogitRebaseDone = { fg = palette.text_muted },
    NeogitRecentcommits = { fg = palette.amber, style = "bold" },
    NeogitRebasing = { fg = palette.amber, style = "bold" },
    NeogitRemote = { fg = palette.accent_primary, style = "bold" },
    NeogitSectionHeader = { fg = palette.amber, style = "bold" },
    NeogitStagedchanges = { fg = palette.amber, style = "bold" },
    NeogitStash = { fg = palette.text_muted },
    NeogitStashes = { fg = palette.amber, style = "bold" },
    NeogitTagName = { fg = palette.amber },
    NeogitUnmergedInto = { fg = palette.accent_primary },
    NeogitUnmergedchanges = { fg = palette.amber, style = "bold" },
    NeogitUnpulledFrom = { fg = palette.accent_primary },
    NeogitUnpulledchanges = { fg = palette.amber, style = "bold" },
    NeogitUnpushedTo = { fg = palette.amber, style = "bold" },
    NeogitUnstagedchanges = { fg = palette.amber, style = "bold" },
    NeogitUntrackedfiles = { fg = palette.amber, style = "bold" },

    NeotestAdapterName = { fg = palette.orange },
    NeotestDir = { fg = palette.accent_primary, style = "bold" },
    NeotestExpandMarker = { fg = palette.text_muted },
    NeotestFailed = { fg = palette.error, style = "bold" },
    NeotestFile = { fg = palette.accent_secondary },
    NeotestFocused = { fg = palette.text_bright, sp = palette.text, style = "bold,underline" },
    NeotestIndent = { fg = palette.surface_highlight },
    NeotestMarked = { fg = palette.orange, style = "bold" },
    NeotestNamespace = { fg = palette.amber },
    NeotestPassed = { fg = palette.accent_primary, style = "bold" },
    NeotestRunning = { fg = palette.orange },
    NeotestSkipped = { fg = palette.accent_secondary },
    NeotestTarget = { fg = palette.error, style = "bold" },
    NeotestTest = { fg = palette.text },
    NeotestUnknown = { fg = palette.text_muted },
    NeotestWinSelect = { fg = palette.accent_secondary, style = "bold" },
  }
end
