return function(palette)
  return {
    MiniAnimateCursor = { style = "reverse,nocombine" },
    MiniAnimateNormalFloat = { fg = palette.text, bg = palette.base },
    MiniClueBorder = { fg = palette.orange, bg = palette.base },
    MiniClueDescGroup = { fg = palette.orange },
    MiniClueDescSingle = { fg = palette.text, bg = palette.base },
    MiniClueNextKey = { fg = palette.accent_secondary, style = "bold" },
    MiniClueNextKeyWithPostkeys = { fg = palette.error, style = "bold" },
    MiniClueSeparator = { fg = palette.accent_secondary },
    MiniClueTitle = { fg = palette.error, style = "bold" },
    MiniCompletionActiveParameter = { sp = palette.text, style = "underline" },
    MiniCursorword = { sp = palette.text, style = "underline" },
    MiniCursorwordCurrent = { sp = palette.text, style = "underline" },
    MiniDepsChangeAdded = { fg = palette.accent_secondary },
    MiniDepsChangeRemoved = { fg = palette.error },
    MiniDepsHint = { fg = palette.accent_secondary },
    MiniDepsInfo = { fg = palette.accent_secondary },
    MiniDepsMsgBreaking = { fg = palette.orange },
    MiniDepsPlaceholder = { fg = palette.text_muted },
    MiniDepsTitle = { fg = palette.error, style = "bold" },
    MiniDepsTitleError = { fg = palette.base, bg = palette.error, style = "bold" },
    MiniDepsTitleSame = { fg = palette.base, bg = palette.amber, style = "bold" },
    MiniDepsTitleUpdate = { fg = palette.base, bg = palette.accent_secondary, style = "bold" },
    MiniDiffOverAdd = { fg = palette.base, bg = palette.accent_secondary },
    MiniDiffOverChange = { fg = palette.base, bg = palette.amber, style = "bold" },
    MiniDiffOverContext = { fg = palette.base, bg = palette.orange },
    MiniDiffOverDelete = { fg = palette.base, bg = palette.error, style = "bold" },
    MiniDiffSignAdd = { fg = palette.accent_secondary },
    MiniDiffSignChange = { fg = palette.orange },
    MiniDiffSignDelete = { fg = palette.error },
    MiniFilesBorder = { fg = palette.orange, bg = palette.base },
    MiniFilesBorderModified = { fg = palette.orange, bg = palette.base, style = "bold" },
    MiniFilesCursorLine = { bg = palette.surface },
    MiniFilesDirectory = { fg = palette.accent_primary, bg = palette.base },
    MiniFilesFile = { fg = palette.text },
    MiniFilesNormal = { fg = palette.text, bg = palette.base },
    MiniFilesTitle = { fg = palette.error, style = "bold" },
    MiniFilesTitleFocused = { fg = palette.text, bg = palette.base, style = "bold" },
    MiniHipatternsFixme = { fg = palette.base, bg = palette.error, style = "bold" },
    MiniHipatternsHack = { fg = palette.base, bg = palette.amber, style = "bold" },
    MiniHipatternsNote = { fg = palette.base, bg = palette.accent_secondary, style = "bold" },
    MiniHipatternsTodo = { fg = palette.base, bg = palette.accent_primary, style = "bold" },
    MiniIconsAzure = { fg = palette.accent_secondary },
    MiniIconsBlue = { fg = palette.accent_secondary },
    MiniIconsCyan = { fg = palette.accent_primary },
    MiniIconsGreen = { fg = palette.accent_primary },
    MiniIconsGrey = { fg = palette.text_muted },
    MiniIconsOrange = { fg = palette.orange },
    MiniIconsPurple = { fg = palette.amber },
    MiniIconsRed = { fg = palette.error },
    MiniIconsYellow = { fg = palette.amber },
    MiniIndentscopeSymbol = { fg = palette.surface_highlight, style = "nocombine" },
    MiniJump = { fg = palette.text, bg = palette.amber },
    MiniJump2dDim = { fg = palette.text_muted },
    MiniJump2dSpot = { fg = palette.orange, bg = palette.base, style = "bold,underline" },
    MiniJump2dSpotAhead = { fg = palette.accent_primary, bg = palette.base },
    MiniJump2dSpotUnique = { fg = palette.accent_secondary, bg = palette.base, style = "bold" },
    MiniMapNormal = { fg = palette.text, bg = palette.base },
    MiniMapSymbolCount = { fg = palette.orange },
    MiniMapSymbolLine = { fg = palette.error, style = "bold" },
    MiniMapSymbolView = { fg = palette.text },
    MiniNotifyBorder = { fg = palette.orange, bg = palette.base },
    MiniNotifyNormal = { fg = palette.text, bg = palette.base },
    MiniNotifyTitle = { fg = palette.error, style = "bold" },
    MiniOperatorsExchangeFrom = { fg = palette.text_bright, bg = palette.error, style = "bold" },
    MiniPickBorder = { fg = palette.orange, bg = palette.base },
    MiniPickBorderBusy = { fg = palette.orange, bg = palette.base, style = "bold" },
    MiniPickBorderText = { fg = palette.amber, bg = palette.base },
    MiniPickHeader = { fg = palette.accent_secondary, style = "bold" },
    MiniPickIconDirectory = { fg = palette.accent_primary, bg = palette.base },
    MiniPickIconFile = { fg = palette.text },
    MiniPickMatchCurrent = { fg = palette.text_bright, bg = palette.surface, style = "bold" },
    MiniPickMatchMarked = { fg = palette.text_bright, bg = palette.surface_highlight },
    MiniPickMatchRanges = { fg = palette.accent_secondary, style = "bold" },
    MiniPickNormal = { fg = palette.text, bg = palette.base },
    MiniPickPreviewLine = { bg = palette.surface },
    MiniPickPreviewRegion = { fg = palette.text_bright, bg = palette.error, style = "bold" },
    MiniPickPrompt = { fg = palette.text, bg = palette.base },
    MiniPickPromptCaret = { fg = palette.orange, bg = palette.base },
    MiniPickPromptPrefix = { fg = palette.orange, bg = palette.base },
    MiniStarterCurrent = {},
    MiniStarterFooter = { fg = palette.amber, style = "italic" },
    MiniStarterHeader = { fg = palette.accent_secondary, style = "bold" },
    MiniStarterInactive = { fg = palette.text_muted },
    MiniStarterItem = { fg = palette.text },
    MiniStarterItemBullet = { fg = palette.accent_secondary },
    MiniStarterItemPrefix = { fg = palette.amber },
    MiniStarterQuery = { fg = palette.accent_primary },
    MiniStarterSection = { fg = palette.orange, style = "bold" },
    MiniStatuslineDevinfo = { fg = palette.text_muted, bg = palette.surface },
    MiniStatuslineFileinfo = { fg = palette.text_muted, bg = palette.surface },
    MiniStatuslineFilename = { fg = palette.text, bg = palette.base },
    MiniStatuslineInactive = { fg = palette.text_muted, bg = palette.base },
    MiniStatuslineModeCommand = { fg = palette.base, bg = palette.orange, style = "bold" },
    MiniStatuslineModeInsert = { fg = palette.base, bg = palette.accent_primary, style = "bold" },
    MiniStatuslineModeNormal = { fg = palette.base, bg = palette.accent_secondary, style = "bold" },
    MiniStatuslineModeOther = { fg = palette.base, bg = palette.accent_primary, style = "bold" },
    MiniStatuslineModeReplace = { fg = palette.base, bg = palette.error, style = "bold" },
    MiniStatuslineModeVisual = { fg = palette.base, bg = palette.amber, style = "bold" },
    MiniSurround = { fg = palette.text, bg = palette.amber },
    MiniTablineCurrent = { fg = palette.text, bg = palette.base, sp = palette.error, style = "bold,italic,underline" },
    MiniTablineFill = { bg = palette.base },
    MiniTablineHidden = { fg = palette.text, bg = palette.base },
    MiniTablineModifiedCurrent = { fg = palette.error, style = "bold,italic" },
    MiniTablineModifiedHidden = { fg = palette.error },
    MiniTablineModifiedVisible = { fg = palette.error },
    MiniTablineTabpagesection = { fg = palette.text_muted, bg = palette.base },
    MiniTablineVisible = { fg = palette.text },
    MiniTestEmphasis = { fg = palette.text, style = "bold" },
    MiniTestFail = { fg = palette.error, style = "bold" },
    MiniTestPass = { fg = palette.accent_primary, style = "bold" },
    MiniTrailspace = { bg = palette.error },
  }
end
