return function(palette)
  return {
    SnacksBackdrop = { bg = palette.surface, blend = 80 },
    SnacksDashboardDesc = { fg = palette.accent_secondary },
    SnacksDashboardDir = { fg = palette.text_muted },
    SnacksDashboardFile = { fg = palette.text },
    SnacksDashboardFooter = { fg = palette.amber, style = "italic" },
    SnacksDashboardHeader = { fg = palette.accent_secondary, style = "bold" },
    SnacksDashboardIcon = { fg = palette.orange, style = "bold" },
    SnacksDashboardKey = { fg = palette.orange },
    SnacksDashboardNormal = { fg = palette.text, bg = palette.base },
    SnacksDashboardSpecial = { fg = palette.orange },
    SnacksDashboardTerminal = { fg = palette.text, bg = palette.base },
    SnacksDashboardTitle = { fg = palette.error, style = "bold" },
    SnacksIndent = { fg = palette.surface },
    SnacksIndentScope = { fg = palette.surface_highlight },
    SnacksNormal = { fg = palette.text, bg = palette.base },
    SnacksNormalNC = { fg = palette.text, bg = palette.base },
    SnacksNotifierBorderDebug = { fg = palette.orange, bg = palette.base },
    SnacksNotifierBorderError = { fg = palette.error, bg = palette.base },
    SnacksNotifierBorderInfo = { fg = palette.accent_secondary, bg = palette.base },
    SnacksNotifierBorderTrace = { fg = palette.text, bg = palette.base },
    SnacksNotifierBorderWarn = { fg = palette.amber, bg = palette.base },
    SnacksNotifierDebug = { fg = palette.orange },
    SnacksNotifierError = { fg = palette.error },
    SnacksNotifierFooterDebug = { fg = palette.accent_secondary },
    SnacksNotifierFooterError = { fg = palette.error },
    SnacksNotifierFooterInfo = { fg = palette.accent_secondary },
    SnacksNotifierFooterTrace = { fg = palette.accent_secondary },
    SnacksNotifierFooterWarn = { fg = palette.orange },
    SnacksNotifierIconDebug = { fg = palette.orange },
    SnacksNotifierIconError = { fg = palette.error },
    SnacksNotifierIconInfo = { fg = palette.accent_secondary },
    SnacksNotifierIconTrace = { fg = palette.text },
    SnacksNotifierIconWarn = { fg = palette.amber },
    SnacksNotifierInfo = { fg = palette.accent_secondary },
    SnacksNotifierTitleDebug = { fg = palette.orange, style = "italic" },
    SnacksNotifierTitleError = { fg = palette.error, style = "italic" },
    SnacksNotifierTitleInfo = { fg = palette.accent_secondary, style = "italic" },
    SnacksNotifierTitleTrace = { fg = palette.text, style = "italic" },
    SnacksNotifierTitleWarn = { fg = palette.amber, style = "italic" },
    SnacksNotifierTrace = { fg = palette.text },
    SnacksNotifierWarn = { fg = palette.amber },
    SnacksPicker = { fg = palette.text, bg = palette.base },
    SnacksPickerBorder = { fg = palette.orange, bg = palette.base },
    SnacksPickerInput = { fg = palette.text, bg = palette.base },
    SnacksPickerInputBorder = { fg = palette.orange, bg = palette.base },
    SnacksPickerInputTitle = { fg = palette.text, bg = palette.error, style = "bold" },
    SnacksPickerListTitle = { fg = palette.base, bg = palette.amber, style = "bold" },
    SnacksPickerMatch = { fg = palette.accent_secondary, style = "bold" },
    SnacksPickerPreviewTitle = { fg = palette.base, bg = palette.accent_primary, style = "bold" },
    SnacksPickerPrompt = { fg = palette.orange },
    SnacksPickerSelected = { fg = palette.text_bright, bg = palette.surface, style = "bold" },
    SnacksPickerTitle = { fg = palette.base, bg = palette.amber, style = "bold" },
    SnacksWinBar = { fg = palette.error, style = "bold" },
    SnacksWinBarNC = { fg = palette.error, style = "bold" },
  }
end
