return function(palette)
  return {
    NeoTreeDimText = { fg = palette.text_muted },
    NeoTreeDirectoryIcon = { fg = palette.accent_primary },
    NeoTreeDirectoryName = { fg = palette.accent_primary },
    NeoTreeExpander = { fg = palette.text_muted },
    NeoTreeFileNameOpened = { fg = palette.text_bright },
    NeoTreeFilterTerm = { fg = palette.orange },
    NeoTreeFloatBorder = { fg = palette.orange, bg = palette.base },
    NeoTreeFloatTitle = { fg = palette.text, bg = palette.base, style = "bold" },
    NeoTreeGitAdded = { fg = palette.accent_secondary },
    NeoTreeGitConflict = { fg = palette.orange },
    NeoTreeGitDeleted = { fg = palette.error },
    NeoTreeGitIgnored = { fg = palette.text_muted },
    NeoTreeGitModified = { fg = palette.orange },
    NeoTreeGitStaged = { fg = palette.accent_primary },
    NeoTreeGitUnstaged = { fg = palette.warning },
    NeoTreeGitUntracked = { fg = palette.amber },
    NeoTreeIndentMarker = { fg = palette.surface_highlight },
    NeoTreeModified = { fg = palette.orange },
    NeoTreeNormal = { fg = palette.text, bg = palette.base },
    NeoTreeNormalNC = { fg = palette.text, bg = palette.base },
    NeoTreeRootName = { fg = palette.error, style = "bold" },
    NeoTreeStatusLineNC = { fg = palette.text_muted, bg = palette.base },
    NeoTreeSymbolicLinkTarget = { fg = palette.accent_secondary },
    NeoTreeTabActive = { fg = palette.text, bg = palette.surface },
    NeoTreeTabInactive = { fg = palette.text_muted, bg = palette.base },
    NeoTreeTabSeparatorActive = { fg = palette.orange, bg = palette.surface },
    NeoTreeTabSeparatorInactive = { fg = palette.surface_highlight, bg = palette.base },
    NeoTreeTitleBar = { fg = palette.base, bg = palette.accent_primary, style = "bold" },
    NeoTreeVertSplit = { fg = palette.surface, bg = palette.base },
    NeoTreeWinSeparator = { fg = palette.surface_highlight, bg = palette.base },

    NvimTreeEmptyFolderName = { fg = palette.text_muted },
    NvimTreeFolderIcon = { fg = palette.accent_primary },
    NvimTreeFolderName = { fg = palette.accent_primary },
    NvimTreeGitDeleted = { fg = palette.error },
    NvimTreeGitDirty = { fg = palette.orange },
    NvimTreeGitNew = { fg = palette.accent_secondary },
    NvimTreeImageFile = { fg = palette.amber },
    NvimTreeIndentMarker = { fg = palette.surface_highlight },
    NvimTreeNormal = { fg = palette.text, bg = palette.base },
    NvimTreeOpenedFile = { fg = palette.text_bright, style = "bold" },
    NvimTreeOpenedFolderName = { fg = palette.text_bright },
    NvimTreeRootFolder = { fg = palette.error, style = "bold" },
    NvimTreeSpecialFile = { fg = palette.amber, style = "underline" },
    NvimTreeStatuslineNc = { fg = palette.text_muted, bg = palette.base },
    NvimTreeSymlink = { fg = palette.accent_secondary },
    NvimTreeWinSeparator = { fg = palette.surface_highlight, bg = palette.base },
  }
end
