accent = "#8f00ff"
cursor = "#ff00ff"
foreground = "#ffffff"
background = "#240037"
selection_foreground = "#ffffff"
selection_background = "#543863"

color0 = "#262335"
color1 = "#ff0040"
color2 = "#8f00ff"
color3 = "#f3e70f"
color4 = "#0080ff"
color5 = "#ff00ff"
color6 = "#03edf9"
color7 = "#ffffff"
color8 = "#614d85"
color9 = "#fe5442"
color10 = "#fe5442"
color11 = "#ffff66"
color12 = "#0080ff"
color13 = "#ff7edb"
color14 = "#03edf9"
color15 = "#ffffff"
