# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0B0C16"

theme[main_fg]="#ddf7ff"

theme[title]="#86a7df"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7cf8f7"

# Background color of selected item in processes box
theme[selected_bg]="#6a6e95"

# Foreground color of selected item in processes box
theme[selected_fg]="#ddf7ff"

theme[inactive_fg]="#6a6e95"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#86a7df"

theme[cpu_box]="#4fe88f"
theme[mem_box]="#4fe88f"
theme[net_box]="#4fe88f"
theme[proc_box]="#4fe88f"
theme[div_line]="#6a6e95"

theme[temp_start]="#7cf8f7"
theme[temp_mid]="#829dd4"
theme[temp_end]="#4fe88f"


theme[cpu_start]="#7cf8f7"
theme[cpu_mid]="#829dd4"
theme[cpu_end]="#4fe88f"


theme[free_start]="#829dd4"
theme[free_mid]="#50f7d4"
theme[free_end]="#50f7d4"


theme[cached_start]="#50f7d4"
theme[cached_mid]="#50f7d4"
theme[cached_end]="#50f7d4"


theme[available_start]="#7cf8f7"
theme[available_mid]="#7cf8f7"
theme[available_end]="#7cf8f7"


theme[used_start]="#4fe88f"
theme[used_mid]="#4fe88f"
theme[used_end]="#4fe88f"


theme[download_start]="#50f7d4"
theme[download_mid]="#7cf8f7"
theme[download_end]="#829dd4"


theme[upload_start]="#50f7d4"
theme[upload_mid]="#7cf8f7"
theme[upload_end]="#829dd4"