return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#0b0c16",
				bg = "#0b0c16",
				dark_bg = "#080910",
				darker_bg = "#07070d",
				lighter_bg = "#1a1b24",
				selection = "#ddf7ff",
				selection_background = "#ddf7ff",
				selection_foreground = "#0b0c16",
				foreground = "#ddf7ff",
				fg = "#ddf7ff",
				light_fg = "#e0f8ff",
				bright_fg = "#ddf7ff",
				dark_fg = "#7e8d96",
				muted = "#6a6e95",
				cursor = "#ddf7ff",
				accent = "#82fb9c",
				red = "#50f872",
				green = "#4fe88f",
				yellow = "#50f7d4",
				blue = "#829dd4",
				purple = "#86a7df",
				magenta = "#86a7df",
				cyan = "#7cf8f7",
				orange = "#85ff9d",
				brown = "#6acc7e",
				bright_red = "#85ff9d",
				bright_green = "#9cf7c2",
				bright_yellow = "#a4ffec",
				bright_blue = "#c4d2ed",
				bright_purple = "#cddbf4",
				bright_cyan = "#d1fffe",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
