return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#070506",
				bg = "#070506",
				dark_bg = "#050404",
				darker_bg = "#040304",
				lighter_bg = "#161415",
				selection = "#979fec",
				selection_background = "#979fec",
				selection_foreground = "#070506",
				foreground = "#ffffff",
				fg = "#ffffff",
				light_fg = "#ffffff",
				bright_fg = "#ffffff",
				dark_fg = "#8f8e8f",
				muted = "#836f79",
				cursor = "#ffffff",
				accent = "#979fec",
				red = "#b37580",
				green = "#648ed0",
				yellow = "#e095b5",
				blue = "#979fec",
				purple = "#cd9dcf",
				magenta = "#cd9dcf",
				cyan = "#7c93dd",
				orange = "#d5aeb5",
				brown = "#aa8b91",
				bright_red = "#d5aeb5",
				bright_green = "#a7c1e8",
				bright_yellow = "#f6dbe6",
				bright_blue = "#e4e6fb",
				bright_purple = "#eddaee",
				bright_cyan = "#c3cef2",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
