return function(palette)
  return {
    ColorColumn = { bg = palette.base },
    CursorColumn = { bg = palette.surface },
    Cursor = { fg = palette.base, bg = palette.warning },
    CursorLine = { bg = palette.surface },
    CursorLineNr = { fg = palette.type, bg = palette.surface, style = "bold" },
    Directory = { fg = palette.type, bg = palette.base },
    Error = { fg = palette.text_bright, bg = palette.orange },
    ErrorMsg = { fg = palette.error, bg = palette.base },
    FloatShadow = { bg = palette.shadow },
    FloatShadowThrough = { bg = palette.shadow_through },
    FoldColumn = { fg = palette.text_muted, bg = palette.surface },
    Folded = { fg = palette.error, bg = palette.surface },
    IncSearch = { fg = palette.base, bg = palette.orange },
    LineNr = { fg = palette.text_muted, bg = palette.surface },
    MatchParen = { fg = palette.text, style = "bold,underline" },
    ModeMsg = { style = "bold" },
    MoreMsg = { fg = palette.accent_secondary, style = "bold" },
    NonText = { fg = palette.text_muted, style = "bold" },
    Normal = { fg = palette.text, bg = palette.base },
    Pmenu = { fg = palette.text, bg = palette.surface },
    PmenuSbar = { bg = palette.text_muted },
    PmenuSel = { fg = palette.base, bg = palette.selection },
    PmenuThumb = { fg = palette.text, bg = palette.text },
    Question = { fg = palette.accent_secondary, style = "bold" },
    RedrawDebugClear = { fg = palette.base, bg = palette.amber },
    RedrawDebugComposed = { fg = palette.base, bg = palette.accent_primary },
    RedrawDebugNormal = { style = "reverse" },
    RedrawDebugRecompose = { fg = palette.base, bg = palette.orange },
    Search = { fg = palette.base, bg = palette.accent_secondary },
    SignColumn = { fg = palette.text_muted, bg = palette.surface },
    SpecialKey = { fg = palette.text },
    StatusLine = { fg = palette.text, bg = palette.base, style = "bold" },
    StatusLineNC = { fg = palette.text_muted, bg = palette.base, style = "bold" },
    TabLineFill = { fg = palette.amber, bg = palette.base },
    TabLine = { fg = palette.text_muted, bg = palette.surface_edge },
    TabLineSel = { fg = palette.surface_edge, bg = palette.accent_primary, style = "bold" },
    TabLineSelSep = { fg = palette.accent_primary, bg = palette.surface, style = "bold" },
    TabLineSep = { fg = palette.surface_edge, bg = palette.base },
    TermCursor = { style = "reverse" },
    Title = { fg = palette.error, style = "bold" },
    User1 = { fg = palette.text, bg = palette.orange },
    User2 = { fg = palette.text, bg = palette.text_muted },
    User3 = { fg = palette.text, bg = palette.error },
    User4 = { fg = palette.text, bg = palette.base },
    User5 = { fg = palette.text, bg = palette.orange },
    User6 = { fg = palette.text, bg = palette.amber },
    User7 = { fg = palette.text, bg = palette.type },
    User8 = { fg = palette.text, bg = palette.error },
    User9 = { fg = palette.text, bg = palette.text_muted },
    VertSplit = { fg = palette.surface, bg = palette.base },
    Visual = { fg = palette.base, bg = palette.selection },
    WarningMsg = { fg = palette.error },
    WildMenu = { fg = "black", bg = palette.amber },
    WinBar = { style = "bold" },
  }
end
