return function(palette)
  return {
    DiagnosticDeprecated = { sp = palette.warning, style = "strikethrough" },
    DiagnosticError = { fg = palette.error },
    DiagnosticHintFloating = { fg = palette.type },
    DiagnosticHint = { fg = palette.accent_secondary },
    DiagnosticInfo = { fg = palette.accent_secondary },
    DiagnosticOk = { fg = palette.type },
    DiagnosticSignError = { fg = palette.error, bg = palette.surface },
    DiagnosticSignHint = { fg = palette.accent_secondary, bg = palette.surface },
    DiagnosticSignInfo = { fg = palette.type, bg = palette.surface },
    DiagnosticSignWarn = { fg = palette.warning, bg = palette.surface },
    DiagnosticUnderlineError = { sp = palette.error, style = "undercurl" },
    DiagnosticUnderlineHint = { sp = palette.type, style = "undercurl" },
    DiagnosticUnderlineInfo = { sp = palette.accent_secondary, style = "undercurl" },
    DiagnosticUnderlineOk = { sp = palette.type, style = "undercurl" },
    DiagnosticUnderlineWarn = { sp = palette.warning, style = "undercurl" },
    DiagnosticUnnecessary = { fg = palette.text_muted, style = "underline" },
    DiagnosticVirtualTextError = { fg = palette.error },
    DiagnosticVirtualTextHint = { fg = palette.type, bg = palette.base },
    DiagnosticVirtualTextInfo = { fg = palette.type, bg = palette.base },
    DiagnosticVirtualTextWarn = { fg = palette.warning, bg = palette.base },
    DiagnosticVirtualTextWarning = { fg = palette.warning, bg = palette.base },
    DiagnosticWarn = { fg = palette.warning },
    DiagnosticWarningFloating = { fg = palette.warning },
    DiagnosticWarning = { fg = palette.warning },
    LspBorderBG = { fg = palette.warning, bg = palette.base },
    LspFloatWinNormal = { fg = palette.text, bg = palette.surface_highlight },
    LspInlayHint = { fg = palette.text_muted, style = "italic" },
    LspReferenceRead = { fg = palette.accent_secondary, sp = palette.reference, style = "bold,undercurl" },
    LspReferenceText = { fg = palette.text, bg = palette.surface_highlight, sp = palette.reference, style = "bold,undercurl" },
    LspReferenceWrite = { fg = palette.accent_secondary, sp = palette.reference, style = "bold,undercurl" },
    LspSignatureActiveParameter = { sp = palette.signature, style = "bold,italic,underline" },
  }
end
