return function(palette)
  return {
    ["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
    ["@lsp.mod.defaultLibrary"] = { fg = palette.orange },
    ["@lsp.mod.readonly"] = { fg = palette.amber },
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.decorator"] = { link = "Function" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { fg = palette.amber },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.macro"] = { fg = palette.orange },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { fg = palette.accent_secondary, style = "italic" },
    ["@lsp.type.parameter"] = { fg = palette.amber },
    ["@lsp.type.property"] = { fg = palette.text },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { fg = palette.amber },
    ["@lsp.type.variable"] = { fg = palette.text },
    ["@lsp.typemod.function.builtin"] = { fg = palette.orange },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = palette.orange },
    ["@lsp.typemod.method.defaultLibrary"] = { fg = palette.orange },
    ["@lsp.typemod.property.readonly"] = { fg = palette.amber },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = palette.orange },
    ["@lsp.typemod.variable.globalScope"] = { fg = palette.orange },
    ["@lsp.typemod.variable.readonly"] = { fg = palette.amber },
  }
end
