return function(palette)
  return {
    Boolean = { fg = palette.type },
    Comment = { fg = palette.comment },
    Constant = { fg = palette.orange },
    Delimiter = { fg = palette.text },
    DiffAdded = { fg = palette.diff_add, bg = palette.surface },
    DiffAdd = { fg = palette.base, bg = palette.diff_add },
    DiffChange = { fg = palette.base, bg = palette.diff_change },
    DiffDelete = { fg = palette.base, bg = palette.diff_delete, style = "bold" },
    DiffRemoved = { fg = palette.diff_delete, bg = palette.surface },
    DiffText = { fg = palette.base, bg = palette.diff_text, style = "bold" },
    Function = { fg = palette.func },
    gitCommitBranch = { fg = palette.error },
    gitCommitSelectedFile = { fg = palette.accent_secondary },
    gitCommitSelectedType = { fg = palette.accent_secondary },
    gitCommitUnmergedFile = { fg = palette.warning },
    gitCommitUnmergedType = { fg = palette.warning },
    htmlArg = { fg = palette.accent_secondary },
    htmlBold = { style = "bold" },
    htmlBoldItalic = { style = "bold,italic" },
    htmlBoldUnderline = { style = "bold,underline" },
    htmlBoldUnderlineItalic = { style = "bold,italic,underline" },
    htmlH1 = { style = "bold" },
    htmlItalic = { style = "italic" },
    htmlTag = { fg = palette.accent_secondary },
    htmlTagName = { fg = palette.accent_secondary },
    htmlUnderline = { style = "underline" },
    htmlUnderlineItalic = { style = "underline" },
    Identifier = { fg = palette.identifier },
    Ignore = { fg = palette.text_subtle, style = "underline" },
    Keyword = { fg = palette.keyword },
    lessVariable = { fg = palette.error },
    markdownBold = { style = "bold" },
    markdownItalic = { style = "italic" },
    mustacheMarker = { fg = palette.orange },
    mustachePartial = { fg = palette.orange },
    mustacheSection = { style = "bold" },
    mustacheVariable = { fg = palette.amber },
    mustacheVariableUnescape = { fg = palette.warning },
    netrwClassify = { fg = palette.text_muted, style = "bold" },
    netrwExe = { fg = palette.warning },
    Number = { fg = palette.type },
    NvimInternalError = { fg = palette.surface, bg = palette.error },
    phpIdentifier = { fg = palette.error },
    phpSpecialFunction = { fg = palette.orange },
    shDerefSimple = { fg = palette.error },
    Special = { fg = palette.special },
    SpellBad = { fg = palette.warning, sp = palette.text, style = "underline" },
    SpellCap = { fg = palette.accent_secondary, sp = palette.text, style = "underline" },
    SpellLocal = { fg = palette.orange, sp = palette.text, style = "underline" },
    SpellRare = { fg = palette.error, sp = palette.text, style = "underline" },
    Statement = { fg = palette.keyword, style = "bold" },
    String = { fg = palette.string },
    SyntasticErrorSign = { fg = palette.error },
    SyntasticWarningSign = { fg = palette.warning },
    Todo = { fg = palette.text, style = "bold,underline" },
    Type = { fg = palette.type, style = "bold" },
    Underlined = { fg = palette.type, style = "underline" },
    WarningMsg = { fg = palette.error },
    xmlTag = { fg = palette.type },
    xmlTagName = { fg = palette.type },
  }
end
