return function(palette)
  return {
    ["@attribute"] = { fg = palette.orange },
    ["@character"] = { fg = palette.amber },
    ["@character.special"] = { fg = palette.orange },
    ["@comment.documentation"] = { fg = palette.text_muted, style = "italic" },
    ["@comment.error"] = { fg = palette.base, bg = palette.error, style = "bold" },
    ["@comment.hint"] = { fg = palette.base, bg = palette.accent_primary, style = "bold" },
    ["@comment.note"] = { fg = palette.base, bg = palette.accent_secondary, style = "bold" },
    ["@comment.todo"] = { fg = palette.base, bg = palette.amber, style = "bold" },
    ["@comment.warning"] = { fg = palette.base, bg = palette.orange, style = "bold" },
    ["@constant.macro"] = { fg = palette.orange },
    ["@constructor.lua"] = { fg = palette.special },
    ["@diff.delta"] = { fg = palette.orange },
    ["@diff.minus"] = { fg = palette.error },
    ["@diff.plus"] = { fg = palette.accent_secondary },
    ["@function.call"] = { fg = palette.accent_primary },
    ["@function.macro"] = { fg = palette.orange },
    ["@function.method"] = { fg = palette.accent_primary },
    ["@function.method.call"] = { fg = palette.accent_primary },
    ["@keyword.conditional"] = { fg = palette.accent_secondary, style = "bold" },
    ["@keyword.conditional.ternary"] = { fg = palette.text },
    ["@keyword.coroutine"] = { fg = palette.accent_secondary, style = "bold" },
    ["@keyword.debug"] = { fg = palette.error, style = "bold" },
    ["@keyword.directive"] = { fg = palette.orange },
    ["@keyword.directive.define"] = { fg = palette.orange, style = "bold" },
    ["@keyword.exception"] = { fg = palette.error, style = "bold" },
    ["@keyword.function"] = { fg = palette.accent_secondary, style = "bold" },
    ["@keyword.import"] = { fg = palette.orange },
    ["@keyword.modifier"] = { fg = palette.accent_secondary },
    ["@keyword.operator"] = { fg = palette.text },
    ["@keyword.repeat"] = { fg = palette.accent_secondary, style = "bold" },
    ["@keyword.return"] = { fg = palette.accent_secondary, style = "bold" },
    ["@keyword.type"] = { fg = palette.accent_primary, style = "bold" },
    ["@markup"] = { fg = palette.text },
    ["@markup.heading"] = { fg = palette.error, style = "bold" },
    ["@markup.heading.1.markdown"] = { fg = palette.error, style = "bold" },
    ["@markup.heading.2.markdown"] = { fg = palette.orange, style = "bold" },
    ["@markup.heading.3.markdown"] = { fg = palette.amber, style = "bold" },
    ["@markup.heading.4.markdown"] = { fg = palette.accent_primary, style = "bold" },
    ["@markup.heading.5.markdown"] = { fg = palette.accent_secondary, style = "bold" },
    ["@markup.heading.6.markdown"] = { fg = palette.text, style = "bold" },
    ["@markup.italic"] = { fg = palette.text, style = "italic" },
    ["@markup.link"] = { fg = palette.accent_primary, style = "underline" },
    ["@markup.link.label"] = { fg = palette.text },
    ["@markup.link.url"] = { fg = palette.accent_secondary, style = "underline" },
    ["@markup.list"] = { fg = palette.accent_secondary },
    ["@markup.list.checked"] = { fg = palette.accent_primary, style = "bold" },
    ["@markup.list.unchecked"] = { fg = palette.text_muted },
    ["@markup.math"] = { fg = palette.amber },
    ["@markup.quote"] = { fg = palette.text_muted, style = "italic" },
    ["@markup.raw"] = { fg = palette.orange },
    ["@markup.strikethrough"] = { fg = palette.text_muted, style = "strikethrough" },
    ["@markup.strong"] = { fg = palette.text, style = "bold" },
    ["@module"] = { fg = palette.accent_primary, style = "italic" },
    ["@number.float"] = { fg = palette.accent_primary },
    ["@operator"] = { fg = palette.text },
    ["@property.css"] = { fg = palette.accent_secondary },
    ["@property.scss"] = { fg = palette.accent_secondary },
    ["@punctuation.bracket"] = { fg = palette.text_muted },
    ["@punctuation.delimiter"] = { fg = palette.text },
    ["@punctuation.special"] = { fg = palette.orange },
    ["@string.documentation"] = { fg = palette.amber, style = "italic" },
    ["@string.escape"] = { fg = palette.error },
    ["@string.regexp"] = { fg = palette.accent_secondary },
    ["@string.special"] = { fg = palette.orange },
    ["@string.special.path"] = { fg = palette.accent_primary },
    ["@string.special.symbol"] = { fg = palette.amber },
    ["@string.special.url"] = { fg = palette.accent_secondary, style = "underline" },
    ["@tag"] = { fg = palette.accent_primary },
    ["@tag.attribute"] = { fg = palette.accent_secondary, style = "italic" },
    ["@tag.builtin"] = { fg = palette.accent_primary, style = "bold" },
    ["@tag.delimiter"] = { fg = palette.text_muted },
    ["@type.builtin"] = { fg = palette.accent_primary, style = "bold" },
    ["@type.definition"] = { fg = palette.accent_primary, style = "bold" },
    ["@variable.builtin"] = { fg = palette.error, style = "italic" },
    ["@variable.member"] = { fg = palette.text },
    ["@variable.parameter"] = { fg = palette.amber },
  }
end
