return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#1a1b1f",
				bg = "#1a1b1f",
				dark_bg = "#141417",
				darker_bg = "#101013",
				lighter_bg = "#28292c",
				selection = "#7b8da3",
				selection_background = "#7b8da3",
				selection_foreground = "#1a1b1f",
				foreground = "#eff2f5",
				fg = "#eff2f5",
				light_fg = "#f1f3f6",
				bright_fg = "#eff2f5",
				dark_fg = "#8f9195",
				muted = "#8a8c94",
				cursor = "#eff2f5",
				accent = "#7b8da3",
				red = "#7a92ae",
				green = "#9eafc0",
				yellow = "#a8b6c4",
				blue = "#7b8da3",
				purple = "#a6b1bf",
				magenta = "#a6b1bf",
				cyan = "#aabaca",
				orange = "#b2c1d2",
				brown = "#8e9aa8",
				bright_red = "#b2c1d2",
				bright_green = "#d5dde5",
				bright_yellow = "#dee4ea",
				bright_blue = "#b0bcca",
				bright_purple = "#dbe0e6",
				bright_cyan = "#e2e8ee",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
