-- Auto-generated by VGS. Do not edit.
VGS_THEME = {
  name = "{name}",
  mode = "{theme_type}",
  primary = "rgb({accent.strip})",
  on_primary = "rgb({onPrimary.strip})",
  outline = "rgb({outline.strip})",
  error = "rgb({error.strip})",
  warning = "rgb({warning.strip})",
  success = "rgb({success.strip})",
  background = "rgb({background.strip})",
  foreground = "rgb({foreground.strip})",
  groupbar_active_bg = "rgb({groupbarActiveBg.strip})",
  groupbar_active_fg = "rgb({groupbarActiveFg.strip})",
  groupbar_inactive_bg = "rgb({groupbarInactiveBg.strip})",
  groupbar_inactive_fg = "rgb({groupbarInactiveFg.strip})",
  groupbar_locked_bg = "rgb({groupbarLockedBg.strip})",
  groupbar_locked_fg = "rgb({groupbarLockedFg.strip})",
}
