#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

pattern='dank|DANK|Dank|Dms|DMS|dms|Aether|aether|DankMaterialShell|danklinux'

# Read locally owned skill paths from kendex.toml through its shared reader.
# Capture its status directly; process substitution can hide a failed reader and leave the scan empty.
if ! skills_raw="$(python3 scripts/lib/kendex_skills.py)"; then
  printf 'check-naming: kendex.toml could not be read, so no skill tree was scanned.\n' >&2
  exit 1
fi
mapfile -t skill_paths <<< "$skills_raw"

# An absent declared path would silently narrow the naming scan.
missing=()
paths=()
for p in \
  README.md \
  quickshell/vshell \
  config/vshell \
  bin \
  backend \
  systemd \
  themes \
  AGENTS.md \
  "${skill_paths[@]}" \
  docs/architecture
do
  if [[ -e "$p" ]]; then
    paths+=("$p")
  else
    missing+=("$p")
  fi
done

if (( ${#missing[@]} )); then
  printf 'check-naming: these scanned paths do not exist, so they were NOT scanned\n' >&2
  printf '  - %s\n' "${missing[@]}" >&2
  printf 'A renamed or removed path updates this list in the same PR; a skill path comes from kendex.toml.\n' >&2
  exit 1
fi

# themes/*/apps/* are curated files imported verbatim from omarchy; they may
# reference third-party plugins (e.g. the aether.nvim colorscheme) by name.
# config/vshell/nvim/colorschemes/** are third-party nvim colorscheme plugins
# vendored verbatim (with their own LICENSE); they keep their upstream naming.
# backend/ATTRIBUTION.md carries upstream license/lineage, which is exempt.
# backend/vendor/** is generated by `go mod vendor` for offline Nix/package builds.
raw="$(rg -n -S --hidden \
  --glob '!quickshell/vshell/LICENSE' \
  --glob '!quickshell/vshell/LICENSE_CHANGE_12_11_2025.md' \
  --glob '!themes/*/apps/*' \
  --glob '!config/vshell/nvim/colorschemes/**' \
  --glob '!backend/ATTRIBUTION.md' \
  --glob '!backend/vendor/**' \
  "$pattern" "${paths[@]}" || true)"

# Full project names support attribution; the Ubuntu PPA name is required by install commands.
# Remove only the accepted strings so other matches on the same line remain visible.
matches=""
while IFS= read -r line; do
  [[ -n "$line" ]] || continue
  normalized="${line//DankMaterialShell/}"
  normalized="${normalized//ppa:avengemedia\/danklinux/}"
  if printf '%s' "$normalized" | rg -q -S "$pattern"; then
    matches+="$line"$'\n'
  fi
done <<< "$raw"

if [[ -n "$matches" ]]; then
  printf 'Legacy upstream naming residue found:\n%s' "$matches" >&2
  exit 1
fi

printf 'No legacy upstream naming residue found.\n'
