#!/usr/bin/env python3
"""Generate packaging optional-dependency metadata from the VGS feature manifest.

`config/vshell/dependencies.json` is the single source of truth for which
commands back which VGS feature group. `packaging/optional-packages.json` maps
those commands to distribution package names and marks which of them back
first-class UI. This script joins the two and rewrites the generated blocks in
the packaging recipes so that the tools behind default UI are installed with the
package, and a package manager can tell a user what else is missing.

Usage:
  scripts/gen-package-metadata.py            # verify the recipes are current
  scripts/gen-package-metadata.py --write    # regenerate them
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "config" / "vshell" / "dependencies.json"
MAPPING = ROOT / "packaging" / "optional-packages.json"

# Channels with a weak-dependency mechanism, so they carry both the generated
# hard dependencies and the generated optional ones.
DISTROS = ("arch", "debian", "fedora", "gentoo")
# Channels that get hard dependencies only. Void has no weak-dependency
# mechanism at all (its optional tools are covered by INSTALL.msg and
# `vshell deps status`), and the Nix wrapper is a PATH, not a package relation.
# They were hand-maintained until VGS-53, which is how Void kept shipping
# `depends="quickshell jq python3"` after every other channel had been fixed.
REQUIRED_ONLY = ("void", "nix")
REQUIRED_DISTROS = DISTROS + REQUIRED_ONLY

# Every packaging channel this repo ships, and where its recipe lives. A
# directory under packaging/ that appears in neither table fails the run: a new
# channel must state whether its dependencies are generated, rather than being
# quietly left out the way Void was.
CHANNEL_RECIPES = {
    "arch": "packaging/arch/PKGBUILD",
    "debian": "packaging/debian/control",
    "fedora": "packaging/fedora/vgs-shell.spec",
    "gentoo": "packaging/gentoo/vgs-shell-0.1.0.ebuild",
    "void": "packaging/void/template",
    "nix": "flake.nix",
}
# Every file that has to declare the notification-daemon conflicts, which is not
# the same set as CHANNEL_RECIPES: Arch alone ships four, and the three that are
# NOT packaging/arch/PKGBUILD are precisely the ones published to the AUR.
CONFLICT_RECIPES = {
    "arch": (
        "packaging/arch/PKGBUILD",
        "packaging/arch/.SRCINFO",
        "packaging/arch/vgs-shell-git/PKGBUILD",
        "packaging/arch/vgs-shell-git/.SRCINFO",
    ),
    "debian": ("packaging/debian/control",),
    "fedora": ("packaging/fedora/vgs-shell.spec",),
    "gentoo": ("packaging/gentoo/vgs-shell-0.1.0.ebuild",),
    "void": ("packaging/void/template",),
}
UNGENERATED_CHANNELS = {
    "ubuntu": (
        "README only: the Launchpad PPA builds from packaging/debian, so its "
        "dependencies are that channel's generated ones"
    ),
}

BEGIN = "# BEGIN GENERATED OPTIONAL DEPENDENCIES"
END = "# END GENERATED OPTIONAL DEPENDENCIES"
BEGIN_REQUIRED = "# BEGIN GENERATED REQUIRED DEPENDENCIES"
END_REQUIRED = "# END GENERATED REQUIRED DEPENDENCIES"
NOTE = (
    "# Generated by scripts/gen-package-metadata.py from\n"
    "# config/vshell/dependencies.json and packaging/optional-packages.json.\n"
    "# Run scripts/gen-package-metadata.py --write after changing either file."
)


class GenError(Exception):
    pass


def feature_commands(feature: dict) -> list[str]:
    """Every command a feature group can require, in manifest order."""
    out: list[str] = []
    for command in feature.get("commands", []):
        out.append(command)
    for alternatives in feature.get("anyCommands", []):
        out.extend(alternatives)
    for commands in feature.get("compositorCommands", {}).values():
        out.extend(commands)
    return out


def conflict_packages(mapping: dict) -> tuple[dict[str, list[str]], list[tuple[str, str, str]]]:
    """Return ({channel: [package]}, waivers) for the daemons VGS conflicts with.

    Same shape and same rule as required_packages(): a daemon with no package
    on a channel must be waived by name with a reason. The channels had already
    drifted apart before this existed — Fedora named four daemons, Arch and
    Debian three, Gentoo and Void a different three (VGS-56).
    """
    section = mapping.get("conflicts")
    if section is None:
        raise GenError('packaging/optional-packages.json has no "conflicts" section')
    daemons = section.get("daemons", {})
    unsupported = section.get("unsupported", {})

    # Nix installs into a profile rather than a distribution package set, so it
    # has no package-relation to express a conflict with. Validating waivers
    # against the SAME tuple the loop below walks is the point: validating
    # against REQUIRED_DISTROS accepted a `nix` waiver that was then never
    # honoured and never printed — a silent state, which is exactly what the
    # stale-waiver check exists to prevent.
    channels = tuple(channel for channel in REQUIRED_DISTROS if channel != "nix")

    for daemon, waived in unsupported.items():
        if daemon not in daemons:
            raise GenError(
                f'"conflicts".unsupported names {daemon!r}, which is not a '
                "conflicting daemon; the waiver would never be read"
            )
        unknown = set(waived) - set(channels)
        if unknown:
            raise GenError(
                f"conflict waiver for {daemon!r} names unknown channel(s): "
                + ", ".join(sorted(unknown))
            )
        for channel, reason in waived.items():
            if not reason:
                raise GenError(f"conflict waiver for {daemon!r} on {channel} has no reason")
            if daemons[daemon].get(channel) is not None:
                raise GenError(
                    f"{daemon!r} is waived as unsupported on {channel} but the "
                    "mapping names a package for it; drop the stale waiver"
                )

    result: dict[str, list[str]] = {channel: [] for channel in channels}
    waivers: list[tuple[str, str, str]] = []

    for daemon, entry in daemons.items():
        for channel in channels:
            package = entry.get(channel)
            if package is None:
                reason = unsupported.get(daemon, {}).get(channel)
                if reason is None:
                    raise GenError(
                        f"conflicting daemon {daemon!r} names no {channel} "
                        "package. Two notification daemons on one session is "
                        "not a supported configuration on any channel, so this "
                        "cannot just be left out of one recipe. Add the package "
                        f'name, or waive it in "conflicts".unsupported.{daemon}.'
                        f"{channel} with the reason."
                    )
                waivers.append((daemon, channel, reason))
                continue
            result[channel].append(package)

    return result, waivers


def _strip_relation(atom: str) -> str:
    """`mako>=0`, `vgs-shell=0.1.0-4` and `mako-notifier (<< 1.0)` all name mako."""
    return re.split(r"[<>=(\s]", atom.strip(), maxsplit=1)[0].strip()


def _shell_word_list(fragment: str, path: Path) -> list[str]:
    """Split a shell word list, honouring `#` comments.

    `shlex.split` without this drops the `#` and keeps the words behind it, so
    `# 'swaync' disabled for now` reads as a declared conflict with swaync and
    the check passes over a package the recipe no longer conflicts with. An
    unmatched quote inside such a comment would otherwise abort the whole
    generator, which is why comment handling has to happen inside the lexer
    rather than as a pre-pass.
    """
    lexer = shlex.shlex(fragment, posix=True)
    lexer.whitespace_split = True
    lexer.commenters = "#"
    try:
        return list(lexer)
    except ValueError as error:
        raise GenError(f"{path}: cannot read a shell word list: {error}") from error


def _shell_words(fragment: str, path: Path) -> set[str]:
    return set(_shell_word_list(fragment, path))


def _shell_scopes(text: str, func: re.Pattern[str]) -> tuple[str, dict[str, str]]:
    """Split a shell recipe into its top level and each function `func` matches.

    Brace-counted rather than parsed. A recipe whose braces do not balance ends
    up with its tail attributed to a function, so the main package looks like it
    declares less than it does — the check then fails, which is the direction a
    misread has to fail in.
    """
    top: list[str] = []
    bodies: dict[str, list[str]] = {}
    current: str | None = None
    depth = 0
    for line in text.splitlines(keepends=True):
        if current is None:
            match = func.match(line)
            if match:
                current = match.group(1)
                bodies.setdefault(current, [])
                depth = line.count("{") - line.count("}")
                continue
            top.append(line)
            continue
        depth += line.count("{") - line.count("}")
        if depth <= 0:
            current = None
            continue
        bodies[current].append(line)
    return "".join(top), {name: "".join(body) for name, body in bodies.items()}


def _shell_assignment(text: str, name: str, path: Path) -> set[str] | None:
    """Every value assigned to `name`, or None when it is never assigned.

    None and the empty set are different answers: an unassigned variable in a
    package function inherits the top-level one, an assigned-but-empty one
    overrides it with nothing.
    """
    values: set[str] | None = None
    pattern = rf"^[ \t]*{re.escape(name)}=(?:\(([^)]*)\)|\"([^\"]*)\"|(\S+))"
    for match in re.finditer(pattern, text, re.MULTILINE):
        if values is None:
            values = set()
        values |= _shell_words(next(g for g in match.groups() if g is not None), path)
    return values


def _pkgbuild_conflicts(text: str, path: Path) -> set[str]:
    """The main package's conflicts in a (possibly split) PKGBUILD.

    makepkg runs each `package_*()` in its own scope over the top-level
    variables, so a function that assigns `conflicts` replaces the global one
    and a function that does not inherits it. Aggregating every function's
    conflicts instead — what this used to do — lets a daemon moved to a
    subpackage keep satisfying the check for the package that no longer
    conflicts with it.
    """
    base = re.search(r"^pkgbase=(\S+)", text, re.MULTILINE)
    if base is not None:
        main = _shell_word_list(base.group(1), path)[0]
    else:
        # Without pkgbase, makepkg takes the FIRST pkgname as the base, so the
        # order matters and the word list has to stay a list.
        listed = re.search(r"^pkgname=(?:\(([^)]*)\)|(\S+))", text, re.MULTILINE)
        names = _shell_word_list(listed.group(1) or listed.group(2), path) if listed else []
        if not names:
            raise GenError(f"{path}: no pkgbase= or pkgname= to identify the main package")
        main = names[0]

    top, functions = _shell_scopes(text, re.compile(r"^(package(?:_[\w.+-]+)?)\s*\(\)"))
    body = functions.get(f"package_{main}", functions.get("package"))
    if body is None and functions:
        raise GenError(
            f"{path}: no package_{main}() or package() function, so there is no "
            "way to tell which conflicts belong to the main package"
        )
    scoped = _shell_assignment(body, "conflicts", path) if body is not None else None
    if scoped is not None:
        return scoped
    return _shell_assignment(top, "conflicts", path) or set()


def _srcinfo_conflicts(text: str, path: Path) -> set[str]:
    """The main package's conflicts in a .SRCINFO.

    The `pkgbase` block holds the defaults; a `pkgname` block overrides a key it
    names for that package alone. Only the block for the package named by
    `pkgbase` — the shell itself — is the main package.
    """
    base = re.search(r"^pkgbase = (\S+)", text, re.MULTILINE)
    if base is None:
        raise GenError(f"{path}: no pkgbase line to identify the main package")
    main = base.group(1)

    sections: list[tuple[str | None, list[str]]] = [(None, [])]
    for line in text.splitlines():
        named = re.match(r"^pkgname = (\S+)", line)
        if named:
            sections.append((named.group(1), []))
            continue
        sections[-1][1].append(line)

    def conflicts(lines: list[str]) -> set[str] | None:
        found = [
            _strip_relation(match.group(1))
            for match in (re.match(r"^[ \t]*conflicts = (.+)$", line) for line in lines)
            if match
        ]
        return set(found) if found else None

    for name, lines in sections[1:]:
        if name == main:
            return conflicts(lines) or conflicts(sections[0][1]) or set()
    raise GenError(f"{path}: no pkgname = {main} section for the pkgbase package")


def _control_conflicts(text: str, path: Path) -> set[str]:
    """The main binary package's Conflicts: in a Debian control file.

    Every binary package gets its own stanza, so the union across stanzas says
    nothing about what installing the shell conflicts with.
    """
    stanzas: list[list[str]] = [[]]
    for line in text.splitlines():
        if not line.strip():
            stanzas.append([])
            continue
        if line.startswith("#"):
            continue
        stanzas[-1].append(line)

    def field(lines: list[str], name: str) -> str | None:
        for index, line in enumerate(lines):
            match = re.match(rf"^{name}:(.*)$", line)
            if not match:
                continue
            value = [match.group(1)]
            for follow in lines[index + 1 :]:
                if not follow[:1].isspace():
                    break
                value.append(follow)
            return "".join(value)
        return None

    source = next((field(s, "Source") for s in stanzas if field(s, "Source")), None)
    binaries = [(field(s, "Package"), s) for s in stanzas if field(s, "Package")]
    named = [s for name, s in binaries if source and name and name.strip() == source.strip()]
    if named:
        main = named[0]
    elif len(binaries) == 1:
        main = binaries[0][1]
    else:
        raise GenError(
            f"{path}: no Package stanza matching Source: {source!r} among "
            f"{len(binaries)} binary packages, so the main package is ambiguous"
        )

    value = field(main, "Conflicts") or ""
    return {name for name in (_strip_relation(entry) for entry in value.split(",")) if name}


def _spec_conflicts(text: str, path: Path) -> set[str]:
    """The main package's Conflicts: in an RPM spec.

    The preamble — everything before the first section directive — belongs to
    the package named by `Name:`. A `%package foo` subpackage preamble that
    follows declares foo's conflicts, not the main package's.
    """
    if re.search(r"^Name:[ \t]*(\S+)", text, re.MULTILINE) is None:
        raise GenError(f"{path}: no Name: field to identify the main package")
    end = re.search(
        r"^%(package|description|prep|build|install|check|files|changelog|pre|post|"
        r"preun|postun|trigger)\b",
        text,
        re.MULTILINE,
    )
    preamble = text[: end.start()] if end else text
    preamble = re.sub(r"^[ \t]*#.*$", "", preamble, flags=re.MULTILINE)
    return set(re.findall(r"^Conflicts:[ \t]*(\S+)", preamble, re.MULTILINE))


def _ebuild_conflicts(text: str, path: Path) -> set[str]:
    """Portage blockers in an ebuild's runtime dependency strings.

    An ebuild builds one package, so scoping is about reading the declaration
    rather than the file: a `!` in a comment, a `sed` expression or BDEPEND is
    not a runtime blocker.
    """
    declared: set[str] = set()
    found = False
    for match in re.finditer(r'^(?:R|P)?DEPEND\+?="([^"]*)"', text, re.MULTILINE):
        found = True
        body = re.sub(r"^[ \t]*#.*$", "", match.group(1), flags=re.MULTILINE)
        declared.update(re.findall(r"^[ \t]*!+([\w./+-]+)", body, re.MULTILINE))
    if not found:
        raise GenError(f"{path}: no RDEPEND/DEPEND/PDEPEND string to read blockers from")
    return declared


def _template_conflicts(text: str, path: Path) -> set[str]:
    """The main package's conflicts in a Void template.

    xbps subpackages are `<name>_package()` functions that set their own
    `conflicts`; only the top-level assignment is the main package's.
    """
    if re.search(r"^pkgname=(\S+)", text, re.MULTILINE) is None:
        raise GenError(f"{path}: no pkgname= to identify the main package")
    top, _ = _shell_scopes(text, re.compile(r"^([\w.+-]+)\s*\(\)"))
    values = _shell_assignment(top, "conflicts", path) or set()
    return {_strip_relation(value) for value in values}


def declared_conflicts(path: Path) -> set[str]:
    """The packages the recipe's MAIN package declares a conflict with.

    Reading the declaration rather than searching the file: a package name in a
    comment, a Suggests: line or a URL is not a conflict, and a check that
    accepts one reports success over ground it never examined — the same defect
    this script exists to catch, one level up. Scope is the other half of that:
    every format here can ship several packages from one recipe, and a conflict
    declared by the assets subpackage does not make installing the shell
    conflict with anything.
    """
    text = path.read_text()

    if path.name == "PKGBUILD":
        declared = _pkgbuild_conflicts(text, path)
    elif path.name == ".SRCINFO":
        declared = _srcinfo_conflicts(text, path)
    elif path.name == "control":
        declared = _control_conflicts(text, path)
    elif path.suffix == ".spec":
        declared = _spec_conflicts(text, path)
    elif path.suffix == ".ebuild":
        declared = _ebuild_conflicts(text, path)
    elif path.name == "template":
        declared = _template_conflicts(text, path)
    else:
        raise GenError(f"{path}: no way to read conflict declarations from this file")

    return {name for name in declared if name}


def check_conflicts(conflicts: dict[str, list[str]]) -> None:
    """Verify every shipped recipe's MAIN package declares the whole list.

    Only Gentoo's blockers are generated (they live inside the generated
    RDEPEND). The others sit in channel-specific shapes — `conflicts=()` inside
    a package_* function, a `Conflicts:` field, an xbps `conflicts=` line — that
    are not worth templating, but they still have to agree with the one list,
    or the divergence this check exists to catch simply comes back.

    Main package, not recipe: the shell is what claims
    org.freedesktop.Notifications, so the conflict has to be on the package a
    user installs to get the shell. An assets subpackage declaring it changes
    nothing.
    """
    missing: list[str] = []
    for channel, packages in conflicts.items():
        for relative in CONFLICT_RECIPES.get(channel, ()):
            declared = declared_conflicts(ROOT / relative)
            for package in packages:
                if package not in declared:
                    missing.append(f"{relative}: main package does not conflict with {package}")

    if missing:
        raise GenError(
            "notification daemon conflicts have drifted from "
            'packaging/optional-packages.json "conflicts":\n    '
            + "\n    ".join(missing)
        )


def check_channels(required: dict[str, list[str]]) -> None:
    """Fail unless every packaging channel this repo ships is accounted for.

    Void is why this exists. It was hand-maintained, the generator skipped it,
    and it kept `depends="quickshell jq python3"` through two rounds of
    packaging fixes — the VGS-53 defect still live on a shipped channel while
    every generated one was correct. Nothing detected that, because nothing was
    looking. A channel now has to be either generated or declared unGenerated
    with a reason; a new directory under packaging/ that is neither fails here.
    """
    declared = set(CHANNEL_RECIPES) | set(UNGENERATED_CHANNELS)
    found = {entry.name for entry in (ROOT / "packaging").iterdir() if entry.is_dir()}

    undeclared = sorted(found - declared)
    if undeclared:
        raise GenError(
            "packaging channel(s) " + ", ".join(undeclared) + " are not declared "
            "in gen-package-metadata.py. Add the recipe to CHANNEL_RECIPES so "
            "its dependencies are generated, or to UNGENERATED_CHANNELS with "
            "the reason it needs none — a channel nothing generates is a "
            "channel that ships the old dependencies forever."
        )

    for channel, relative in CHANNEL_RECIPES.items():
        if not (ROOT / relative).is_file():
            raise GenError(f"channel {channel} declares {relative}, which does not exist")
        if channel not in required:
            raise GenError(
                f'channel {channel} has a generated recipe but no "required".base '
                "entry, so its hard dependencies would be generated empty"
            )


def required_packages(mapping: dict) -> tuple[dict[str, list[str]], list[tuple[str, str, str]]]:
    """Return ({distro: [package]}, waivers) for the commands behind first-class UI.

    optdepends and Suggests are advisory: no package manager installs them by
    default. A command that a default bar button or modal points at therefore
    has to be a real dependency, or a stock install ships UI that reports
    missing tools (VGS-53).

    A required command with no package on one of the generated distributions is
    NOT quietly left out — that would ship the same broken stock install one
    distribution down. It has to be waived by name in `required.unsupported`,
    with a reason, and every run prints the waivers it honoured.
    """
    section = mapping.get("required")
    if section is None:
        raise GenError(
            'packaging/optional-packages.json has no "required" section; the '
            "hard dependencies of every recipe are generated from it"
        )
    commands = mapping["commands"]
    required = section.get("commands", [])
    unsupported = section.get("unsupported", {})
    result: dict[str, list[str]] = {}
    waivers: list[tuple[str, str, str]] = []

    for command, distros in unsupported.items():
        if command not in required:
            raise GenError(
                f'"required".unsupported names {command!r}, which is not a '
                "required command; the waiver would never be read"
            )
        unknown = set(distros) - set(REQUIRED_DISTROS)
        if unknown:
            raise GenError(
                f"unsupported waiver for {command!r} names unknown "
                "distribution(s): " + ", ".join(sorted(unknown))
            )
        for distro, reason in distros.items():
            if not reason:
                raise GenError(
                    f"unsupported waiver for {command!r} on {distro} has no "
                    "reason; a silent waiver is a silent drop with extra steps"
                )
            if commands.get(command, {}).get(distro) is not None:
                raise GenError(
                    f"{command!r} is waived as unsupported on {distro} but the "
                    "mapping names a package for it; drop the stale waiver"
                )

    for distro in REQUIRED_DISTROS:
        base = section.get("base", {}).get(distro)
        if base is None:
            raise GenError(
                f'"required".base names no packages for {distro}; the generated '
                "depends block would drop the runtime itself"
            )
        result[distro] = list(base)

    for command in required:
        entry = commands.get(command)
        if entry is None:
            raise GenError(
                f'required command {command!r} has no entry in "commands"'
            )
        if "skip" in entry:
            raise GenError(
                f"required command {command!r} is marked skip; a command cannot "
                "be both a hard dependency and already covered by one"
            )
        for distro in REQUIRED_DISTROS:
            packages = entry.get(distro)
            if packages is None:
                reason = unsupported.get(command, {}).get(distro)
                if reason is None:
                    raise GenError(
                        f"required command {command!r} names no {distro} "
                        "package. A command behind default UI cannot just be "
                        "left out of one recipe — that ships the stock install "
                        "this list exists to prevent. Add the package name, or "
                        f'waive it in "required".unsupported.{command}.{distro} '
                        "with the reason it cannot be required there."
                    )
                waivers.append((command, distro, reason))
                continue
            if isinstance(packages, str):
                packages = [packages]
            for package in packages:
                if package not in result[distro]:
                    result[distro].append(package)

    return result, waivers


def collect(
    manifest: dict, mapping: dict, required: dict[str, list[str]]
) -> dict[str, dict[str, list[str]]]:
    """Return {distro: {package: [descriptions]}} derived from the manifest."""
    features = manifest["features"]
    labels = mapping["features"]
    commands = mapping["commands"]
    required_commands = set(mapping.get("required", {}).get("commands", []))

    unlabelled = [name for name in features if name not in labels]
    if unlabelled:
        raise GenError(
            "packaging/optional-packages.json has no description for feature "
            "group(s): " + ", ".join(sorted(unlabelled))
        )

    result: dict[str, dict[str, list[str]]] = {distro: {} for distro in DISTROS}
    overrides: dict[str, dict[str, list[str]]] = {distro: {} for distro in DISTROS}

    for name, feature in features.items():
        label = labels[name]
        for command in feature_commands(feature):
            if command.startswith("${VSHELL_ROOT}"):
                continue  # shipped inside the package
            if command in required_commands:
                continue  # a hard dependency; see required_packages()
            entry = commands.get(command)
            if entry is None:
                raise GenError(
                    f"command {command!r} (feature {name!r}) has no entry in "
                    "packaging/optional-packages.json; add a package name or a "
                    "\"skip\" reason"
                )
            if "skip" in entry:
                continue
            unknown = set(entry) - {"description", "skip"} - set(REQUIRED_DISTROS)
            if unknown:
                raise GenError(
                    f"command {command!r} has unknown key(s): "
                    + ", ".join(sorted(unknown))
                )
            if not any(distro in entry for distro in DISTROS):
                raise GenError(
                    f"command {command!r} names no distribution package and no "
                    "\"skip\" reason"
                )
            for distro in DISTROS:
                packages = entry.get(distro)
                if packages is None:
                    continue
                if isinstance(packages, str):
                    packages = [packages]
                for package in packages:
                    bucket = (
                        overrides[distro] if "description" in entry else result[distro]
                    )
                    text = entry.get("description", label)
                    descriptions = bucket.setdefault(package, [])
                    if text not in descriptions:
                        descriptions.append(text)

    # A command-level description replaces the feature labels for that package:
    # "hyprland: Hyprland compositor support" beats listing five feature groups.
    for distro in DISTROS:
        for package, descriptions in overrides[distro].items():
            result[distro][package] = descriptions

    # A package that is already a hard dependency must not also be advertised as
    # optional: pacman prints such an entry as an optdep the user "may want to
    # install" for something they already have.
    for distro in DISTROS:
        for package in required[distro]:
            result[distro].pop(package, None)

    return result


def render_arch(packages: dict[str, list[str]]) -> str:
    lines = [BEGIN, NOTE, "optdepends=("]
    for package in sorted(packages):
        lines.append(f"  '{package}: {', '.join(packages[package])}'")
    lines.append(")")
    lines.append(END)
    return "\n".join(lines)


def render_arch_required(packages: list[str]) -> str:
    lines = [BEGIN_REQUIRED, NOTE, "depends=("]
    lines.extend(f"  '{package}'" for package in packages)
    lines.append(")")
    lines.append(END_REQUIRED)
    return "\n".join(lines)


def render_fedora_required(packages: list[str]) -> str:
    lines = [BEGIN_REQUIRED, NOTE]
    lines.extend(f"Requires:       {package}" for package in packages)
    lines.append(END_REQUIRED)
    return "\n".join(lines)


def render_gentoo_required(packages: list[str], blockers: list[str]) -> str:
    # The whole RDEPEND assignment is generated: a `#` inside a double-quoted
    # bash string is literal text, not a comment, so BEGIN/END markers cannot
    # live inside it the way they do in the other recipes.
    lines = [
        "# RDEPEND is generated by scripts/gen-package-metadata.py from",
        "# config/vshell/dependencies.json and packaging/optional-packages.json.",
        "# Run scripts/gen-package-metadata.py --write after changing either file.",
        'RDEPEND="',
    ]
    lines.extend(f"\t{package}" for package in packages)
    # Blockers, not dependencies: portage reads a leading ! as "must not be
    # installed". Two notification daemons cannot share the bus name.
    lines.extend(f"\t!{package}" for package in blockers)
    lines.append('"')
    return "\n".join(lines)


def render_void_required(packages: list[str]) -> str:
    lines = [BEGIN_REQUIRED, NOTE, 'depends="' + " ".join(packages) + '"', END_REQUIRED]
    return "\n".join(lines)


def render_nix_required(packages: list[str]) -> str:
    # Inside installPhase, which is a bash script, so these markers are shell
    # comments. The wrapper PATH is what makes the tools reachable from the
    # shell no matter what the user's profile holds.
    indent = " " * 14
    lines = [
        indent + BEGIN_REQUIRED,
        *(indent + line for line in NOTE.splitlines()),
        indent + "wrapProgram $out/lib/vshell/bin/vshell \\",
        indent + "  --prefix PATH : ${pkgs.lib.makeBinPath [ " + " ".join(packages) + " ]}",
        indent + END_REQUIRED,
    ]
    return "\n".join(lines)


def render_debian_required(packages: list[str]) -> str:
    # ${misc:Depends} is a debhelper substitution variable rather than a
    # package, so it is appended here instead of living in the mapping.
    names = list(packages) + ["${misc:Depends}"]
    lines = ["Depends: " + names[0] + ("," if len(names) > 1 else "")]
    for index, package in enumerate(names[1:], start=2):
        lines.append(" " + package + ("," if index < len(names) else ""))
    return "\n".join(lines)


def render_fedora(packages: dict[str, list[str]]) -> str:
    # Suggests, not Recommends: dnf installs weak Recommends by default, and
    # this list contains a login manager and both supported compositors.
    lines = [BEGIN, NOTE]
    for package in sorted(packages):
        lines.append(f"# {', '.join(packages[package])}")
        lines.append(f"Suggests:       {package}")
    lines.append(END)
    return "\n".join(lines)


def render_gentoo(packages: dict[str, list[str]]) -> str:
    lines = ["\t" + BEGIN]
    lines.extend("\t" + line for line in NOTE.splitlines())
    for package in sorted(packages):
        lines.append(f'\toptfeature "{", ".join(packages[package])}" {package}')
    lines.append("\t" + END)
    return "\n".join(lines)


def render_debian(packages: dict[str, list[str]]) -> str:
    names = sorted(packages)
    lines = ["Suggests: " + names[0] + ("," if len(names) > 1 else "")]
    for index, package in enumerate(names[1:], start=2):
        lines.append(" " + package + ("," if index < len(names) else ""))
    return "\n".join(lines)


def replace_block(
    path: Path, text: str, block: str, begin: str = BEGIN, end: str = END
) -> str:
    pattern = re.compile(
        r"^[ \t]*" + re.escape(begin) + r".*?^[ \t]*" + re.escape(end) + r"$",
        re.DOTALL | re.MULTILINE,
    )
    if not pattern.search(text):
        raise GenError(f"{path}: missing {begin} / {end} markers")
    return pattern.sub(lambda _: block, text, count=1)


def replace_gentoo_rdepend(path: Path, text: str, block: str) -> str:
    """Rewrite the RDEPEND assignment and the generator note above it."""
    pattern = re.compile(
        r"(?:^# RDEPEND is generated.*?\n(?:^#.*\n)*)?^RDEPEND=\".*?^\"$",
        re.DOTALL | re.MULTILINE,
    )
    if not pattern.search(text):
        raise GenError(f"{path}: no RDEPEND assignment to regenerate")
    return pattern.sub(lambda _: block, text, count=1)


def replace_debian_field(
    path: Path, text: str, block: str, field: str = "Suggests", stanza: str | None = None
) -> str:
    """Replace a field of one stanza, continuation lines included.

    `stanza` names the binary package whose field is meant. control has two
    Depends: fields — vgs-shell's and the assets package's, which depends on
    vgs-shell and must not be touched.
    """
    offset = 0
    if stanza is not None:
        match = re.search(rf"^Package: {re.escape(stanza)}$", text, re.MULTILINE)
        if match is None:
            raise GenError(f"{path}: no `Package: {stanza}` stanza")
        offset = match.end()
    head, tail = text[:offset], text[offset:]
    pattern = re.compile(rf"^{re.escape(field)}:.*?(?=^\S)", re.DOTALL | re.MULTILINE)
    if not pattern.search(tail):
        raise GenError(f"{path}: no {field}: field to regenerate")
    return head + pattern.sub(lambda _: block + "\n", tail, count=1)


def replace_srcinfo(path: Path, text: str, packages: dict[str, list[str]]) -> str:
    """Rewrite the optdepends lines of the pkgbase stanza of a .SRCINFO."""
    block = "".join(
        f"\toptdepends = {package}: {', '.join(packages[package])}\n"
        for package in sorted(packages)
    )
    existing = re.compile(r"(?:^\toptdepends = .*\n)+", re.MULTILINE)
    if existing.search(text):
        return existing.sub(lambda _: block, text, count=1)
    depends = list(re.finditer(r"^\tdepends = .*\n", text, re.MULTILINE))
    if not depends:
        raise GenError(f"{path}: no depends lines to anchor optdepends after")
    end = depends[-1].end()
    return text[:end] + block + text[end:]


def replace_srcinfo_depends(path: Path, text: str, packages: list[str]) -> str:
    """Rewrite the depends lines of the pkgbase stanza of a .SRCINFO.

    Scoped to pkgbase on purpose: every `pkgname =` stanza below it has its own
    depends line, and the assets subpackage's is a versioned self-reference.
    """
    split = re.search(r"^pkgname = ", text, re.MULTILINE)
    end = split.start() if split else len(text)
    head, tail = text[:end], text[end:]
    block = "".join(f"\tdepends = {package}\n" for package in packages)
    existing = re.compile(r"(?:^\tdepends = .*\n)+", re.MULTILINE)
    if not existing.search(head):
        raise GenError(f"{path}: no pkgbase depends lines to regenerate")
    return existing.sub(lambda _: block, head, count=1) + tail


def targets(
    collected: dict[str, dict[str, list[str]]],
    required: dict[str, list[str]],
    conflicts: dict[str, list[str]],
) -> list[tuple[Path, str]]:
    arch = render_arch(collected["arch"])
    arch_required = render_arch_required(required["arch"])
    out: list[tuple[Path, str]] = []

    for name in ("packaging/arch/PKGBUILD", "packaging/arch/vgs-shell-git/PKGBUILD"):
        path = ROOT / name
        text = replace_block(path, path.read_text(), arch_required, BEGIN_REQUIRED, END_REQUIRED)
        out.append((path, replace_block(path, text, arch)))

    for name in ("packaging/arch/.SRCINFO", "packaging/arch/vgs-shell-git/.SRCINFO"):
        path = ROOT / name
        text = replace_srcinfo_depends(path, path.read_text(), required["arch"])
        out.append((path, replace_srcinfo(path, text, collected["arch"])))

    path = ROOT / "packaging/debian/control"
    text = replace_debian_field(
        path,
        path.read_text(),
        render_debian_required(required["debian"]),
        field="Depends",
        stanza="vgs-shell",
    )
    out.append((path, replace_debian_field(path, text, render_debian(collected["debian"]))))

    path = ROOT / "packaging/fedora/vgs-shell.spec"
    text = replace_block(
        path,
        path.read_text(),
        render_fedora_required(required["fedora"]),
        BEGIN_REQUIRED,
        END_REQUIRED,
    )
    out.append((path, replace_block(path, text, render_fedora(collected["fedora"]))))

    path = ROOT / "packaging/gentoo/vgs-shell-0.1.0.ebuild"
    text = replace_gentoo_rdepend(
        path,
        path.read_text(),
        render_gentoo_required(required["gentoo"], conflicts["gentoo"]),
    )
    out.append((path, replace_block(path, text, render_gentoo(collected["gentoo"]))))

    # Hard dependencies only below: neither channel has a weak-dependency
    # mechanism to carry the optional list.
    path = ROOT / "packaging/void/template"
    out.append(
        (
            path,
            replace_block(
                path,
                path.read_text(),
                render_void_required(required["void"]),
                BEGIN_REQUIRED,
                END_REQUIRED,
            ),
        )
    )

    path = ROOT / "flake.nix"
    out.append(
        (
            path,
            replace_block(
                path,
                path.read_text(),
                render_nix_required(required["nix"]),
                BEGIN_REQUIRED,
                END_REQUIRED,
            ),
        )
    )

    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the recipes instead of verifying them",
    )
    args = parser.parse_args()

    try:
        manifest = json.loads(MANIFEST.read_text())
        mapping = json.loads(MAPPING.read_text())
        required, waivers = required_packages(mapping)
        conflicts, conflict_waivers = conflict_packages(mapping)
        check_channels(required)
        collected = collect(manifest, mapping, required)
        rendered = targets(collected, required, conflicts)
    except GenError as error:
        print(f"gen-package-metadata: {error}", file=sys.stderr)
        return 1

    stale = []
    for path, text in rendered:
        if path.read_text() == text:
            continue
        if args.write:
            path.write_text(text)
        else:
            stale.append(path.relative_to(ROOT))

    if stale:
        print(
            "gen-package-metadata: packaging metadata is out of date with the "
            "feature manifest:",
            file=sys.stderr,
        )
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run scripts/gen-package-metadata.py --write", file=sys.stderr)
        return 1

    # Deliberately after the write: the Gentoo blockers are generated, so this
    # has to read what this run produced rather than what was on disk before it.
    try:
        check_conflicts(conflicts)
    except GenError as error:
        print(f"gen-package-metadata: {error}", file=sys.stderr)
        return 1

    counts = ", ".join(f"{distro} {len(collected[distro])}" for distro in DISTROS)
    verb = "regenerated" if args.write else "verified"
    print(f"packaging optional dependencies {verb} ({counts})")
    print(
        f"hard dependencies {verb} for every shipped channel: "
        + ", ".join(f"{channel} {len(required[channel])}" for channel in CHANNEL_RECIPES)
    )
    print(
        "notification daemon conflicts verified: "
        + ", ".join(f"{channel} {len(conflicts[channel])}" for channel in conflicts)
    )
    for channel, reason in UNGENERATED_CHANNELS.items():
        print(f"  not generated: {channel} — {reason}")
    # Printed every run, not only when they change: each line is a recipe that
    # ships without a tool VGS considers first-class, and that should be
    # visible in the log rather than buried in a JSON file.
    for command, distro, reason in waivers:
        print(f"  waived: {distro} cannot require {command} — {reason}")
    for daemon, channel, reason in conflict_waivers:
        print(f"  waived: {channel} cannot conflict with {daemon} — {reason}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
