#!/usr/bin/env python3
"""Generate packaging optional-dependency metadata from the VGS feature manifest.

`config/vshell/dependencies.json` is the single source of truth for which
commands back which VGS feature group. `packaging/optional-packages.json` maps
those commands to distribution package names. This script joins the two and
rewrites the generated blocks in the packaging recipes so a package manager can
tell a user what is missing.

Usage:
  scripts/gen-package-metadata.py            # verify the recipes are current
  scripts/gen-package-metadata.py --write    # regenerate them
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "config" / "vshell" / "dependencies.json"
MAPPING = ROOT / "packaging" / "optional-packages.json"

DISTROS = ("arch", "debian", "fedora", "gentoo")

BEGIN = "# BEGIN GENERATED OPTIONAL DEPENDENCIES"
END = "# END GENERATED OPTIONAL DEPENDENCIES"
NOTE = (
    "# Generated by scripts/gen-package-metadata.py from\n"
    "# config/vshell/dependencies.json and packaging/optional-packages.json.\n"
    "# Run scripts/gen-package-metadata.py --write after changing either file."
)


class GenError(Exception):
    pass


def feature_commands(feature: dict) -> list[str]:
    """Every command a feature group can require, in manifest order."""
    out: list[str] = []
    for command in feature.get("commands", []):
        out.append(command)
    for alternatives in feature.get("anyCommands", []):
        out.extend(alternatives)
    for commands in feature.get("compositorCommands", {}).values():
        out.extend(commands)
    return out


def collect(manifest: dict, mapping: dict) -> dict[str, dict[str, list[str]]]:
    """Return {distro: {package: [descriptions]}} derived from the manifest."""
    features = manifest["features"]
    labels = mapping["features"]
    commands = mapping["commands"]

    unlabelled = [name for name in features if name not in labels]
    if unlabelled:
        raise GenError(
            "packaging/optional-packages.json has no description for feature "
            "group(s): " + ", ".join(sorted(unlabelled))
        )

    result: dict[str, dict[str, list[str]]] = {distro: {} for distro in DISTROS}
    overrides: dict[str, dict[str, list[str]]] = {distro: {} for distro in DISTROS}

    for name, feature in features.items():
        label = labels[name]
        for command in feature_commands(feature):
            if command.startswith("${VSHELL_ROOT}"):
                continue  # shipped inside the package
            entry = commands.get(command)
            if entry is None:
                raise GenError(
                    f"command {command!r} (feature {name!r}) has no entry in "
                    "packaging/optional-packages.json; add a package name or a "
                    "\"skip\" reason"
                )
            if "skip" in entry:
                continue
            unknown = set(entry) - {"description", "skip"} - set(DISTROS)
            if unknown:
                raise GenError(
                    f"command {command!r} has unknown key(s): "
                    + ", ".join(sorted(unknown))
                )
            if not any(distro in entry for distro in DISTROS):
                raise GenError(
                    f"command {command!r} names no distribution package and no "
                    "\"skip\" reason"
                )
            for distro in DISTROS:
                packages = entry.get(distro)
                if packages is None:
                    continue
                if isinstance(packages, str):
                    packages = [packages]
                for package in packages:
                    bucket = (
                        overrides[distro] if "description" in entry else result[distro]
                    )
                    text = entry.get("description", label)
                    descriptions = bucket.setdefault(package, [])
                    if text not in descriptions:
                        descriptions.append(text)

    # A command-level description replaces the feature labels for that package:
    # "hyprland: Hyprland compositor support" beats listing five feature groups.
    for distro in DISTROS:
        for package, descriptions in overrides[distro].items():
            result[distro][package] = descriptions

    return result


def render_arch(packages: dict[str, list[str]]) -> str:
    lines = [BEGIN, NOTE, "optdepends=("]
    for package in sorted(packages):
        lines.append(f"  '{package}: {', '.join(packages[package])}'")
    lines.append(")")
    lines.append(END)
    return "\n".join(lines)


def render_fedora(packages: dict[str, list[str]]) -> str:
    # Suggests, not Recommends: dnf installs weak Recommends by default, and
    # this list contains a login manager and both supported compositors.
    lines = [BEGIN, NOTE]
    for package in sorted(packages):
        lines.append(f"# {', '.join(packages[package])}")
        lines.append(f"Suggests:       {package}")
    lines.append(END)
    return "\n".join(lines)


def render_gentoo(packages: dict[str, list[str]]) -> str:
    lines = ["\t" + BEGIN]
    lines.extend("\t" + line for line in NOTE.splitlines())
    for package in sorted(packages):
        lines.append(f'\toptfeature "{", ".join(packages[package])}" {package}')
    lines.append("\t" + END)
    return "\n".join(lines)


def render_debian(packages: dict[str, list[str]]) -> str:
    names = sorted(packages)
    lines = ["Suggests: " + names[0] + ("," if len(names) > 1 else "")]
    for index, package in enumerate(names[1:], start=2):
        lines.append(" " + package + ("," if index < len(names) else ""))
    return "\n".join(lines)


def replace_block(path: Path, text: str, block: str) -> str:
    pattern = re.compile(
        r"^[ \t]*" + re.escape(BEGIN) + r".*?^[ \t]*" + re.escape(END) + r"$",
        re.DOTALL | re.MULTILINE,
    )
    if not pattern.search(text):
        raise GenError(f"{path}: missing {BEGIN} / {END} markers")
    return pattern.sub(lambda _: block, text, count=1)


def replace_debian_field(path: Path, text: str, block: str) -> str:
    """Replace the Suggests: field, continuation lines included."""
    pattern = re.compile(r"^Suggests:.*?(?=^\S)", re.DOTALL | re.MULTILINE)
    if not pattern.search(text):
        raise GenError(f"{path}: no Suggests: field to regenerate")
    return pattern.sub(lambda _: block + "\n", text, count=1)


def replace_srcinfo(path: Path, text: str, packages: dict[str, list[str]]) -> str:
    """Rewrite the optdepends lines of the pkgbase stanza of a .SRCINFO."""
    block = "".join(
        f"\toptdepends = {package}: {', '.join(packages[package])}\n"
        for package in sorted(packages)
    )
    existing = re.compile(r"(?:^\toptdepends = .*\n)+", re.MULTILINE)
    if existing.search(text):
        return existing.sub(lambda _: block, text, count=1)
    depends = list(re.finditer(r"^\tdepends = .*\n", text, re.MULTILINE))
    if not depends:
        raise GenError(f"{path}: no depends lines to anchor optdepends after")
    end = depends[-1].end()
    return text[:end] + block + text[end:]


def targets(collected: dict[str, dict[str, list[str]]]) -> list[tuple[Path, str]]:
    arch = render_arch(collected["arch"])
    out: list[tuple[Path, str]] = []

    for name in ("packaging/arch/PKGBUILD", "packaging/arch/vgs-shell-git/PKGBUILD"):
        path = ROOT / name
        out.append((path, replace_block(path, path.read_text(), arch)))

    for name in ("packaging/arch/.SRCINFO", "packaging/arch/vgs-shell-git/.SRCINFO"):
        path = ROOT / name
        out.append((path, replace_srcinfo(path, path.read_text(), collected["arch"])))

    path = ROOT / "packaging/debian/control"
    out.append(
        (path, replace_debian_field(path, path.read_text(), render_debian(collected["debian"])))
    )

    path = ROOT / "packaging/fedora/vgs-shell.spec"
    out.append((path, replace_block(path, path.read_text(), render_fedora(collected["fedora"]))))

    path = ROOT / "packaging/gentoo/vgs-shell-0.1.0.ebuild"
    out.append((path, replace_block(path, path.read_text(), render_gentoo(collected["gentoo"]))))

    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the recipes instead of verifying them",
    )
    args = parser.parse_args()

    try:
        manifest = json.loads(MANIFEST.read_text())
        mapping = json.loads(MAPPING.read_text())
        collected = collect(manifest, mapping)
        rendered = targets(collected)
    except GenError as error:
        print(f"gen-package-metadata: {error}", file=sys.stderr)
        return 1

    stale = []
    for path, text in rendered:
        if path.read_text() == text:
            continue
        if args.write:
            path.write_text(text)
        else:
            stale.append(path.relative_to(ROOT))

    if stale:
        print(
            "gen-package-metadata: packaging metadata is out of date with the "
            "feature manifest:",
            file=sys.stderr,
        )
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run scripts/gen-package-metadata.py --write", file=sys.stderr)
        return 1

    counts = ", ".join(f"{distro} {len(collected[distro])}" for distro in DISTROS)
    verb = "regenerated" if args.write else "verified"
    print(f"packaging optional dependencies {verb} ({counts})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
