#!/usr/bin/env bash
# Controls for scripts/qml-unit.sh and the unit tests under
# scripts/qml-tests/: a table of mutations, one per guarantee a test pins,
# each applied to a copy of shell/Ui with its match counted, and the runner
# is required to fail on every copy and to pass on the unmutated copy. Two
# rows pin the runner's arguments: a missing qmltestrunner is not a pass,
# and an unknown argument is refused. A second table plants one test file
# per rule of the runner's log check and pins the exit and the line each
# prints.
#
# Exit 0 when every row holds, 1 otherwise, 77 when qmltestrunner is absent,
# since a mutation nothing runs proves nothing.
set -euo pipefail

self="$(readlink -f -- "${BASH_SOURCE[0]}")"
repo="$(cd -- "$(dirname -- "$self")/.." && pwd)"
runner="$repo/scripts/qml-unit.sh"

if ! out="$("$runner" --tests "$repo/scripts/qml-tests" "$repo/scripts/qml-tests/tst_module.qml" 2>&1)"; then
  if [[ $out == *"status=not-measured missing=qmltestrunner"* ]]; then
    echo "test-qml-unit: status=not-measured missing=qmltestrunner"
    exit 77
  fi
  echo "test-qml-unit: the module test does not pass on the shipped tree:"
  printf '%s\n' "$out" | tail -n 20
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf -- "${tmp:?}"' EXIT
failures=0
ok() { printf '  ok    %s\n' "$*"; }
fail() { failures=$((failures + 1)); printf '  FAIL  %s\n' "$*"; }

# One fresh copy of the module under test at $1.
fresh() {
  rm -rf -- "$1"
  cp -R -- "$repo/shell/Ui" "$1"
}

# Rows: label | file under shell/Ui | text to replace | replacement | the
# test file that must go red. The replacement keeps the text around the
# behaviour and removes the behaviour. A field holds no `|`, the separator.
mutations=(
  "the orb takes pointer input|feedback/VoiceOrb.qml|    Accessible.ignored: true|    Accessible.ignored: true; MouseArea { anchors.fill: parent }|tst_voiceorb.qml"
  "the orb takes tab focus|feedback/VoiceOrb.qml|    property bool active: false|    property bool active: false; activeFocusOnTab: true|tst_voiceorb.qml"
  "the orb ignores the attack token|feedback/VoiceOrb.qml|Theme.voiceOrb.attack : Theme.voiceOrb.release|70 : Theme.voiceOrb.release|tst_voiceorb.qml"
  "the orb ignores the release token|feedback/VoiceOrb.qml|Theme.voiceOrb.attack : Theme.voiceOrb.release|Theme.voiceOrb.attack : 250|tst_voiceorb.qml"
  "the orb ticks in a minimized window|feedback/VoiceOrb.qml|&& root.Window.window.visibility !== Window.Minimized|&& true|tst_voiceorb.qml"
  "the orb ignores its size token|feedback/VoiceOrb.qml|implicitWidth: Theme.voiceOrb.size|implicitWidth: 96|tst_voiceorb.qml"
  "the orb ignores its height token|feedback/VoiceOrb.qml|implicitHeight: Theme.voiceOrb.size|implicitHeight: 96|tst_voiceorb.qml"
  "the orb ignores its tone|feedback/VoiceOrb.qml|const found = Theme.voiceOrb.tone[name];|const found = Theme.voiceOrb.tone.accent;|tst_voiceorb.qml"
  "the orb logs no unknown tone|feedback/VoiceOrb.qml|console.error('VoiceOrb: no tone named \"' + name + '\"; drawing accent');|{}|tst_voiceorb.qml"
  "the orb falls back to muted|feedback/VoiceOrb.qml|return Theme.voiceOrb.tone.accent;|return Theme.voiceOrb.tone.muted;|tst_voiceorb.qml"
  "the orb does not bound finite levels|feedback/VoiceOrb.qml|Math.max(0, Math.min(1, value))|value|tst_voiceorb.qml"
  "the orb keeps nonfinite levels|feedback/VoiceOrb.qml|Number.isFinite(value)|true|tst_voiceorb.qml"
  "the orb leaves primary levels static|feedback/VoiceOrb.qml|property real amplitude: driver.running ? state.primary : root.bounded(root.level)|property real amplitude: root.bounded(root.level)|tst_voiceorb.qml"
  "the orb leaves secondary levels static|feedback/VoiceOrb.qml|property real secondaryAmplitude: driver.running ? state.secondary : root.bounded(root.secondaryLevel)|property real secondaryAmplitude: root.bounded(root.secondaryLevel)|tst_voiceorb.qml"
  "the orb stops updating primary levels|feedback/VoiceOrb.qml|state.primary = state.smooth(state.primary, root.bounded(root.level), frameTime);|state.primary = state.primary;|tst_voiceorb.qml"
  "the orb stops updating secondary levels|feedback/VoiceOrb.qml|state.secondary = state.smooth(state.secondary, root.bounded(root.secondaryLevel), frameTime);|state.secondary = state.secondary;|tst_voiceorb.qml"
  "the orb ticks at reduced motion|feedback/VoiceOrb.qml|Theme.motion.scale > 0 && Theme.voiceOrb.period > 0|true|tst_voiceorb.qml"
  "the orb ignores a zero period|feedback/VoiceOrb.qml|&& Theme.voiceOrb.period > 0|&& true|tst_voiceorb.qml"
  "the orb ticks when hidden or its parent is hidden|feedback/VoiceOrb.qml|root.visible && root.active|root.active|tst_voiceorb.qml"
  "the orb ticks when inactive|feedback/VoiceOrb.qml|root.visible && root.active|root.visible|tst_voiceorb.qml"
  "the orb ticks in a hidden window|feedback/VoiceOrb.qml|&& root.Window.window.visible|&& true|tst_voiceorb.qml"
  "the orb phase never advances|feedback/VoiceOrb.qml|state.phase = (state.phase + frameTime * 1000 * 2 * Math.PI / Theme.voiceOrb.period) % (2 * Math.PI);|state.phase = state.phase;|tst_voiceorb.qml"
  "the orb drops the line tokens|feedback/VoiceOrb.qml|Qt.vector4d(Theme.voiceOrb.radius, Theme.voiceOrb.gap, Theme.voiceOrb.stroke, Theme.voiceOrb.arcStroke)|Qt.vector4d(0.28, 0.045, 1.5, 0.75)|tst_voiceorb.qml"
  "the orb drops the wave tokens|feedback/VoiceOrb.qml|Qt.vector4d(Theme.voiceOrb.amplitude, Theme.voiceOrb.waveCount, Theme.voiceOrb.arcSpan, Theme.voiceOrb.arcOpacity)|Qt.vector4d(0.018, 3, 2.4, 0.6)|tst_voiceorb.qml"
  "the orb is exposed as an accessible control|feedback/VoiceOrb.qml|Accessible.ignored: true|Accessible.ignored: false|tst_voiceorb.qml"
  "the orb loads no compiled shader|feedback/VoiceOrb.qml|fragmentShader: Qt.resolvedUrl(\"shaders/voiceorb.frag.qsb\")|fragmentShader: \"\"|tst_voiceorb.qml"
  "the label's role is not read|foundation/Label.qml|const found = Theme.text[name];|const found = undefined;|tst_label.qml"
  "the label's weight does not reach the axis|foundation/Label.qml|font.variableAxes: ({ wght: typography.weight })|font.variableAxes: ({ wght: 400 })|tst_label.qml"
  "the bar role draws at the body metrics|../Commons/Tokens.js|bar: role(\"mono\", 0.8, 500, 0.08, 1, true, \"text\")|bar: role(\"sans\", 1, 400, 0, 1.55, false, \"text\")|tst_label.qml"
  "body text draws in the mono family|../Commons/Tokens.js|body: role(\"sans\", 1, 400, 0, 1.6, false, \"text\")|body: role(\"mono\", 1, 400, 0, 1.6, false, \"text\")|tst_label.qml"
  "a wrapping role leaves the 4 px grid|../Commons/Tokens.js|hint: role(\"sans\", 0.87, 400, 0, 1.55, false, \"textFaint\")|hint: role(\"sans\", 0.87, 400, 0, 1.7, false, \"textFaint\")|tst_label.qml"
  "an absent family draws the mono family whatever its token|../Commons/Theme.qml|convertLeaf(level[key], node[key], fallback[key], loaded, families, missing)|convertLeaf(level[key], node[key], loaded[0], loaded, families, missing)|tst_label.qml"
  "the label's letter spacing is not scaled|foundation/Label.qml|font.letterSpacing: typography.letterSpacing * typography.size|font.letterSpacing: typography.letterSpacing|tst_label.qml"
  "the label drops its fixed-height branch|foundation/Label.qml|lineHeightMode: lineBox > fontHeight ? Text.FixedHeight : Text.ProportionalHeight|lineHeightMode: Text.ProportionalHeight|tst_label.qml"
  "the label line box is not whole-pixel floored|foundation/Label.qml|readonly property real lineBox: Math.max(Math.round(typography.size * typography.lineHeight), Math.ceil(fontHeight))|readonly property real lineBox: Math.max(Math.round(typography.size * typography.lineHeight), fontHeight)|tst_label.qml"
  "the icon's stroke scales with its size|foundation/Icon.qml|strokeWidth: root.stroke / root.factor|strokeWidth: root.stroke|tst_icon.qml"
  "the icon's path is not scaled|foundation/Icon.qml|transform: Scale { xScale: root.factor; yScale: root.factor }|transform: Scale { xScale: 1; yScale: 1 }|tst_icon.qml"
  "the icon keeps an unknown name's paths|foundation/Icon.qml|return [\"\", \"\"];|return Lucide.ICONS.circle;|tst_icon.qml"
  "the focus ring ignores a text input's focus|foundation/FocusRing.qml|visible: target.visualFocus === undefined ? target.activeFocus : target.visualFocus|visible: target.visualFocus === true|tst_textfield.qml"
  "the progress fill stays displaced|feedback/ProgressBar.qml|onStopped: fill.x = Qt.binding(() => root.mirrored && !root.indeterminate ? fill.parent.width - fill.width : 0)|onStopped: {}|tst_feedback.qml"
  "the popover does not count as open|overlay/Popover.qml|onVisibleChanged: root.share(visible)|onVisibleChanged: {}|tst_overlays.qml"
  "a hidden anchor leaves its popup open|overlay/AnchorTracker.qml|function onVisibleChanged() { if (!target.visible) tracker.popup.visible = false; }|function onVisibleChanged() {}|tst_overlays.qml"
  "a moved anchor leaves its popup behind|overlay/AnchorTracker.qml|if (popup.visible) popup.anchor.updateAnchor();|return;|tst_overlays.qml"
  "the tooltip opens under an open overlay|overlay/Tooltip.qml|if (root.resting && OverlayState.open === 0) window.visible = true|if (root.resting) window.visible = true|tst_overlays.qml"
  "the tooltip opens again over what a press opened|overlay/Tooltip.qml|onPressedChanged: if (pressed) root.pressedHere = true|onPressedChanged: {}|tst_overlays.qml"
  "the menu stays open after a trigger|overlay/Menu.qml|function onTriggered() { root.close(); }|function onTriggered() {}|tst_overlays.qml"
  "the menu keys move no highlight|overlay/Menu.qml|item.highlighted = index === currentIndex;|item.highlighted = false;|tst_overlays.qml"
  "the menu window stays at the minimum width|overlay/Menu.qml|Math.max(Theme.menu.minWidth, root.widest + 2 * Theme.menu.padding))|Math.max(Theme.menu.minWidth, 0))|tst_overlays.qml"
  "the menu grows past its maximum height|overlay/Menu.qml|Math.min(column.implicitHeight, root.maxHeight)|column.implicitHeight|tst_overlays.qml"
  "the highlight scrolls out of view|overlay/Menu.qml|else if (item.y + item.height > scroll.contentY + scroll.height) scroll.contentY = item.y + item.height - scroll.height;|else {}|tst_overlays.qml"
  "the menu opens on no entry whatever is checked|overlay/Menu.qml|currentIndex = items().findIndex(item => reachable(item) && item.checked);|currentIndex = -1;|tst_overlays.qml"
  "the menu opens where it was scrolled|overlay/Menu.qml|scroll.contentY = 0;|scroll.contentY = scroll.contentY;|tst_overlays.qml"
  "typing jumps to an entry that holds the letters|overlay/Menu.qml|String(item.text).toLowerCase().indexOf(prefix) === 0|String(item.text).toLowerCase().indexOf(prefix) !== -1|tst_overlays.qml"
  "typing keeps no letters|overlay/Menu.qml|let wanted = typed + letter.toLowerCase();|let wanted = letter.toLowerCase();|tst_overlays.qml"
  "a letter no prefix continues jumps nowhere|overlay/Menu.qml|            found = find(wanted);|            found = -1;|tst_overlays.qml"
  "the typed letters are never cleared|overlay/Menu.qml|onTriggered: root.typed = \"\"|onTriggered: {}|tst_overlays.qml"
  "the checked entry draws no mark|overlay/MenuItem.qml|visible: root.checked|visible: false|tst_overlays.qml"
  "the check mark takes no room|overlay/MenuItem.qml|rightPadding: sidePadding + (checked ? Theme.icon.size.sm + spacing : 0)|rightPadding: sidePadding|tst_overlays.qml"
  "the scroll area leaves no gutter|layout/ScrollArea.qml|contentWidth: width - rightInset|contentWidth: width|tst_scroll.qml"
  "the scroll area's gutter comes and goes with the overflow|layout/ScrollArea.qml|contentWidth: width - rightInset|contentWidth: overflowing ? width - rightInset : width|tst_scroll.qml"
  "the scroll area ignores its right inset|layout/ScrollArea.qml|property real rightInset: Theme.scrollArea.gutter|property real rightInset: 0|tst_scroll.qml"
  "the scroll area reads its content item through childrenRect|layout/ScrollArea.qml|contentHeight: measuredContentHeight|contentHeight: contentItem.childrenRect.height|tst_scroll.qml"
  "the scroll area drops content height while its ancestor is hidden|layout/ScrollArea.qml|if (!child.visible && root.visible) continue;|if (!child.visible) continue;|tst_scroll.qml"
  "the bar shows without an overflow|layout/ScrollBar.qml|    visible: needed|    visible: true|tst_scroll.qml"
  "the thumb shrinks below its minimum|layout/ScrollBar.qml|Math.max(Theme.scrollArea.minThumb, height * flickable.height / flickable.contentHeight)|height * flickable.height / flickable.contentHeight|tst_scroll.qml"
  "the thumb is not the view's share|layout/ScrollBar.qml|Math.max(Theme.scrollArea.minThumb, height * flickable.height / flickable.contentHeight)|Theme.scrollArea.minThumb|tst_scroll.qml"
  "dragging the thumb scrolls nothing|layout/ScrollBar.qml|if (pressed) root.dragTo(mapToItem(root, 0, mouse.y).y - grab);|if (pressed) {}|tst_scroll.qml"
  "the dragged thumb jumps to the pointer|layout/ScrollBar.qml|root.dragTo(mapToItem(root, 0, mouse.y).y - grab)|root.dragTo(mapToItem(root, 0, mouse.y).y)|tst_scroll.qml"
  "a press on the track pages nothing|layout/ScrollBar.qml|onPressed: mouse => root.page(mouse.y < thumbItem.y ? -1 : 1)|onPressed: mouse => {}|tst_scroll.qml"
  "a press on the track always pages down|layout/ScrollBar.qml|onPressed: mouse => root.page(mouse.y < thumbItem.y ? -1 : 1)|onPressed: mouse => root.page(1)|tst_scroll.qml"
  "the idle bar never fades|layout/ScrollBar.qml|opacity: active ? 1 : Theme.scrollArea.idleOpacity|opacity: 1|tst_scroll.qml"
  "scrolling does not show the bar|layout/ScrollBar.qml|function onContentYChanged() { recent.restart(); }|function onContentYChanged() {}|tst_scroll.qml"
  "hovering does not show the bar|layout/ScrollBar.qml|readonly property bool active: hovered|readonly property bool active: false|tst_scroll.qml"
  "the pane lays the scroll area outside the content edge|layout/Pane.qml|width: Math.max(0, root.width - root.contentInset + root.ringRoom)|width: root.contentWidth + root.ringRoom|tst_pane.qml"
  "the pane ignores the container radius|layout/Pane.qml|radius: root.baseRadius|radius: 0|tst_pane.qml"
  "the pane ignores the dialog component padding|layout/Pane.qml|case \"dialog\": return Theme.dialog.padding;|case \"dialog\": return Theme.inset.dialog;|tst_pane.qml"
  "the pane drops the gap between a header and footer without a body|layout/Pane.qml|readonly property real headerGap: headerHeight > 0 && contentBelowHeader ? gap : 0|readonly property real headerGap: headerHeight > 0 && bodyContentHeight > 0 ? gap : 0|tst_pane.qml"
  "the pane does not cap fitted content|layout/Pane.qml|readonly property real cappedHeight: maximumHeight > 0 ? Math.min(uncappedHeight, maximumHeight) : uncappedHeight|readonly property real cappedHeight: uncappedHeight|tst_pane.qml"
  "the pane's footer sits on the body|layout/Pane.qml|y: scroll.y + scroll.height - root.ringRoom + root.footerGap|y: scroll.y + scroll.height - root.ringRoom|tst_pane.qml"
  "the select list leaves no gutter|controls/Select.qml|width: ListView.view.width - Theme.menu.padding|width: ListView.view.width|tst_scroll.qml"
  "a click leaves the title's menu closed|controls/TitleButton.qml|onClicked: toggleMenu()|onClicked: {}|tst_titlebutton.qml"
  "down leaves the title's menu closed|controls/TitleButton.qml|Keys.onDownPressed: toggleMenu()|Keys.onDownPressed: {}|tst_titlebutton.qml"
  "the title ignores hover|controls/TitleButton.qml|readonly property color foreground: hovered|readonly property color foreground: false && hovered|tst_titlebutton.qml"
  "the underline sits on the text|controls/TitleButton.qml|y: label.height + Theme.titleButton.underlineGap|y: label.height|tst_titlebutton.qml"
  "the caret touches the text|controls/TitleButton.qml|x: label.width + root.spacing|x: label.width|tst_titlebutton.qml"
  "a narrow title overflows its button|controls/TitleButton.qml|width: Math.min(implicitWidth, parent.width - root.spacing - caret.width)|width: implicitWidth|tst_titlebutton.qml"
  "the select accepts an index past its end|controls/Select.qml|index >= count) return;|index >= count + 100) return;|tst_overlays.qml"
  "the select ignores its text role|controls/Select.qml|return String(entry[textRole]);|return String(entry);|tst_overlays.qml"
  "the select breaks its index binding on the current choice|controls/Select.qml|if (index !== currentIndex) currentIndex = index;|currentIndex = index;|tst_overlays.qml"
  "the select emits no user choice|controls/Select.qml|        activated(index);|        if (false) activated(index);|tst_overlays.qml"
  "the select activates on a model refresh|controls/Select.qml|signal activated(int index)|signal activated(int index); onModelChanged: activated(currentIndex)|tst_overlays.qml"
  "the toast ignores its tone|feedback/Toast.qml|const found = Theme.badge.tone[name];|const found = undefined;|tst_overlays.qml"
  "Return answers no dialog|feedback/Dialog.qml|Keys.onReturnPressed: pressFocused()|Keys.onReturnPressed: {}|tst_dialog.qml"
  "Enter answers no dialog|feedback/Dialog.qml|Keys.onEnterPressed: pressFocused()|Keys.onEnterPressed: {}|tst_dialog.qml"
  "Escape leaves the dialog unanswered|feedback/Dialog.qml|Keys.onEscapePressed: if (!busy) rejected()|Keys.onEscapePressed: {}|tst_dialog.qml"
  "Escape answers a busy dialog|feedback/Dialog.qml|Keys.onEscapePressed: if (!busy) rejected()|Keys.onEscapePressed: rejected()|tst_dialog.qml"
  "the dialog's focus stays on the action last clicked|feedback/Dialog.qml|onActiveFocusChanged: if (activeFocus) focusAccept()|onActiveFocusChanged: {}|tst_dialog.qml"
  "the dialog's first action takes the focus|feedback/Dialog.qml|const button = buttons()[acceptIndex];|const button = buttons()[0];|tst_dialog.qml"
  "Enter presses the accept action whatever holds the focus|feedback/Dialog.qml|trigger(focused !== -1 ? focused : acceptIndex);|trigger(acceptIndex);|tst_dialog.qml"
  "Tab stops at the dialog's last action|feedback/Dialog.qml|reach[(at + step + reach.length) % reach.length]|reach[Math.max(0, Math.min(at + step, reach.length - 1))]|tst_dialog.qml"
  "Tab leaves the dialog from an action|feedback/Dialog.qml|Keys.onTabPressed: root.cycle(1)|Keys.onTabPressed: event => { event.accepted = false; }|tst_dialog.qml"
  "Tab leaves the dialog from the dialog itself|feedback/Dialog.qml|Keys.onTabPressed: cycle(1)|Keys.onTabPressed: event => { event.accepted = false; }|tst_dialog.qml"
  "Tab stops on a disabled action|feedback/Dialog.qml|buttons().filter(button => button.enabled)|buttons()|tst_dialog.qml"
  "Tab focus draws no ring in the dialog|feedback/Dialog.qml|next.forceActiveFocus(step > 0 ? Qt.TabFocusReason : Qt.BacktabFocusReason)|next.forceActiveFocus()|tst_dialog.qml"
  "a pressed dialog action answers nothing|feedback/Dialog.qml|onClicked: root.trigger(index)|onClicked: {}|tst_dialog.qml"
  "a cancel action draws the accept variant|feedback/Dialog.qml|role === \"accept\" ? \"primary\" : \"tertiary\"|\"primary\"|tst_dialog.qml"
  "an unknown action role accepts|feedback/Dialog.qml|role = \"cancel\";|role = \"accept\";|tst_dialog.qml"
  "a busy dialog's actions stay enabled|feedback/Dialog.qml|enabled: modelData.enabled && !root.busy|enabled: modelData.enabled|tst_dialog.qml"
  "a busy dialog answers|feedback/Dialog.qml|const answers = !busy && entry|const answers = entry|tst_dialog.qml"
  "a disabled dialog action answers|feedback/Dialog.qml|entry !== undefined && entry.enabled;|entry !== undefined;|tst_dialog.qml"
  "a busy dialog shows no spinner|feedback/Dialog.qml|visible: root.busy|visible: false|tst_dialog.qml"
  "the dialog's title ignores its role token|feedback/Dialog.qml|role: Theme.dialog.titleRole|role: \"h3\"|tst_dialog.qml"
  "the dialog's message ignores its role token|feedback/Dialog.qml|role: Theme.dialog.bodyRole|role: \"body\"|tst_dialog.qml"
  "the dialog's card ignores its background token|feedback/Dialog.qml|color: Theme.dialog.background|color: Theme.color.surface|tst_dialog.qml"
  "the dialog's content is hidden|feedback/Dialog.qml|visible: children.length > 0|visible: false|tst_dialog.qml"
  "a dialog ignores its maximum height|feedback/Dialog.qml|implicitHeight: pane.implicitHeight|implicitHeight: pane.uncappedHeight|tst_dialog.qml"
  "a dialog without an available height ignores its screen|feedback/Dialog.qml|const height = availableHeight > 0 ? availableHeight : root.screenHeight();|const height = availableHeight;|tst_dialog.qml"
  "the card leans by a fixed skew|layout/AngledCard.qml|property real skew: Theme.angledCard.skew|property real skew: 28|tst_angledcard.qml"
  "the card's top edge does not lean|layout/AngledCard.qml|Qt.point(Math.max(skew, 0), 0),|Qt.point(0, 0),|tst_angledcard.qml"
  "a negative skew leans the card as a positive one|layout/AngledCard.qml|Qt.point(-Math.min(skew, 0), height)|Qt.point(0, height)|tst_angledcard.qml"
  "the card's outline is left open|layout/AngledCard.qml|readonly property var outline: corners.concat([corners[0]])|readonly property var outline: corners|tst_angledcard.qml"
  "the card's content is not masked|layout/AngledCard.qml|maskEnabled: true|maskEnabled: false|tst_angledcard.qml"
  "the card's mask has no coverage|layout/AngledCard.qml|strokeColor: \"transparent\"|strokeColor: \"transparent\"; fillColor: \"transparent\"|tst_angledcard.qml"
  "a selected card is washed|layout/AngledCard.qml|property bool dimmed: !selected|property bool dimmed: true|tst_angledcard.qml"
  "the card's wash ignores dimmed|layout/AngledCard.qml|visible: root.dimmed|visible: !root.selected|tst_angledcard.qml"
  "the card's wash ignores its token|layout/AngledCard.qml|color: Theme.angledCard.dim|color: Theme.color.scrim|tst_angledcard.qml"
  "a selected card draws the plain outline width|layout/AngledCard.qml|strokeWidth: root.selected ? Theme.angledCard.selectedBorderWidth : Theme.angledCard.borderWidth|strokeWidth: Theme.angledCard.borderWidth|tst_angledcard.qml"
  "a selected card draws the plain outline colour|layout/AngledCard.qml|strokeColor: root.selected ? Theme.angledCard.selectedBorder : Theme.angledCard.border|strokeColor: Theme.angledCard.border|tst_angledcard.qml"
  "the card's wash is not Omarchy's 0.42|../Commons/Tokens.js|dim: color(\"alpha({palette.background}, 0.42)\")|dim: color(\"alpha({palette.background}, 0.5)\")|tst_angledcard.qml"
  "the selected outline is not Omarchy's 3 pixels|../Commons/Tokens.js|selectedBorderWidth: length(3)|selectedBorderWidth: length(\"{border.thick}\")|tst_angledcard.qml"
  "the card's outline is not a hairline|../Commons/Tokens.js|borderWidth: length(\"{border.thin}\")|borderWidth: length(\"{border.thick}\")|tst_angledcard.qml"
  "the carousel's unit ignores its height|layout/CardCarousel.qml|Math.min(tokens.maxScale, root.width / reference, root.height / tokens.expandedHeight)|Math.min(tokens.maxScale, root.width / reference)|tst_carousel.qml"
  "the carousel's unit ignores its width|layout/CardCarousel.qml|Math.min(tokens.maxScale, root.width / reference, root.height / tokens.expandedHeight)|Math.min(tokens.maxScale, root.height / tokens.expandedHeight)|tst_carousel.qml"
  "the carousel's unit falls below its minimum|layout/CardCarousel.qml|Math.max(tokens.minScale, |Math.max(0, |tst_carousel.qml"
  "the carousel's unit rises past its maximum|layout/CardCarousel.qml|Math.min(tokens.maxScale, |Math.min(Infinity, |tst_carousel.qml"
  "the reference rail leaves no margin|layout/CardCarousel.qml| + 2 * tokens.referenceMargin||tst_carousel.qml"
  "the reference rail is not Omarchy's thirteen steps|../Commons/Tokens.js|referenceSteps: number(13, 0, 64)|referenceSteps: number(12, 0, 64)|tst_carousel.qml"
  "the rail is not centred down the carousel|layout/CardCarousel.qml|readonly property real top: (root.height - expandedHeight) / 2|readonly property real top: 0|tst_carousel.qml"
  "the slices are not centred on the expanded card|layout/CardCarousel.qml|sliceTop: top + (expandedHeight - sliceHeight) / 2|sliceTop: top|tst_carousel.qml"
  "the right slices do not overlap the expanded card|layout/CardCarousel.qml|left + expandedWidth - overlap + (offset - 1) * pitch|left + expandedWidth + (offset - 1) * pitch|tst_carousel.qml"
  "the left slices step by their width|layout/CardCarousel.qml|left + offset * pitch|left + offset * sliceWidth|tst_carousel.qml"
  "the overlap does not shorten the slice step|layout/CardCarousel.qml|Math.max(sliceWidth - overlap, 1)|Math.max(sliceWidth, 1)|tst_carousel.qml"
  "a slice that does not fit whole is shown|layout/CardCarousel.qml|Math.floor(left / pitch)|Math.ceil(left / pitch)|tst_carousel.qml"
  "no card past the shown slices is built|layout/CardCarousel.qml|slicesPerSide + tokens.band|slicesPerSide|tst_carousel.qml"
  "every card of the model is built|layout/CardCarousel.qml|active: slot.retained|active: true|tst_carousel.qml"
  "a built card past the shown slices is drawn|layout/CardCarousel.qml|visible: shown|visible: retained|tst_carousel.qml"
  "the card's lean does not scale with the rail|layout/CardCarousel.qml|Theme.angledCard.skew * unit|Theme.angledCard.skew|tst_carousel.qml"
  "the current card is not selected|layout/CardCarousel.qml|selected: slot.offset === 0|selected: false|tst_carousel.qml"
  "the card nearer the current one is not on top|layout/CardCarousel.qml|z: -Math.abs(offset)|z: 0|tst_carousel.qml"
  "a slice decodes in pixels, not device pixels|layout/CardCarousel.qml|Qt.size(Math.round(sliceWidth * root.devicePixelRatio), Math.round(sliceHeight * root.devicePixelRatio))|Qt.size(Math.round(sliceWidth), Math.round(sliceHeight))|tst_carousel.qml"
  "the full decode has no cap|layout/CardCarousel.qml|Math.min(1, tokens.decodeCap / (Math.max(expandedWidth, expandedHeight) * root.devicePixelRatio))|1|tst_carousel.qml"
  "the neighbours decode at the slice size|layout/CardCarousel.qml|Math.abs(offset) <= 1 ? internal.fullDecode|offset === 0 ? internal.fullDecode|tst_carousel.qml"
  "a card's decode size stays as it was built|layout/CardCarousel.qml|content.decodeSize = Qt.binding(() => slot.decodeSize);||tst_carousel.qml"
  "a card's model data is not rebound to its slot|layout/CardCarousel.qml|content.modelData = Qt.binding(() => slot.modelData);||tst_carousel.qml"
  "the carousel does not tell a delegate it is current|layout/CardCarousel.qml|content.current = Qt.binding(() => slot.offset === 0);|content.current = false;|tst_carousel.qml"
  "a click on a slice selects nothing|layout/CardCarousel.qml|else root.currentIndex = slot.index;|else {}|tst_carousel.qml"
  "a click on the current card activates nothing|layout/CardCarousel.qml|if (slot.offset === 0) root.activated(slot.index);|if (slot.offset === 0) {}|tst_carousel.qml"
  "a click lands on a card's bounding box|layout/CardCarousel.qml|return internal.inside(card, point);|return true;|tst_carousel.qml"
  "Left steps forward|layout/CardCarousel.qml|case Qt.Key_Left:|case Qt.Key_unknown:|tst_carousel.qml"
  "Backtab steps nowhere|layout/CardCarousel.qml|case Qt.Key_Backtab:|case Qt.Key_unknown:|tst_carousel.qml"
  "Right steps back|layout/CardCarousel.qml|step(1);|step(-1);|tst_carousel.qml"
  "Shift+Tab steps forward|layout/CardCarousel.qml|step(event.modifiers & Qt.ShiftModifier ? -1 : 1);|step(1);|tst_carousel.qml"
  "Home stays on the current card|layout/CardCarousel.qml|step(-currentIndex);|step(0);|tst_carousel.qml"
  "End stays on the current card|layout/CardCarousel.qml|step(cards.count - 1 - currentIndex);|step(0);|tst_carousel.qml"
  "a step stops at the ends|layout/CardCarousel.qml|((currentIndex + delta) % count + count) % count|Math.max(0, Math.min(count - 1, currentIndex + delta))|tst_carousel.qml"
  "a part-notch steps|layout/CardCarousel.qml|Math.trunc(internal.wheel / internal.notch)|Math.sign(internal.wheel)|tst_carousel.qml"
  "a part-notch is dropped|layout/CardCarousel.qml|internal.wheel -= notches * internal.notch;|internal.wheel = 0;|tst_carousel.qml"
  "the wheel steps the other way|layout/CardCarousel.qml|root.step(-notches);|root.step(notches);|tst_carousel.qml"
  "a sideways wheel steps nothing|layout/CardCarousel.qml|wheel.angleDelta.y !== 0 ? wheel.angleDelta.y : wheel.angleDelta.x|wheel.angleDelta.y|tst_carousel.qml"
  "a hidden carousel keeps a part-notch|layout/CardCarousel.qml|            wheel = 0;|            wheel = wheel;|tst_carousel.qml"
  "the rail shows before it settles|layout/CardCarousel.qml|visible: internal.settled|visible: true|tst_carousel.qml"
  "a carousel shown again stays settled|layout/CardCarousel.qml|            settled = false;|            settled = settled;|tst_carousel.qml"
  "a seeded index glides before the rail settles|layout/CardCarousel.qml|const glides = settled && |const glides = |tst_carousel.qml"
  "a move past the shown slices glides|layout/CardCarousel.qml| && Math.abs(target - position) <= slicesPerSide;|;|tst_carousel.qml"
  "a move within the shown slices lands at once|layout/CardCarousel.qml|glide.start();|position = target;|tst_carousel.qml"
  "a change of the current index moves nothing|layout/CardCarousel.qml|onCurrentIndexChanged: internal.follow()|onCurrentIndexChanged: {}|tst_carousel.qml"
  "a card the glide leaves is hidden at once|layout/CardCarousel.qml|Math.min(Math.abs(offset), Math.abs(index - internal.position))|Math.abs(offset)|tst_carousel.qml"
  "a card between two places is hidden|layout/CardCarousel.qml|distance < internal.slicesPerSide + 1|distance <= internal.slicesPerSide|tst_carousel.qml"
  "a card between two places is released|layout/CardCarousel.qml|distance < internal.reach + 1|distance <= internal.reach|tst_carousel.qml"
  "the rail draws past the carousel|layout/CardCarousel.qml|clip: true|clip: false|tst_carousel.qml"
  "a delegate without decodeSize is kept|layout/CardCarousel.qml|const built = content !== null && \"decodeSize\" in content;|const built = content !== null;|tst_carousel.qml"
  "a delegate that built nothing is used|layout/CardCarousel.qml|const built = content !== null && \"decodeSize\" in content;|const built = \"decodeSize\" in content;|tst_carousel.qml"
  "a refused content stays in its card|layout/CardCarousel.qml|if (content !== null) content.destroy();||tst_carousel.qml"
  "a card left empty is not named|layout/CardCarousel.qml|console.warn(\"CardCarousel: no content index=\"|void(\"CardCarousel: no content index=\"|tst_carousel.qml"
  "the rail moves over another duration|layout/CardCarousel.qml|duration: Theme.carousel.duration|duration: Theme.motion.duration.normal|tst_carousel.qml"
  "the cards jump to the current index|layout/CardCarousel.qml|internal.place(index - internal.position)|internal.place(offset)|tst_carousel.qml"
  "the cards jump between whole places|layout/CardCarousel.qml|const t = offset - whole;|const t = 0;|tst_carousel.qml"
  "the scrim does not fill its parent|foundation/Scrim.qml|anchors.fill: parent|anchors.centerIn: parent|tst_scrim.qml"
  "the scrim draws another colour|foundation/Scrim.qml|color: Theme.color.scrim|color: Theme.color.background|tst_scrim.qml"
  "a click on the scrim is not reported|foundation/Scrim.qml|onClicked: root.clicked()|onClicked: {}|tst_scrim.qml"
  "hover over the scrim reaches the control under it|foundation/Scrim.qml|hoverEnabled: true|hoverEnabled: false|tst_scrim.qml"
  "the wheel over the scrim scrolls the area under it|foundation/Scrim.qml|onWheel: wheel => { wheel.accepted = true; }|onWheel: wheel => { wheel.accepted = false; }|tst_scrim.qml"
  "a destroyed overlay keeps its count|overlay/Popover.qml|Component.onDestruction: share(false)|Component.onDestruction: {}|tst_overlays.qml"
  "the menu keys reach a disabled entry|overlay/Menu.qml|function reachable(item) { return item.enabled && item.visible; }|function reachable(item) { return true; }|tst_overlays.qml"
  "the menu triggers a disabled entry|overlay/Menu.qml|if (currentIndex >= 0 && currentIndex < all.length && reachable(all[currentIndex])) all[currentIndex].triggered();|if (currentIndex >= 0 && currentIndex < all.length) all[currentIndex].triggered();|tst_overlays.qml"
  "the menu starts upward at the penultimate entry|overlay/Menu.qml|if (at === -1) keyTo(step > 0 ? reach[0] : reach[reach.length - 1]);|if (at === -1) keyTo(reach[(step + reach.length) % reach.length]);|tst_overlays.qml"
  "a shown tooltip stays under a new overlay|overlay/Tooltip.qml|function onOpenChanged() { if (OverlayState.open > 0) window.visible = false; }|function onOpenChanged() {}|tst_overlays.qml"
  "enter leaves the select closed|controls/Select.qml|Keys.onReturnPressed: openList()|Keys.onReturnPressed: {}|tst_overlays.qml"
  "the list row prefers no width of its own|layout/ListItem.qml|leftPadding + rightPadding + (iconName !== \"\" ? Theme.icon.size.md + Theme.listItem.iconGap : 0) + Math.max(title.implicitWidth, secondaryLabel.implicitWidth)|leftPadding + rightPadding + (iconName !== \"\" ? Theme.icon.size.md + Theme.listItem.iconGap : 0) + 0|tst_layout.qml"
  "the list row's secondary line keeps paragraph leading|layout/ListItem.qml|role: \"itemHint\"|role: \"hint\"|tst_layout.qml"
  "a two-line list row stands at the one-line height|layout/ListItem.qml|implicitHeight: Math.max(secondary !== \"\" ? Theme.listItem.twoLineHeight : Theme.listItem.height,|implicitHeight: Math.max(Theme.listItem.height,|tst_layout.qml"
  "the list row's title keeps paragraph leading|layout/ListItem.qml|role: \"item\"|role: \"body\"|tst_layout.qml"
  "the icon button's icon sits at the top|controls/IconButton.qml|topPadding: leftPadding|topPadding: 0|tst_button.qml"
  "the icon button rests opaque|controls/IconButton.qml|? Theme.iconButton.restOpacity : 1|? 1 : 1|tst_button.qml"
  "the icon button ignores focus opacity|controls/IconButton.qml|root.visualFocus|false|tst_button.qml"
  "the icon button ignores pressed opacity|controls/IconButton.qml|root.down|false|tst_button.qml"
  "the icon button ignores checked opacity|controls/IconButton.qml|root.checked|false|tst_button.qml"
  "the icon button ignores hover opacity|controls/IconButton.qml|root.hovered|false|tst_button.qml"
  "the disabled icon button fades its icon twice|controls/IconButton.qml|? Theme.iconButton.restOpacity : 1|? Theme.iconButton.restOpacity : Theme.iconButton.restOpacity|tst_button.qml"
  "the button ignores hover|controls/Button.qml|hovered ? tokens.hover :|false ? tokens.hover :|tst_button.qml"
  "the button ignores press|controls/Button.qml|down ? tokens.pressed :|false ? tokens.pressed :|tst_button.qml"
  "the button ignores checked|controls/Button.qml|readonly property color fill: checked ?|readonly property color fill: false ?|tst_button.qml"
  "the button's text does not follow its fill|../Commons/Tokens.js|foreground: color(\"contrast({\" + path + \".background})\")|foreground: color(\"{color.text}\")|tst_button.qml"
  "the disabled button does not fade|controls/Button.qml|opacity: enabled ? 1 : Theme.opacity.disabled|opacity: 1|tst_button.qml"
  "the focus ring ignores focus|foundation/FocusRing.qml|visible: target.visualFocus === undefined ? target.activeFocus : target.visualFocus|visible: false|tst_button.qml"
  "the icon button is not square|controls/IconButton.qml|implicitWidth: controlHeight|implicitWidth: controlHeight * 2|tst_button.qml"
  "the switch knob does not slide|controls/Switch.qml|x: inset + root.visualPosition * (parent.width - width - 2 * inset)|x: inset|tst_toggles.qml"
  "the switch ignores its size|controls/Switch.qml|const found = Theme.toggle.size[name];|const found = Theme.toggle.size.md;|tst_toggles.qml"
  "the toggle width counts the gap twice|controls/Checkbox.qml|implicitWidth: text !== \"\" ? implicitContentWidth : implicitIndicatorWidth|implicitWidth: implicitIndicatorWidth + spacing + implicitContentWidth|tst_toggles.qml"
  "a clicked segment leaves the keys elsewhere|controls/SegmentedControl.qml|onClicked: { root.forceActiveFocus(); root.choose(index); }|onClicked: root.choose(index)|tst_segmented.qml"
  "the switch track ignores checked|controls/Switch.qml|color: root.checked ? (root.hovered|color: false ? (root.hovered|tst_toggles.qml"
  "the checkbox mark ignores checked|controls/Checkbox.qml|visible: root.checked|visible: false|tst_toggles.qml"
  "the radio dot ignores checked|controls/Radio.qml|visible: root.checked|visible: true|tst_toggles.qml"
  "the slider fill ignores the value|controls/Slider.qml|width: root.position * parent.width|width: parent.width|tst_slider.qml"
  "the mirrored slider fills from the left|controls/Slider.qml|x: root.mirrored ? parent.width - width : 0|x: 0|tst_slider.qml"
  "the segments take the tab focus|controls/SegmentedControl.qml|focusPolicy: Qt.NoFocus|focusPolicy: Qt.StrongFocus|tst_segmented.qml"
  "the slider handle ignores the value|controls/Slider.qml|x: root.leftPadding + root.visualPosition * (root.availableWidth - width)|x: root.leftPadding|tst_slider.qml"
  "the text field's outline ignores error|controls/TextField.qml|readonly property color outline: error ? Theme.textField.error :|readonly property color outline: false ? Theme.textField.error :|tst_textfield.qml"
  "the text field's placeholder never hides|controls/TextField.qml|visible: root.text === \"\" && root.preeditText === \"\"|visible: true|tst_textfield.qml"
  "the text field's placeholder keeps paragraph leading|controls/TextField.qml|role: \"item\"|role: \"body\"|tst_textfield.qml"
  "the leading icon reserves no space|controls/TextField.qml|leftPadding: sidePadding + (leadingIcon !== \"\" ? Theme.icon.size.md + Theme.textField.gap : 0)|leftPadding: sidePadding|tst_textfield.qml"
  "the field shows the hint over the error|controls/Field.qml|text: root.error !== \"\" ? root.error : root.hint|text: root.hint|tst_textfield.qml"
  "the inline field ignores the label width|controls/Field.qml|width: parent.width - (root.inline ? Theme.field.labelWidth + parent.spacing : 0)|width: parent.width|tst_textfield.qml"
  "the inline field row follows its content height|controls/Field.qml|height: root.inline ? Math.max(root.compact ? Theme.row.compactHeight : Theme.row.height, inlineLabel.implicitHeight, slot.childrenRect.height) : slot.childrenRect.height|height: slot.childrenRect.height|tst_textfield.qml"
  "the inline field hint starts under the label|controls/Field.qml|x: root.inline ? Theme.field.labelWidth + Theme.field.labelGap : 0|x: 0|tst_textfield.qml"
  "the segmented control ignores a click|controls/SegmentedControl.qml|onClicked: { root.forceActiveFocus(); root.choose(index); }|onClicked: {}|tst_segmented.qml"
  "the segmented control fires for the same segment|controls/SegmentedControl.qml|index === currentIndex) return;|false) return;|tst_segmented.qml"
  "the spinner turns under reduced motion|feedback/Spinner.qml|running: root.running && Theme.spinner.duration > 0|running: root.running|tst_feedback.qml"
  "the progress fill ignores the value|feedback/ProgressBar.qml|width: root.indeterminate ? span : root.position * parent.width|width: parent.width|tst_feedback.qml"
  "the mirrored progress fills from the left|feedback/ProgressBar.qml|x: root.mirrored && !root.indeterminate ? parent.width - width : 0|x: 0|tst_feedback.qml"
  "the key cap draws the code role|feedback/Kbd.qml|role: \"kbd\"|role: \"code\"|tst_feedback.qml"
  "the key cap takes its line box for its height|feedback/Kbd.qml|implicitHeight: Math.max(Theme.kbd.height, label.lineBox)|implicitHeight: label.lineBox|tst_feedback.qml"
  "the key cap shrinks below a square|feedback/Kbd.qml|implicitWidth: Math.max(Theme.kbd.height, Math.round(label.opticalWidth + 2 * sidePadding))|implicitWidth: label.opticalWidth + 2 * sidePadding|tst_feedback.qml"
  "the key cap does not centre its label|feedback/Kbd.qml|x: Math.round((root.width - opticalWidth) / 2)|x: Theme.kbd.paddingX / 2|tst_feedback.qml"
  "the code line copies nothing|feedback/CodeLine.qml|clipboard.copy();|clipboard.deselect();|tst_codeline.qml"
  "the code line signals no copy|feedback/CodeLine.qml|root.copied();|root.confirming;|tst_codeline.qml"
  "the code line confirms no copy|feedback/CodeLine.qml|iconName: root.confirming ? \"check\" : \"copy\"|iconName: \"copy\"|tst_codeline.qml"
  "the code line keeps the check mark|feedback/CodeLine.qml|interval: Theme.codeLine.confirm|interval: 60000|tst_codeline.qml"
  "the code line does not wrap|feedback/CodeLine.qml|wrapMode: Text.WrapAtWordBoundaryOrAnywhere|wrapMode: Text.NoWrap|tst_codeline.qml"
  "the code line's text runs under its button|feedback/CodeLine.qml|width: Math.max(0, button.x - Theme.codeLine.gap - x)|width: root.width - x|tst_codeline.qml"
  "the code line's button uses the old inset|feedback/CodeLine.qml|x: root.width - width - sideInset.inset|x: root.width - width - Theme.space.xxs|tst_codeline.qml"
  "the code line centres wrapped text|feedback/CodeLine.qml|y: lineCount <= 1 ? topForCapCenter(root.height) : Theme.codeLine.padding + halfLeading|y: topForCapCenter(root.height)|tst_codeline.qml"
  "the code line ignores its left padding|feedback/CodeLine.qml|x: sideInset.inset|x: Theme.space.xxs|tst_codeline.qml"
  "the code line ignores its fill token|feedback/CodeLine.qml|color: Theme.codeLine.background|color: Theme.codeLine.borderColor|tst_codeline.qml"
  "the badge ignores its tone|feedback/Badge.qml|const found = Theme.badge.tone[name];|const found = undefined;|tst_feedback.qml"
  "the tab does not check on click|layout/Tabs.qml|visible: tab.checked|visible: true|tst_layout.qml"
  "the list item ignores highlight|layout/ListItem.qml|root.highlighted ? (root.down ? Theme.listItem.selectedPressed : Theme.listItem.selected) :|false ? (root.down ? Theme.listItem.selectedPressed : Theme.listItem.selected) :|tst_layout.qml"
  "the surface ignores its level|foundation/Surface.qml|const found = Theme.surface.level[name];|const found = undefined;|tst_layout.qml"
  "the scroll area's content height ignores a direct child's offset|layout/ScrollArea.qml|bottom = Math.max(bottom, child.y + childHeight);|bottom = Math.max(bottom, childHeight);|tst_scroll.qml"
  "the segmented control stands at its own height|controls/SegmentedControl.qml|implicitHeight: Theme.segmented.height|implicitHeight: Theme.size.control.lg|tst_spacing.qml"
  "the segments pad off the control rhythm|controls/SegmentedControl.qml|                rightPadding: leftPadding|                rightPadding: Theme.space.sm|tst_spacing.qml"
  "the button pads off the control rhythm|controls/Button.qml|leftPadding: Inset.controlPadding(sizeTokens.paddingX, Theme.button.radius, controlHeight, implicitContentHeight, Theme.space.xs)|leftPadding: Theme.space.md|tst_spacing.qml"
  "the select pads off the control rhythm|controls/Select.qml|    leftPadding: sidePadding|    leftPadding: Theme.space.sm|tst_spacing.qml"
  "the text field pads off the control rhythm|controls/TextField.qml|leftPadding: sidePadding + (|leftPadding: Theme.space.sm + (|tst_spacing.qml"
  "the list item pads off the row rhythm|layout/ListItem.qml|leftPadding: Inset.controlPadding(Theme.listItem.paddingX,|leftPadding: Inset.controlPadding(Theme.space.sm,|tst_spacing.qml"
  "the list item uses the control gap after its icon|layout/ListItem.qml|x: icon.visible ? icon.width + Theme.listItem.iconGap : 0|x: icon.visible ? icon.width + Theme.control.gap : 0|tst_spacing.qml"
  "the menu item pads off the row rhythm|overlay/MenuItem.qml|Inset.controlPadding(Theme.menu.item.paddingX,|Inset.controlPadding(Theme.space.sm,|tst_spacing.qml"
  "the field draws its label on the column's edge|controls/Field.qml|leftPadding: Theme.field.paddingX|leftPadding: 0|tst_spacing.qml"
  "the button's icon gap is its own step|controls/Button.qml|spacing: sizeTokens.gap|spacing: Theme.space.xs|tst_spacing.qml"
  "the menu item's icon gap is its own step|overlay/MenuItem.qml|spacing: Theme.menu.item.gap|spacing: Theme.space.sm|tst_spacing.qml"
  "the badge's icon gap is its own step|feedback/Badge.qml|x: root.sidePadding + (icon.visible ? icon.width + Theme.badge.gap : 0)|x: root.sidePadding + (icon.visible ? icon.width + Theme.space.xxs : 0)|tst_spacing.qml"
  "the badge centres text by its box|feedback/Badge.qml|y: topForCapCenter(root.height)|y: Math.round((root.height - height) / 2)|tst_feedback.qml"
  "the badge uses its implicit text width|feedback/Badge.qml|label.opticalWidth|label.implicitWidth|tst_feedback.qml"
  "the toast's icon gap is its own step|feedback/Toast.qml|spacing: Theme.toast.contentGap|spacing: Theme.space.sm|tst_spacing.qml"
  "a lone face does not fill the avatar box|feedback/AvatarGroup.qml|readonly property real faceSize: places <= 1 ? size : size * faceShare|readonly property real faceSize: size * faceShare|tst_avatargroup.qml"
  "a lone face keeps a ring|feedback/AvatarGroup.qml|ringWidth: group.places > 1 ? group.ringWidth : 0|ringWidth: group.ringWidth|tst_avatargroup.qml"
  "two faces sit on one row|feedback/AvatarGroup.qml|[[0, 0], [1, 1]],|[[0, 0], [1, 0]],|tst_avatargroup.qml"
  "three faces sit in a row|feedback/AvatarGroup.qml|[[0.5, 0], [1, 1], [0, 1]],|[[0, 0], [0.5, 0], [1, 0]],|tst_avatargroup.qml"
  "the cluster runs anticlockwise|feedback/AvatarGroup.qml|[[0, 0], [1, 0], [1, 1], [0, 1]]|[[0, 0], [0, 1], [1, 1], [1, 0]]|tst_avatargroup.qml"
  "a face lies under the one before|feedback/AvatarGroup.qml|            z: index|            z: -index|tst_avatargroup.qml"
  "past four no chip counts the rest|feedback/AvatarGroup.qml|readonly property int faces: Math.min(people.length, total > 4 ? 3 : 4)|readonly property int faces: Math.min(people.length, 4)|tst_avatargroup.qml"
  "the chip counts only the extra count|feedback/AvatarGroup.qml|\"+\" + (group.total - group.faces)|\"+\" + group.more|tst_avatargroup.qml"
  "a face without a tint draws none|feedback/AvatarGroup.qml|person.tint : group.tint|person.tint : \"transparent\"|tst_avatargroup.qml"
  "the photo is not cut to a circle|feedback/AvatarFace.qml|maskEnabled: true|maskEnabled: false|tst_avatargroup.qml"
  "the photo never shows|feedback/AvatarFace.qml|visible: face.photoShown|visible: false|tst_avatargroup.qml"
  "the toast text does not clear a rounded corner|feedback/Toast.qml|x: contentInset.inset|x: root.basePadding|tst_spacing.qml"
  "the toast clears the whole corner above its text|feedback/Toast.qml|top: root.basePadding|top: 0|tst_spacing.qml"
  "the clearing inset ignores the helper value|../Commons/ClearingInset.qml|return Math.ceil(Inset.clearing(pad, radius, width, height, step, top));|return pad;|tst_spacing.qml"
  "the inline label stands the stacking gap from its control|controls/Field.qml|spacing: Theme.field.labelGap|spacing: Theme.field.gap|tst_textfield.qml"
  "a padded section header's lines overflow it|layout/SectionHeader.qml|readonly property real bodyWidth: width - leftPadding - rightPadding|readonly property real bodyWidth: width|tst_layout.qml"
  "a click on the disclosure's row toggles nothing|layout/Disclosure.qml|if (root.expandable) root.expanded = !root.expanded|if (root.expandable) {}|tst_disclosure.qml"
  "a disclosure that cannot expand toggles on a click|layout/Disclosure.qml|onClicked: if (root.expandable) |onClicked: if (true) |tst_disclosure.qml"
  "the disclosure shows its content while collapsed|layout/Disclosure.qml|visible: root.expandable && root.expanded|visible: root.expandable|tst_disclosure.qml"
  "the disclosure's chevron ignores the state|layout/Disclosure.qml|name: root.expanded ? \"chevron-up\" : \"chevron-down\"|name: \"chevron-down\"|tst_disclosure.qml"
  "a section ignores its parent's spacing|layout/Section.qml|topPadding: Positioner.isFirstItem ? 0 : Math.max(0, Theme.stack.section - parentSpacing)|topPadding: Positioner.isFirstItem ? 0 : Theme.stack.section|tst_layout.qml"
  "the first section takes top padding|layout/Section.qml|topPadding: Positioner.isFirstItem ? 0 : Math.max(0, Theme.stack.section - parentSpacing)|topPadding: Math.max(0, Theme.stack.section - parentSpacing)|tst_layout.qml"
  "a theme change does not reach a group|../Commons/Theme.qml|readonly property var color: published.color|readonly property var color: convert(source.defaults.values, []).color|tst_theme.qml"
  "an appearance reads the whole theme|../Commons/Theme.qml|return convertTree(table, accepted.values, accepted.values, []);|return convertTree(table, Object.assign({}, accepted.values, { card: Object.assign({}, accepted.values.card, { fill: source.values.color.surface }) }), accepted.values, []);|tst_appearance.qml"
  "a read a change overtook is reported|../Commons/WatchedFile.qml|if (operation === \"stale\") {|if (false) {|tst_watched_file.qml"
  "a change during a read is not marked stale|../Commons/WatchedFile.qml|onFileChanged: file.inRead ? file.read() : file.changed()|onFileChanged: file.changed()|tst_watched_file.qml"
  "a change during a write is lost|../Commons/WatchedFile.qml|onFileChanged: file.inRead ? file.read() : file.changed()|onFileChanged: file.busy ? file.read() : file.changed()|tst_watched_file.qml"
  "a read asked during a read starts nothing more|../Commons/WatchedFile.qml|            operation = \"stale\";|            return;|tst_watched_file.qml"
  "the reading view watches the file|../Commons/WatchedFile.qml|        id: view|        id: view; watchChanges: true|tst_watched_file.qml"
  "the watching view reads the file|../Commons/WatchedFile.qml|        preload: false|        preload: true|tst_watched_file.qml"
  "a read asked from a result handler is lost|../Commons/WatchedFile.qml|Qt.callLater(reloadView);|reloadView();|tst_watched_file.qml"
  "a write asked from a result handler is lost|../Commons/WatchedFile.qml|Qt.callLater(() => view.setText(content));|view.setText(content);|tst_watched_file.qml"
  "an appearance never applies its light overrides|../Commons/Theme.qml|ThemeLogic.acceptAppearance(table, light, source.values)|ThemeLogic.acceptAppearance(table, light, Object.assign({}, source.values, { scheme: { mode: \"dark\" } }))|tst_appearance.qml"
  "an image segment draws its alt text|foundation/ImageTextLogic.js|} else if (drawableUrl(segment.image) && failed.indexOf(segment.image) === -1) {|} else if (false) {|tst_imagetext.qml"
  "a line with an image grows|foundation/ImageText.qml|readonly property int imageSize: Math.floor(metrics.height)|readonly property int imageSize: Math.ceil(metrics.height) + 2|tst_imagetext.qml"
  "the text's colour fades its images|foundation/ImageText.qml|        color: root.color|        color: root.color; opacity: root.color.a|tst_imagetext.qml"
  "text without images is not elided|foundation/ImageText.qml|drawn.elide = Text.ElideRight;|drawn.elide = Text.ElideNone;|tst_imagetext.qml"
  "text with images takes Qt's elision|foundation/ImageText.qml|drawn.text = result.markup;|drawn.text = Logic.join(tokens, tokens.length); drawn.elide = Text.ElideRight;|tst_imagetext.qml"
  "the cut splits a word|foundation/ImageTextLogic.js|    return join(list, count) + ELLIPSIS;|    return join(list, count).slice(0, -2) + ELLIPSIS;|tst_imagetext.qml"
  "an unbroken word runs past the width|foundation/ImageText.qml|            drawn.wrapMode = Text.Wrap;|            drawn.wrapMode = Text.WordWrap;|tst_imagetext.qml"
  "the measure lets an unbroken word run past the width|foundation/ImageText.qml|        wrapMode: Text.Wrap|        wrapMode: Text.WordWrap|tst_imagetext.qml"
  "a failed image stays a hole|foundation/ImageText.qml|if (held[url].status === Image.Error && failed.indexOf(url) === -1) {|if (false) {|tst_imagetext.qml"
  "the pool shares no image|foundation/ImagePool.qml|let entry = entries[key];|let entry = undefined;|tst_imagetext.qml"
  "the pool keeps an image nobody holds|foundation/ImagePool.qml|if (entry.holders > 0) return;|return;|tst_imagetext.qml"
  "a TUI wait result never reaches the records|../Core/TuiRecords.qml|if (outcome.record !== null) {|if (false) {|tst_tui_records.qml"
  "a later run's wait record replaces an earlier run's of the key|../Core/TuiRecords.qml|waitRecords.filter(record => record.run !== outcome.record.run)|waitRecords.filter(record => record.key !== outcome.record.key)|tst_tui_records.qml"
  "the list cursor lands where it should travel|layout/ListCursor.qml|if (glide && root[property] !== value) {|if (false) {|tst_listcursor.qml"
  "the list cursor travels after a snap|layout/ListCursor.qml|        state.snapping = true;|        state.snapping = false;|tst_listcursor.qml"
  "the list cursor travels from where it was hidden|layout/ListCursor.qml|const glide = !state.snapping && root.shown && root.opacity > 0 && duration > 0;|const glide = !state.snapping && duration > 0;|tst_listcursor.qml"
  "the list cursor reads only the row's own place|layout/ListCursor.qml|for (const at of chain) {|for (const at of chain.slice(0, 1)) {|tst_listcursor.qml"
  "the list cursor stays when an item between moves|layout/ListCursor.qml|function onYChanged() { if (root !== null) root.place(); }|function onYChanged() {}|tst_listcursor.qml"
  "the list cursor takes a row outside its parent|layout/ListCursor.qml|if (chainOf(row) === null) {|if (false) {|tst_listcursor.qml"
  "a resting pointer takes the selection|layout/ListCursor.qml|const moved = Logic.pointerMoved(state.last, point);|const moved = true;|tst_listcursor.qml"
  "a key leaves the pointer armed|layout/ListCursor.qml|state.armed = false;|state.armed = state.armed;|tst_listcursor.qml"
  "the list cursor draws over its rows|layout/ListCursor.qml|    z: -1|    z: 1|tst_listcursor.qml"
  "a cursor in a painting parent is not refused|layout/ListCursor.qml|if (parent !== null && parent.color !== undefined && parent.color.a > 0)|if (false)|tst_listcursor.qml"
  "a reopened menu's cursor travels from the dismissed entry|overlay/Menu.qml|        plate.snap();|        Qt.callLater(plate.snap);|tst_overlays.qml"
  "a reopened select list's cursor travels from the dismissed entry|controls/Select.qml|        plate.snap();|        Qt.callLater(plate.snap);|tst_overlays.qml"
  "a click leaves the pointer disarmed|layout/ListCursor.qml|function arm() { state.armed = true; }|function arm() {}|tst_listcursor.qml"
  "the list cursor snaps past its turn|layout/ListCursor.qml|function settle() { snapping = false; }|function settle() {}|tst_listcursor.qml"
  "a later turn's rows wait behind the earlier turn's|layout/ListCursor.qml|if (state.arrivals === 0) Qt.callLater(state.endArrivals);|if (false) Qt.callLater(state.endArrivals);|tst_listcursor.qml"
  "the list cursor draws no background|layout/ListCursor.qml|background.parent = root;|background.parent = null;|tst_listcursor.qml"
  "the list cursor never fades|layout/ListCursor.qml|opacity: shown ? 1 : 0|opacity: 1|tst_listcursor.qml"
  "a faded list cursor takes room|layout/ListCursor.qml|visible: opacity > 0|visible: true|tst_listcursor.qml"
  "a row claims no cursor|layout/ListCursorRow.qml|onHoldsChanged: claim()|onHoldsChanged: {}|tst_listcursor.qml"
  "a hover emits no pointed|layout/ListCursorRow.qml|cursor.hoverTakes(point.scenePosition)) pointed()|cursor.hoverTakes(point.scenePosition)) {}|tst_listcursor.qml"
  "a plugin's bezier curve is dropped|layout/ListAnimation.qml|easing.bezierCurve: step.easing === Easing.BezierSpline ? step.curve : []|easing.bezierCurve: []|tst_listcursor.qml"
  "a list item under a cursor draws its own fill|layout/ListItem.qml|color: root.cursor !== null ? \"transparent\" : |color: |tst_listcursor.qml"
  "a list item in a cursor list does not enter|layout/ListItem.qml|Component.onCompleted: if (enters && cursor !== null) entrance.start(cursor.enterSlot(), 0)|Component.onCompleted: {}|tst_listcursor.qml"
  "a list item's opacity ignores its entrance|layout/ListItem.qml|(enabled ? 1 : Theme.opacity.disabled) * entrance.progress|(enabled ? 1 : Theme.opacity.disabled)|tst_listcursor.qml"
  "rows enter together|layout/ListEntrance.qml|run.delay = Logic.enterDelay(slot, motion.stagger, motion.staggerRows);|run.delay = 0;|tst_listcursor.qml"
  "a row enters without rising|layout/ListEntrance.qml|(1 - progress) * motion.rise|0|tst_listcursor.qml"
  "a row enters without sliding|layout/ListEntrance.qml|x: (1 - progress) * direction * shift|x: 0|tst_listcursor.qml"
  "the menu hands its entries no cursor|overlay/Menu.qml|Component.onCompleted: modelData.cursor = plate|Component.onCompleted: {}|tst_overlays.qml"
  "a hover highlights no menu entry|overlay/Menu.qml|function onPointed() { if (root.reachable(modelData)) root.currentIndex = root.items().indexOf(modelData); }|function onPointed() { root.currentIndex = root.items().indexOf(modelData); }|tst_overlays.qml"
  "a menu key leaves the pointer armed|overlay/Menu.qml|function keyTo(index) { plate.disarm(); currentIndex = index; }|function keyTo(index) { currentIndex = index; }|tst_overlays.qml"
  "a menu entry under a cursor draws its own fill|overlay/MenuItem.qml|color: root.cursor !== null ? \"transparent\" : root.down ? Theme.menu.item.pressed|color: root.down ? Theme.menu.item.pressed|tst_overlays.qml"
  "a hover highlights no select entry|controls/Select.qml|onPointed: entries.currentIndex = entry.index|onPointed: {}|tst_overlays.qml"
  "a select key leaves the pointer armed|controls/Select.qml|{ plate.disarm(); event.accepted = false; }|{ event.accepted = false; }|tst_overlays.qml"
  "a select entry draws the highlight's fill|controls/Select.qml|color: entry.chosen ? Theme.select.selected : \"transparent\"|color: entry.chosen ? Theme.select.selected : entry.highlighted ? Theme.select.highlight : \"transparent\"|tst_overlays.qml"
  "the button pads every size alike|controls/Button.qml|leftPadding: Inset.controlPadding(sizeTokens.paddingX,|leftPadding: Inset.controlPadding(Theme.button.paddingX,|tst_button.qml"
  "the button's icon ignores its size|controls/Button.qml|size: root.sizeTokens.icon|size: Theme.icon.size.sm|tst_button.qml"
  "the button's gap ignores its size|controls/Button.qml|spacing: sizeTokens.gap|spacing: Theme.button.gap|tst_button.qml"
  "a checked button shows no hover|controls/Button.qml|checked ? (down ? Theme.button.checked.pressed : hovered ? Theme.button.checked.hover : Theme.button.checked.background)|checked ? Theme.button.checked.background|tst_button.qml"
  "a rounded button keeps its pad|controls/Button.qml|Inset.controlPadding(sizeTokens.paddingX, Theme.button.radius,|Inset.controlPadding(sizeTokens.paddingX, 0,|tst_button.qml"
  "the ring ignores the control's corner|foundation/FocusRing.qml|readonly property real ringRadius: targetRadius + offset|readonly property real ringRadius: Theme.focusRing.radius + offset|tst_button.qml"
  "the icon button reads no glyph inset|controls/IconButton.qml|readonly property real glyphStart: leftPadding + contentItem.painted[0]|readonly property real glyphStart: leftPadding|tst_button.qml"
  "the icon's extent ignores the path|foundation/Icon.qml|const box = IconBounds.bounds(data[0] + \" \" + data[1]);|const box = { left: 0, top: 0, right: 24, bottom: 24 };|tst_icon.qml"
  "a focused field in error loses its cue|controls/TextField.qml|ringColor: root.error ? Theme.textField.error : Theme.focusRing.color|ringColor: Theme.focusRing.color|tst_textfield.qml"
  "the field's icons stay small|controls/TextField.qml|leftPadding: sidePadding + (leadingIcon !== \"\" ? Theme.icon.size.md|leftPadding: sidePadding + (leadingIcon !== \"\" ? Theme.icon.size.sm|tst_textfield.qml"
  "the menu grows past its maximum width|overlay/Menu.qml|implicitWidth: Math.min(OverlayState.widthFor(root.anchorItem, Theme.menu.maxWidth), |implicitWidth: (|tst_overlays.qml"
  "the menu entry's text never elides|overlay/MenuItem.qml|width: Math.max(0, parent.width - parent.lead - parent.tail)|width: implicitWidth|tst_overlays.qml"
  "the menu's entries leave the bar a strip inside the padding|overlay/Menu.qml|rightInset: Theme.menu.padding|rightInset: Theme.scrollArea.gutter + Theme.menu.padding|tst_overlays.qml"
  "the select list opens on the control's edge|controls/Select.qml|anchor.margins.left: -Theme.menu.padding|anchor.margins.left: 0|tst_overlays.qml"
  "the select entries start at the menu's padding|controls/Select.qml|                leftPadding: root.sidePadding|                leftPadding: Theme.menu.item.paddingX + Theme.menu.padding|tst_overlays.qml"
  "the tooltip never wraps|overlay/Tooltip.qml|wrapMode: Text.Wrap|wrapMode: Text.NoWrap|tst_overlays.qml"
  "the tooltip grows past its maximum width|overlay/Tooltip.qml|OverlayState.widthFor(root.anchorItem, Theme.tooltip.maxWidth + 2 * sideInset.inset)|100000|tst_overlays.qml"
  "a rounded tooltip keeps its pad|overlay/Tooltip.qml|x: sideInset.inset|x: Theme.tooltip.paddingX|tst_overlays.qml"
  "a pressed row leaves the plate at rest|layout/ListCursor.qml|color: root.pressed ? root.pressedColor : root.color|color: root.color|tst_listcursor.qml"
  "a loose row presses like a hover|layout/ListItem.qml|: root.down ? Theme.listItem.pressed : root.hovered|: root.down ? Theme.listItem.hover : root.hovered|tst_listcursor.qml"
  "a compact track keeps no input area|controls/Switch.qml|implicitHeight: Math.max(Theme.size.control.sm, implicitIndicatorHeight, implicitContentHeight)|implicitHeight: Math.max(implicitIndicatorHeight, implicitContentHeight)|tst_toggles.qml"
  "the switch shows no hover|controls/Switch.qml|Theme.toggle.offHover : Theme.toggle.off|Theme.toggle.off : Theme.toggle.off|tst_toggles.qml"
  "the checkbox shows no press|controls/Checkbox.qml|: root.down ? Theme.checkbox.pressed : Theme.checkbox.background|: Theme.checkbox.background|tst_toggles.qml"
  "the slider keeps no input area|controls/Slider.qml|implicitHeight: Math.max(Theme.size.control.sm, |implicitHeight: Math.max(|tst_slider.qml"
  "the tab label hugs its left edge|layout/Tabs.qml|horizontalAlignment: Text.AlignHCenter|horizontalAlignment: Text.AlignLeft|tst_layout.qml"
  "tab hover reads as the open tab|layout/Tabs.qml|Theme.tabs.hover : Theme.tabs.foreground|Theme.tabs.active : Theme.tabs.foreground|tst_layout.qml"
  "the tabs ignore disabled|layout/Tabs.qml|    opacity: enabled ? 1 : Theme.opacity.disabled|    opacity: 1|tst_layout.qml"
  "a segment shows no hover|controls/SegmentedControl.qml|: segment.hovered ? Theme.segmented.hover : \"transparent\"|: \"transparent\"|tst_segmented.qml"
  "a segment's corner ignores the inset|controls/SegmentedControl.qml|radius: Math.max(0, Theme.segmented.radius - Theme.segmented.padding)|radius: Theme.segmented.radius|tst_segmented.qml"
  "the underline shows at rest|controls/TitleButton.qml|            visible: root.engaged|            visible: true|tst_titlebutton.qml"
  "the caret sits on a half pixel|controls/TitleButton.qml|y: Math.round(label.capCentre - height / 2)|y: label.capCentre - height / 2 + 0.5|tst_titlebutton.qml"
  "the toast icon sits at the row top|feedback/Toast.qml|            y: Math.round(titleLabel.capCentre - height / 2)|            y: 0|tst_spacing.qml"
  "a section heading indents by default|layout/Section.qml|property real headerInset: 0|property real headerInset: Theme.row.paddingX|tst_spacing.qml"
  "a section ignores its row spacing|layout/Section.qml|spacing: root.rowSpacing|spacing: Theme.stack.row|tst_spacing.qml"
  "a disclosure's content starts at the icon|layout/Disclosure.qml|        x: inset|        x: 0|tst_spacing.qml"
  "a compact field keeps the full row|controls/Field.qml|root.compact ? Theme.row.compactHeight : Theme.row.height|Theme.row.height|tst_spacing.qml"
  "a rounded badge keeps its pad|feedback/Badge.qml|Inset.controlPadding(sizeTokens.paddingX, Theme.badge.radius,|Inset.controlPadding(sizeTokens.paddingX, 0,|tst_spacing.qml"
  "a rounded key cap keeps its pad|feedback/Kbd.qml|Inset.controlPadding(Theme.kbd.paddingX, Theme.kbd.radius,|Inset.controlPadding(Theme.kbd.paddingX, 0,|tst_spacing.qml"
  "a rounded list row keeps its pad|layout/ListItem.qml|Inset.controlPadding(Theme.listItem.paddingX, Theme.listItem.radius,|Inset.controlPadding(Theme.listItem.paddingX, 0,|tst_spacing.qml"
  "a rounded menu entry keeps its pad|overlay/MenuItem.qml|Inset.controlPadding(Theme.menu.item.paddingX, Theme.menu.item.radius,|Inset.controlPadding(Theme.menu.item.paddingX, 0,|tst_spacing.qml"
  "a rounded text field keeps its pad|controls/TextField.qml|Inset.controlPadding(Theme.textField.paddingX, Theme.textField.radius,|Inset.controlPadding(Theme.textField.paddingX, 0,|tst_spacing.qml"
  "a rounded select keeps its pad|controls/Select.qml|Inset.controlPadding(Theme.textField.paddingX, Theme.textField.radius,|Inset.controlPadding(Theme.textField.paddingX, 0,|tst_spacing.qml"
  "a rounded segment keeps its pad|controls/SegmentedControl.qml|Inset.controlPadding(Theme.segmented.paddingX, Math.max(0, Theme.segmented.radius - Theme.segmented.padding),|Inset.controlPadding(Theme.segmented.paddingX, 0,|tst_spacing.qml"
  "a rounded code line keeps its pad|feedback/CodeLine.qml|        radius: Theme.codeLine.radius|        radius: 0|tst_spacing.qml"
  "a code line wraps inside words|feedback/CodeLine.qml|wrapMode: Text.WrapAtWordBoundaryOrAnywhere|wrapMode: Text.WrapAnywhere|tst_codeline.qml"
  "the pane's padding ignores its input|layout/Pane.qml|readonly property real basePadding: padding|readonly property real basePadding: paddingOf(container)|tst_pane.qml"
  "the header divider never shows|layout/Pane.qml|visible: root.headerHeight > 0 && scroll.contentY > 0|visible: false|tst_pane.qml"
  "the viewport clips a ring on the edge|layout/Pane.qml|readonly property real ringRoom: Theme.focusRing.width + Theme.focusRing.offset|readonly property real ringRoom: 0|tst_pane.qml"
  "the pane clears the whole corner|layout/Pane.qml|        top: root.basePadding|        top: 0|tst_pane.qml"
  "an icon-only bar item is not square|controls/BarItem.qml|leftPadding: iconOnly ? Math.floor((Theme.bar.item.height - Theme.bar.item.icon) / 2) : Theme.bar.item.paddingX|leftPadding: Theme.bar.item.paddingX|tst_baritem.qml"
  "the bar item's count ignores its tone|controls/BarItem.qml|readonly property color foreground: active ? Theme.bar.onActive : tone|readonly property color foreground: active ? Theme.bar.onActive : Theme.bar.foreground|tst_baritem.qml"
  "the bar item shows no press|controls/BarItem.qml|root.down ? Theme.bar.item.pressed : root.hovered|root.hovered|tst_baritem.qml"
  "a long inline label elides on one line|controls/Field.qml|            maximumLineCount: 2|            maximumLineCount: 1|tst_textfield.qml"
  "the field publishes no value column|controls/Field.qml|readonly property real valueX: leftPadding + (inline ? Theme.field.labelWidth + Theme.field.labelGap : 0)|readonly property real valueX: leftPadding|tst_textfield.qml"
  "a row that cannot expand gives up its chevron's room|layout/Disclosure.qml|opacity: root.expandable ? 1 : 0|visible: root.expandable|tst_disclosure.qml"
  "a pane's footer divider shows only while more lies below|layout/Pane.qml|visible: root.footerHeight > 0 && scroll.contentY + scroll.height < scroll.contentHeight - 1|visible: root.footerHeight > 0|tst_pane.qml"
  "a title button reports its title's capital centre|controls/TitleButton.qml|readonly property real capCentre: topPadding + label.capCentre|readonly property real capCentre: topPadding + label.height / 2|tst_titlebutton.qml"
)

copy="$tmp/ui"
fresh "$copy"
if out="$("$runner" --ui "$copy" 2>&1)"; then ok "the unmutated copy passes"; else fail "the unmutated copy fails"; printf '%s\n' "$out" | tail -n 20; fi

for row in "${mutations[@]}"; do
  IFS='|' read -r label file needle replacement test <<<"$row"
  # A `|` inside a field shifts the rest, and a runner handed a test that is
  # not there fails, which would read as a red mutation.
  if [[ ! -f $repo/scripts/qml-tests/$test ]]; then fail "$label: the row's test is not a file: $test"; continue; fi
  fresh "$copy"
  target="$copy/$file"
  commons_args=()
  core_args=()
  if [[ $file == ../Commons/* ]]; then
    rm -rf -- "$tmp/commons"
    cp -R -- "$repo/shell/Commons" "$tmp/commons"
    target="$tmp/commons/${file#../Commons/}"
    commons_args=(--commons "$tmp/commons")
  fi
  if [[ $file == ../Core/* ]]; then
    rm -rf -- "$tmp/core"
    cp -R -- "$repo/shell/Core" "$tmp/core"
    target="$tmp/core/${file#../Core/}"
    core_args=(--core "$tmp/core")
  fi
  count="$(python3 - "$target" "$needle" <<'PY'
import sys
print(open(sys.argv[1], encoding="utf-8").read().count(sys.argv[2]))
PY
)"
  if [[ $count -ne 1 ]]; then fail "$label: the text to replace occurs $count times in $file"; continue; fi
  python3 - "$target" "$needle" "$replacement" <<'PY'
import sys
path, needle, replacement = sys.argv[1:]
text = open(path, encoding="utf-8").read()
open(path, "w", encoding="utf-8").write(text.replace(needle, replacement))
PY
  if out="$("$runner" --ui "$copy" "${commons_args[@]}" "${core_args[@]}" "$repo/scripts/qml-tests/$test" 2>&1)"; then
    fail "$label: $test passed on the mutated copy"
  else
    ok "$label"
  fi
done

if out="$(QML_UNIT_RUNNER=/nonexistent/qmltestrunner "$runner" --ui "$copy" 2>&1)"; then
  fail "a missing runner passed"
elif [[ $out == "qml-unit: status=not-measured missing=qmltestrunner" ]]; then
  ok "a missing runner is not a pass"
else
  fail "a missing runner: got $out"
fi
if out="$("$runner" --nope 2>&1)"; then fail "an unknown argument passed"; elif [[ $out == "qml-unit: refused: argument=--nope" ]]; then ok "an unknown argument is refused"; else fail "an unknown argument: got $out"; fi

# Rows: label | name of the planted tst_<name>.qml | the runner's exit |
# the line it must print | the file's lines after the planted head, whose
# body starts at line 6; printf %b expands the \n.
planted_head='import QtQuick\nimport QtTest\nTestCase {\n    id: planted\n    name: "planted"\n'
logs=(
  "an unexpected console.error fails|error|1|qml-unit: unexpected-log file=tst_error.qml line=QCRITICAL: qmltestrunner::planted::test_a() critical: qml: planted log|    function test_a() { console.error(\"planted log\"); }\n"
  "an unexpected console.warn fails|warn|1|qml-unit: unexpected-log file=tst_warn.qml line=QWARN  : qmltestrunner::planted::test_a() warning: qml: planted log|    function test_a() { console.warn(\"planted log\"); }\n"
  "a declared log passes|declared|0|qml-unit: ok files=1|    // expected-log: planted log -- the row plants it\n    function test_a() { console.error(\"planted log\"); }\n"
  "a declaration that matches nothing fails|stale|1|qml-unit: expected-log unmatched file=tst_stale.qml line=6 message=planted log|    // expected-log: planted log -- the row plants it\n    function test_a() { verify(true); }\n"
  "a declaration covers no other function|other|1|qml-unit: unexpected-log file=tst_other.qml line=QCRITICAL: qmltestrunner::planted::test_b() critical: qml: planted log|    // expected-log: planted log -- the row plants it\n    function test_a() { console.error(\"planted log\"); }\n    function test_b() { console.error(\"planted log\"); }\n"
  "a declaration with no reason is refused|noreason|2|qml-unit: refused: expected-log=no-reason file=tst_noreason.qml line=6|    // expected-log: planted log\n    function test_a() { console.error(\"planted log\"); }\n"
  "a declaration with no function under it is refused|nofunction|2|qml-unit: refused: expected-log=no-function file=tst_nofunction.qml line=6|    // expected-log: planted log -- the row plants it\n    property int n: 0\n    function test_a() { console.error(\"planted log\"); }\n"
  "a log at load fails|load|1|qml-unit: unexpected-log file=tst_load.qml line=critical: qml: planted log|    Component.onCompleted: console.error(\"planted log\")\n    function test_a() { verify(true); }\n"
  "a declaration does not excuse a script error|script|1|qml-unit: warnings file=tst_script.qml|    // expected-log: ReferenceError -- the row plants it\n    function test_a() { Qt.createQmlObject(\"import QtQuick; Item { property int n: noSuchName.x }\", planted); }\n"
)
mkdir -p "$tmp/logs"
for row in "${logs[@]}"; do
  IFS='|' read -r label name want_status want_line body <<<"$row"
  printf '%b%b}\n' "$planted_head" "$body" >"$tmp/logs/tst_$name.qml"
  got_status=0
  out="$("$runner" --tests "$repo/scripts/qml-tests" "$tmp/logs/tst_$name.qml" 2>&1)" || got_status=$?
  if [[ $got_status -ne $want_status ]]; then
    fail "$label: exit $got_status, want $want_status"
    printf '%s\n' "$out" | tail -n 20
  elif ! grep -qFx -- "$want_line" <<<"$out"; then
    fail "$label: no line: $want_line"
    printf '%s\n' "$out" | tail -n 20
  else
    ok "$label"
  fi
done

if [[ $failures -eq 0 ]]; then
  echo "test-qml-unit: ok mutations=${#mutations[@]} logs=${#logs[@]}"
  exit 0
fi
echo "test-qml-unit: failed=$failures"
exit 1
