return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#040303",
				bg = "#040303",
				dark_bg = "#030202",
				darker_bg = "#020202",
				lighter_bg = "#131212",
				selection = "#aaacac",
				selection_background = "#aaacac",
				selection_foreground = "#ffffff",
				foreground = "#ffffff",
				fg = "#ffffff",
				light_fg = "#ffffff",
				bright_fg = "#ffffff",
				dark_fg = "#8e8e8e",
				muted = "#7f6e6e",
				cursor = "#ffffff",
				accent = "#aaacac",
				red = "#f82a2a",
				green = "#d1d2d1",
				yellow = "#fef348",
				blue = "#aaacac",
				purple = "#f76e78",
				magenta = "#f76e78",
				cyan = "#babbbb",
				orange = "#ff7f7f",
				brown = "#cc6666",
				bright_red = "#ff7f7f",
				bright_green = "#ffffff",
				bright_yellow = "#fff9a3",
				bright_blue = "#d8d9d9",
				bright_purple = "#ffc2c7",
				bright_cyan = "#e8e9e9",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
