statusBg = "#232530"
surfaceVariant = "#232530"
surfaceContainerLow = "#232530"
surfaceContainer = "#232530"
surfaceContainerHigh = "#2e303e"
surfaceContainerHighest = "#2e303e"
outline = "#6c6f93"
outlineVariant = "#6c6f93"
