# VGS generated kitty theme — include from kitty.conf: include vgs-theme.conf
foreground #35302a
background #f5e6d3
cursor #dea193
cursor_text_color #f5e6d3
selection_foreground #35302a
selection_background #c68d95
url_color #9e4f5b
active_border_color #9e4f5b
inactive_border_color #a69b8d
bell_border_color #8a5a00
active_tab_foreground #f5e6d3
active_tab_background #9e4f5b
inactive_tab_foreground #6c655b
inactive_tab_background #ded5c9
tab_bar_background #c7b9a7
color0 #35302a
color1 #a02b16
color2 #54703f
color3 #644535
color4 #76634c
color5 #78292e
color6 #b2688d
color7 #d3bb9d
color8 #80623a
color9 #a02b16
color10 #659144
color11 #694c45
color12 #76634c
color13 #78292e
color14 #713a56
color15 #f5ede2
