local p = require("retro82.palette")

return {
  ["Boolean"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["ColorColumn"] = { fg = "NONE", bg = p.bg3, sp = "NONE" },
  ["Comment"] = { fg = p.comment, bg = "NONE", sp = "NONE" },
  ["Constant"] = { fg = p.constant, bg = "NONE", sp = "NONE" },
  ["CursorColumn"] = { fg = "NONE", bg = p.surface, sp = "NONE" },
  ["Cursor"] = { fg = p.bg0, bg = p.border, sp = "NONE" },
  ["CursorLine"] = { fg = "NONE", bg = p.surface, sp = "NONE" },
  ["CursorLineNr"] = { fg = p.border, bg = p.surface, sp = "NONE", bold = true },
  ["Delimiter"] = { fg = p.fg1, bg = "NONE", sp = "NONE" },
  ["DiffAdded"] = { fg = p.added, bg = p.surface, sp = "NONE" },
  ["DiffAdd"] = { fg = p.bg0, bg = p.added, sp = "NONE" },
  ["DiffChange"] = { fg = p.bg0, bg = p.modified, sp = "NONE" },
  ["DiffDelete"] = { fg = p.bg0, bg = p.base12, sp = "NONE", bold = true },
  ["DiffRemoved"] = { fg = p.deleted, bg = p.surface, sp = "NONE" },
  ["DiffText"] = { fg = p.bg0, bg = p.info, sp = "NONE", bold = true },
  ["Directory"] = { fg = p.link, bg = p.bg0, sp = "NONE" },
  ["Error"] = { fg = p.text_bright, bg = p.base12, sp = "NONE" },
  ["ErrorMsg"] = { fg = p.error, bg = p.bg0, sp = "NONE" },
  ["FloatShadow"] = { fg = "NONE", bg = p.bg3, sp = "NONE" },
  ["FloatShadowThrough"] = { fg = "NONE", bg = p.surface_alt, sp = "NONE" },
  ["FoldColumn"] = { fg = p.muted, bg = p.surface, sp = "NONE" },
  ["Folded"] = { fg = p.special, bg = p.surface, sp = "NONE" },
  ["Function"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["Identifier"] = { fg = p.identifier, bg = "NONE", sp = "NONE" },
  ["Ignore"] = { fg = p.surface_highlight, bg = "NONE", sp = "NONE", underline = true },
  ["IncSearch"] = { fg = p.bg0, bg = p.base13, sp = "NONE", bold = true },
  ["Keyword"] = { fg = p.keyword, bg = "NONE", sp = "NONE" },
  ["lCursor"] = { fg = "bg", bg = "fg", sp = "NONE" },
  ["LineNr"] = { fg = p.muted, bg = p.bg0, sp = "NONE" },
  ["Character"] = { link = "Constant" },
  ["Conceal"] = { link = "Ignore" },
  ["Conditional"] = { link = "Statement" },
  ["CurSearch"] = { link = "Search" },
  ["CursorLineFold"] = { link = "FoldColumn" },
  ["CursorLineSign"] = { link = "SignColumn" },
  ["Debug"] = { link = "Special" },
  ["Define"] = { link = "PreProc" },
  ["EndOfBuffer"] = { link = "NonText" },
  ["Exception"] = { link = "Statement" },
  ["Float"] = { link = "Number" },
  ["FloatTitle"] = { link = "Title" },
  ["Include"] = { link = "PreProc" },
  ["Label"] = { link = "Statement" },
  ["LineNrAbove"] = { link = "LineNr" },
  ["LineNrBelow"] = { link = "LineNr" },
  ["Macro"] = { link = "PreProc" },
  ["MsgSeparator"] = { link = "StatusLine" },
  ["NvimArrow"] = { link = "Delimiter" },
  ["NvimColon"] = { link = "Delimiter" },
  ["NvimComma"] = { link = "Delimiter" },
  ["NvimFigureBrace"] = { link = "NvimInternalError" },
  ["NvimIdentifier"] = { link = "Identifier" },
  ["NvimInvalid"] = { link = "Error" },
  ["NvimInvalidSingleQuotedUnknownEscape"] = { link = "NvimInternalError" },
  ["NvimInvalidSpacing"] = { link = "ErrorMsg" },
  ["NvimNumber"] = { link = "Number" },
  ["NvimNumberPrefix"] = { link = "Type" },
  ["NvimOptionSigil"] = { link = "Type" },
  ["NvimParenthesis"] = { link = "Delimiter" },
  ["NvimSingleQuotedUnknownEscape"] = { link = "NvimInternalError" },
  ["NvimSpacing"] = { link = "Normal" },
  ["NvimString"] = { link = "String" },
  ["Operator"] = { fg = p.operator, bg = "NONE", sp = "NONE" },
  ["PmenuExtra"] = { link = "Pmenu" },
  ["PmenuExtraSel"] = { link = "PmenuSel" },
  ["PmenuKind"] = { link = "Pmenu" },
  ["PmenuKindSel"] = { link = "PmenuSel" },
  ["PreCondit"] = { link = "PreProc" },
  ["PreProc"] = { fg = p.preproc, bg = "NONE", sp = "NONE" },
  ["QuickFixLine"] = { link = "Search" },
  ["Repeat"] = { link = "Statement" },
  ["SpecialChar"] = { link = "Special" },
  ["SpecialComment"] = { link = "Special" },
  ["StorageClass"] = { link = "Type" },
  ["Structure"] = { link = "Type" },
  ["Substitute"] = { link = "Search" },
  ["Tag"] = { link = "Special" },
  ["Typedef"] = { link = "Type" },
  ["Whitespace"] = { link = "NonText" },
  ["WinBarNC"] = { link = "WinBar" },
  ["WinSeparator"] = { link = "VertSplit" },
  ["MatchParen"] = { fg = p.text, bg = "NONE", sp = "NONE", bold = true, underline = true },
  ["ModeMsg"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true },
  ["MoreMsg"] = { fg = p.success, bg = "NONE", sp = "NONE", bold = true },
  ["NonText"] = { fg = p.muted, bg = "NONE", sp = "NONE", bold = true },
  ["Normal"] = { fg = p.text, bg = p.bg0, sp = "NONE" },
  ["NormalFloat"] = { fg = p.text, bg = p.bg_alt, sp = "NONE" },
  ["Number"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["NvimInternalError"] = { fg = p.surface, bg = p.error, sp = "NONE" },
  ["Pmenu"] = { fg = p.text, bg = p.bg_alt, sp = "NONE" },
  ["PmenuMatch"] = { fg = p.text, bg = "NONE", sp = "NONE", bold = true },
  ["PmenuMatchSel"] = { fg = p.text_bright, bg = p.base16, sp = "NONE", bold = true },
  ["PmenuSbar"] = { fg = "NONE", bg = p.surface, sp = "NONE" },
  ["PmenuSel"] = { fg = p.text_bright, bg = p.base16, sp = "NONE" },
  ["PmenuThumb"] = { fg = p.text, bg = p.text, sp = "NONE" },
  ["Question"] = { fg = p.success, bg = "NONE", sp = "NONE", bold = true },
  ["RedrawDebugClear"] = { fg = p.bg0, bg = p.base15, sp = "NONE" },
  ["RedrawDebugComposed"] = { fg = p.bg0, bg = p.statement, sp = "NONE" },
  ["RedrawDebugNormal"] = { fg = "NONE", bg = "NONE", sp = "NONE", reverse = true },
  ["RedrawDebugRecompose"] = { fg = p.bg0, bg = p.warning, sp = "NONE" },
  ["Search"] = { fg = p.bg0, bg = p.base15, sp = "NONE", bold = true },
  ["SignColumn"] = { fg = p.muted, bg = p.surface, sp = "NONE" },
  ["Special"] = { fg = p.special, bg = "NONE", sp = "NONE" },
  ["SpecialKey"] = { fg = p.support, bg = "NONE", sp = "NONE" },
  ["SpellBad"] = { fg = p.warning, bg = "NONE", sp = p.text, underline = true },
  ["SpellCap"] = { fg = p.support, bg = "NONE", sp = p.text, underline = true },
  ["SpellLocal"] = { fg = p.special, bg = "NONE", sp = p.text, underline = true },
  ["SpellRare"] = { fg = p.error, bg = "NONE", sp = p.text, underline = true },
  ["Statement"] = { fg = p.statement, bg = "NONE", sp = "NONE", bold = true },
  ["StatusLine"] = { fg = p.text, bg = p.panel, sp = "NONE", bold = true },
  ["StatusLineNC"] = { fg = p.muted, bg = p.panel_deep, sp = "NONE", bold = true },
  ["String"] = { fg = p.string, bg = "NONE", sp = "NONE" },
  ["TabLineFill"] = { fg = p.base15, bg = p.bg3, sp = "NONE" },
  ["TabLine"] = { fg = p.muted, bg = p.bg3, sp = "NONE" },
  ["TabLineSel"] = { fg = p.bg0, bg = p.base16, sp = "NONE", bold = true },
  ["TabLineSelSep"] = { fg = p.statement, bg = p.surface, sp = "NONE", bold = true },
  ["TabLineSep"] = { fg = p.bg3, bg = p.bg3, sp = "NONE" },
  ["TermCursor"] = { fg = "NONE", bg = "NONE", sp = "NONE", reverse = true },
  ["Title"] = { fg = p.keyword, bg = "NONE", sp = "NONE", bold = true },
  ["Todo"] = { fg = p.text, bg = "NONE", sp = "NONE", bold = true, underline = true },
  ["Type"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["Underlined"] = { fg = p.link, bg = "NONE", sp = "NONE", underline = true },
  ["User1"] = { fg = p.text, bg = p.keyword, sp = "NONE" },
  ["User2"] = { fg = p.text, bg = p.muted, sp = "NONE" },
  ["User3"] = { fg = p.text, bg = p.error, sp = "NONE" },
  ["User4"] = { fg = p.text, bg = p.bg0, sp = "NONE" },
  ["User5"] = { fg = p.text, bg = p.warning, sp = "NONE" },
  ["User6"] = { fg = p.text, bg = p.parameter, sp = "NONE" },
  ["User7"] = { fg = p.text, bg = p.statement, sp = "NONE" },
  ["User8"] = { fg = p.text, bg = p.error, sp = "NONE" },
  ["User9"] = { fg = p.text, bg = p.muted, sp = "NONE" },
  ["VertSplit"] = { fg = p.border, bg = p.bg0, sp = "NONE" },
  ["Visual"] = { fg = p.text_bright, bg = p.selection, sp = "NONE" },
  ["WarningMsg"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["WildMenu"] = { fg = p.bg0, bg = p.base15, sp = "NONE" },
  ["FloatBorder"] = { fg = p.border, bg = p.bg_alt, sp = "NONE" },
  ["WinBar"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true },
}
