local p = require("retro82.palette")

return {
  ["GitSignsAdd"] = { fg = p.added, bg = p.bg1, sp = "NONE" },
  ["GitSignsChange"] = { fg = p.modified, bg = p.bg1, sp = "NONE" },
  ["GitSignsDelete"] = { fg = p.deleted, bg = p.bg1, sp = "NONE" },
  ["IblIndent"] = { fg = p.bg1, bg = "NONE", sp = "NONE", nocombine = true },
  ["IblScope"] = { fg = p.bg2, bg = "NONE", sp = "NONE", nocombine = true },
  ["IblWhitespace"] = { fg = p.bg1, bg = "NONE", sp = "NONE", nocombine = true },
  ["LazyButtonActive"] = { fg = p.bg0, bg = p.statement, sp = "NONE" },
  ["LazyButton"] = { fg = "NONE", bg = p.bg0, sp = "NONE" },
  ["LazyComment"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyCommit"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyCommitIssue"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyCommitScope"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyCommitType"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyDimmed"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyDir"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyH1"] = { fg = p.statement, bg = p.bg0, sp = "NONE" },
  ["LazyH2"] = { fg = p.statement, bg = p.bg0, sp = "NONE" },
  ["LazyLocal"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyNoCond"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyNormal"] = { fg = "NONE", bg = p.bg0, sp = "NONE" },
  ["LazyProgressDone"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyProgressTodo"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyProp"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonCmd"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonEvent"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonFt"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonImport"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonKeys"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonPlugin"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonRuntime"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonSource"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyReasonStart"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazySpecial"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["LazyTaskError"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyTaskOutput"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyUrl"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["LazyValue"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["CtrlPLinePre"] = { link = "Comment" },
  ["CtrlPMatch"] = { link = "String" },
  ["FzfLuaBorder"] = { link = "Normal" },
  ["FzfLuaCursor"] = { link = "Cursor" },
  ["FzfLuaCursorLine"] = { link = "CursorLine" },
  ["FzfLuaCursorLineNr"] = { link = "CursorLineNr" },
  ["FzfLuaNormal"] = { link = "Normal" },
  ["FzfLuaScrollFloatEmpty"] = { link = "PmenuSbar" },
  ["FzfLuaScrollFloatFull"] = { link = "PmenuThumb" },
  ["FzfLuaSearch"] = { link = "IncSearch" },
  ["MasonHeaderSecondary"] = { link = "LazyButtonActive" },
  ["MasonHighlightBlockBold"] = { link = "LazyButtonActive" },
  ["MasonHighlightBlock"] = { link = "LazyButtonActive" },
  ["MasonMutedBlockBold"] = { link = "MasonHighlight" },
  ["MasonMutedBlock"] = { link = "MasonMuted" },
  ["NERDTreeExecFile"] = { link = "String" },
  ["NERDTreeHelp"] = { link = "Comment" },
  ["TelescopeMatching"] = { link = "Special" },
  ["TelescopePreviewBorder"] = { link = "TelescopeBorder" },
  ["TelescopePreviewLine"] = { link = "TelescopeSelection" },
  ["TelescopePreviewTitle"] = { link = "TelescopeTitle" },
  ["TelescopePromptCounter"] = { link = "TelescopeBorder" },
  ["TelescopePromptPrefix"] = { link = "TelescopeTitle" },
  ["TelescopePromptTitle"] = { link = "TelescopeTitle" },
  ["TelescopeResultsBorder"] = { link = "TelescopeBorder" },
  ["TelescopeResultsFileIcon"] = { link = "Special" },
  ["TelescopeResultsTitle"] = { link = "TelescopeTitle" },
  ["TelescopeSelection"] = { link = "Visual" },
  ["BlinkCmpDoc"] = { fg = p.fg0, bg = p.panel, sp = "NONE" },
  ["BlinkCmpDocBorder"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["BlinkCmpKind"] = { fg = p.type, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindClass"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["BlinkCmpKindColor"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindConstant"] = { fg = p.constant, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindConstructor"] = { fg = p.constructor, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindCopilot"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindEnum"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["BlinkCmpKindEnumMember"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindEvent"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindField"] = { fg = p.field, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindFile"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindFolder"] = { fg = p.directory, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindFunction"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindInterface"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["BlinkCmpKindKeyword"] = { fg = p.keyword, bg = "NONE", sp = "NONE", bold = true },
  ["BlinkCmpKindMethod"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindModule"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindOperator"] = { fg = p.operator, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindProperty"] = { fg = p.property, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindReference"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindSnippet"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindStruct"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["BlinkCmpKindText"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindTypeParameter"] = { fg = p.type, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindUnit"] = { fg = p.type, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindValue"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["BlinkCmpKindVariable"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["BlinkCmpLabel"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["BlinkCmpLabelDeprecated"] = { fg = p.muted, bg = "NONE", sp = "NONE", strikethrough = true },
  ["BlinkCmpLabelDescription"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["BlinkCmpLabelDetail"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["BlinkCmpLabelMatch"] = { fg = p.fg1, bg = "NONE", sp = "NONE", bold = true },
  ["BlinkCmpMenu"] = { fg = p.fg0, bg = p.panel, sp = "NONE" },
  ["BlinkCmpMenuBorder"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["BlinkCmpMenuSelection"] = { fg = p.fg1, bg = p.rename, sp = "NONE", bold = true },
  ["BlinkCmpScrollBarGutter"] = { fg = "NONE", bg = p.muted, sp = "NONE" },
  ["BlinkCmpScrollBarThumb"] = { fg = "NONE", bg = p.fg0, sp = "NONE" },
  ["BlinkCmpSignatureHelpBorder"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["CmpItemAbbr"] = { link = "BlinkCmpLabel" },
  ["CmpItemAbbrDeprecated"] = { link = "BlinkCmpLabelDeprecated" },
  ["CmpItemAbbrMatch"] = { link = "BlinkCmpLabelMatch" },
  ["CmpItemAbbrMatchFuzzy"] = { link = "BlinkCmpKindSnippet" },
  ["CmpItemKind"] = { link = "BlinkCmpKind" },
  ["CmpItemKindClass"] = { link = "BlinkCmpKindClass" },
  ["CmpItemKindColor"] = { link = "BlinkCmpKindColor" },
  ["CmpItemKindConstant"] = { link = "BlinkCmpKindConstant" },
  ["CmpItemKindConstructor"] = { link = "BlinkCmpKindConstructor" },
  ["CmpItemKindCopilot"] = { link = "BlinkCmpKindCopilot" },
  ["CmpItemKindEnum"] = { link = "BlinkCmpKindEnum" },
  ["CmpItemKindEnumMember"] = { link = "BlinkCmpKindEnumMember" },
  ["CmpItemKindEvent"] = { link = "BlinkCmpKindEvent" },
  ["CmpItemKindField"] = { link = "BlinkCmpKindField" },
  ["CmpItemKindFile"] = { link = "BlinkCmpKindFile" },
  ["CmpItemKindFolder"] = { link = "BlinkCmpKindFolder" },
  ["CmpItemKindFunction"] = { link = "BlinkCmpKindFunction" },
  ["CmpItemKindInterface"] = { link = "BlinkCmpKindInterface" },
  ["CmpItemKindKeyword"] = { link = "BlinkCmpKindKeyword" },
  ["CmpItemKindMenu"] = { link = "BlinkCmpLabelDescription" },
  ["CmpItemKindMethod"] = { link = "BlinkCmpKindMethod" },
  ["CmpItemKindModule"] = { link = "BlinkCmpKindModule" },
  ["CmpItemKindOperator"] = { link = "BlinkCmpKindOperator" },
  ["CmpItemKindProperty"] = { link = "BlinkCmpKindProperty" },
  ["CmpItemKindReference"] = { link = "BlinkCmpKindReference" },
  ["CmpItemKindSnippet"] = { link = "BlinkCmpKindSnippet" },
  ["CmpItemKindStruct"] = { link = "BlinkCmpKindStruct" },
  ["CmpItemKindText"] = { link = "BlinkCmpKindText" },
  ["CmpItemKindTypeParameter"] = { link = "BlinkCmpKindTypeParameter" },
  ["CmpItemKindUnit"] = { link = "BlinkCmpKindUnit" },
  ["CmpItemKindValue"] = { link = "BlinkCmpKindValue" },
  ["CmpItemKindVariable"] = { link = "BlinkCmpKindVariable" },
  ["CmpItemMenu"] = { link = "BlinkCmpLabelDescription" },
  ["AlphaButtons"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["AlphaFooter"] = { fg = p.modified, bg = "NONE", sp = "NONE", italic = true },
  ["AlphaHeader"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["AlphaHeaderLabel"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["AlphaShortcut"] = { fg = p.func, bg = "NONE", sp = "NONE", bold = true },
  ["DapBreakpoint"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["DapBreakpointCondition"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["DapBreakpointRejected"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["DapLogPoint"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["DapStopped"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIBreakpointsCurrentLine"] = { fg = p.success, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIBreakpointsDisabledLine"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["DapUIBreakpointsInfo"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIBreakpointsPath"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["DapUIDecoration"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIFloatBorder"] = { link = "FloatBorder" },
  ["DapUILineNumber"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["DapUIModifiedValue"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIPlayPause"] = { fg = p.success, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIPlayPauseNC"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["DapUIRestart"] = { fg = p.success, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIRestartNC"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["DapUIScope"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUISource"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["DapUIStepBack"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStepBackNC"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStepInto"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStepIntoNC"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStepOut"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStepOutNC"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStepOver"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStepOverNC"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DapUIStop"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIStopNC"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["DapUIStoppedThread"] = { fg = p.info, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIThread"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["DapUIType"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["DapUIUnavailable"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["DapUIUnavailableNC"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["DapUIValue"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["DapUIVariable"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["DapUIWatchesEmpty"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["DapUIWatchesError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["DapUIWatchesValue"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["DapUIWinSelect"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["DashboardCenter"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["DashboardDesc"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["DashboardFiles"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["DashboardFooter"] = { fg = p.modified, bg = "NONE", sp = "NONE", italic = true },
  ["DashboardHeader"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["DashboardIcon"] = { fg = p.warning, bg = "NONE", sp = "NONE", bold = true },
  ["DashboardKey"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["DashboardMruTitle"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["DashboardProjectTitle"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["DashboardShortCut"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewDim1"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["DiffviewFilePanelConflicts"] = { fg = p.conflict, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewFilePanelCounter"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["DiffviewFilePanelDeletions"] = { fg = p.deleted, bg = "NONE", sp = "NONE" },
  ["DiffviewFilePanelFileName"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["DiffviewFilePanelInsertions"] = { fg = p.added, bg = "NONE", sp = "NONE" },
  ["DiffviewFilePanelPath"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["DiffviewFilePanelRootPath"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewFilePanelSelected"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewFilePanelTitle"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewFolderName"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewFolderSign"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["DiffviewHash"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["DiffviewNormal"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["DiffviewPrimary"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["DiffviewReference"] = { fg = p.base17, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewReflogSelector"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["DiffviewSecondary"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusAdded"] = { fg = p.added, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusBroken"] = { fg = p.deleted, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusCopied"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusDeleted"] = { fg = p.deleted, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusIgnored"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusModified"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusRenamed"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusTypeChange"] = { fg = p.base1D, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusUnknown"] = { fg = p.deleted, bg = "NONE", sp = "NONE" },
  ["DiffviewStatusUnmerged"] = { fg = p.conflict, bg = "NONE", sp = "NONE", bold = true },
  ["DiffviewStatusUntracked"] = { fg = p.hint, bg = "NONE", sp = "NONE" },
  ["DiffviewWinSeparator"] = { fg = p.bg2, bg = p.bg0, sp = "NONE" },
  ["DropBarIconUISeparator"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["DropBarMenuHoverEntry"] = { fg = p.fg1, bg = p.bg2, sp = "NONE" },
  ["DropBarMenuHoverIcon"] = { fg = p.bg0, bg = p.modified, sp = "NONE" },
  ["DropBarMenuHoverSymbol"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["FidgetTask"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["FidgetTitle"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["GitSignsAddInline"] = { fg = p.bg0, bg = p.added, sp = "NONE", bold = true },
  ["GitSignsAddPreview"] = { fg = p.bg0, bg = p.added, sp = "NONE" },
  ["GitSignsChangeInline"] = { fg = p.bg0, bg = p.modified, sp = "NONE", bold = true },
  ["GitSignsCurrentLineBlame"] = { fg = p.muted, bg = "NONE", sp = "NONE", italic = true },
  ["GitSignsDeleteInline"] = { fg = p.bg0, bg = p.deleted, sp = "NONE", bold = true },
  ["GitSignsDeletePreview"] = { fg = p.bg0, bg = p.deleted, sp = "NONE" },
  ["HarpoonBorder"] = { link = "FloatBorder" },
  ["HarpoonWindow"] = { link = "Normal" },
  ["NeogitBranch"] = { fg = p.warning, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeAdded"] = { fg = p.added, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeBothModified"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeCopied"] = { fg = p.info, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeDeleted"] = { fg = p.deleted, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeModified"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeNewFile"] = { fg = p.added, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeRenamed"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitChangeUpdated"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitCommitViewHeader"] = { fg = p.fg0, bg = p.bg1, sp = "NONE", bold = true },
  ["NeogitDiffAdd"] = { fg = p.added, bg = p.bg1, sp = "NONE" },
  ["NeogitDiffAddHighlight"] = { fg = p.bg0, bg = p.added, sp = "NONE" },
  ["NeogitDiffContext"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["NeogitDiffContextHighlight"] = { fg = p.fg1, bg = p.bg1, sp = "NONE" },
  ["NeogitDiffDelete"] = { fg = p.deleted, bg = p.bg1, sp = "NONE" },
  ["NeogitDiffDeleteHighlight"] = { fg = p.bg0, bg = p.deleted, sp = "NONE" },
  ["NeogitDiffHeader"] = { fg = p.link, bg = p.bg0, sp = "NONE", bold = true },
  ["NeogitDiffHeaderHighlight"] = { fg = p.modified, bg = p.bg0, sp = "NONE", bold = true },
  ["NeogitFilePath"] = { fg = p.link, bg = "NONE", sp = "NONE", italic = true },
  ["NeogitGraphBlue"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["NeogitGraphBoldBlue"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldCyan"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldGray"] = { fg = p.muted, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldGreen"] = { fg = p.statement, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldOrange"] = { fg = p.warning, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldPurple"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldRed"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldWhite"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphBoldYellow"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitGraphCyan"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["NeogitGraphGray"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeogitGraphGreen"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["NeogitGraphOrange"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["NeogitGraphPurple"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeogitGraphRed"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["NeogitGraphWhite"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["NeogitGraphYellow"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeogitHunkHeader"] = { fg = p.muted, bg = p.bg1, sp = "NONE" },
  ["NeogitHunkHeaderHighlight"] = { fg = p.fg0, bg = p.bg2, sp = "NONE", bold = true },
  ["NeogitNotificationError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["NeogitNotificationInfo"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["NeogitNotificationWarning"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["NeogitObjectId"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeogitPopupActionKey"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeogitPopupBold"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitPopupConfigKey"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeogitPopupOptionKey"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeogitPopupSwitchKey"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeogitRebaseDone"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeogitRecentcommits"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitRebasing"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitRemote"] = { fg = p.statement, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitSectionHeader"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitStagedchanges"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitStash"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeogitStashes"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitTagName"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeogitUnmergedInto"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["NeogitUnmergedchanges"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitUnpulledFrom"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["NeogitUnpulledchanges"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitUnpushedTo"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitUnstagedchanges"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeogitUntrackedfiles"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["TreesitterContext"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["TreesitterContextBottom"] = { fg = "NONE", bg = "NONE", sp = p.bg1, underline = true },
  ["TreesitterContextLineNumber"] = { fg = p.modified, bg = p.bg0, sp = "NONE" },
  ["MasonError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["MasonHeader"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["MasonHeading"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["MasonHighlightBlockBoldSecondary"] = { fg = p.bg0, bg = p.warning, sp = "NONE", bold = true },
  ["MasonHighlightBlockSecondary"] = { fg = p.bg0, bg = p.warning, sp = "NONE" },
  ["MasonHighlight"] = { fg = p.statement, bg = p.bg0, sp = "NONE" },
  ["MasonHighlightSecondary"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["MasonMuted"] = { fg = p.modified, bg = p.bg1, sp = "NONE" },
  ["MasonWarning"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["NoiceCmdline"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["NoiceCmdlineIcon"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["NoiceCmdlineIconSearch"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NoiceCmdlinePopupBorder"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["NoiceCmdlinePopupBorderSearch"] = { fg = p.search, bg = p.panel, sp = "NONE" },
  ["NoiceConfirmBorder"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["NoiceFormatProgressDone"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["NoiceFormatProgressTodo"] = { fg = p.muted, bg = p.bg0, sp = "NONE" },
  ["NoiceMini"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeoTreeDirectoryIcon"] = { fg = p.directory, bg = "NONE", sp = "NONE" },
  ["NeoTreeDirectoryName"] = { fg = p.directory, bg = "NONE", sp = "NONE" },
  ["NeoTreeDimText"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeoTreeExpander"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeoTreeFileNameOpened"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeoTreeFilterTerm"] = { fg = p.search, bg = "NONE", sp = "NONE", bold = true },
  ["NeoTreeFloatBorder"] = { link = "FloatBorder" },
  ["NeoTreeFloatTitle"] = { fg = p.link, bg = p.panel, sp = "NONE", bold = true },
  ["NeoTreeGitAdded"] = { fg = p.added, bg = "NONE", sp = "NONE" },
  ["NeoTreeGitConflict"] = { fg = p.conflict, bg = "NONE", sp = "NONE", bold = true },
  ["NeoTreeGitDeleted"] = { fg = p.deleted, bg = "NONE", sp = "NONE" },
  ["NeoTreeGitIgnored"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeoTreeGitModified"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeoTreeGitStaged"] = { fg = p.base15, bg = "NONE", sp = "NONE" },
  ["NeoTreeGitUnstaged"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["NeoTreeGitUntracked"] = { fg = p.hint, bg = "NONE", sp = "NONE" },
  ["NeoTreeIndentMarker"] = { fg = p.bg2, bg = "NONE", sp = "NONE" },
  ["NeoTreeNormal"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["NeoTreeNormalNC"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["NeoTreeRootName"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["NeoTreeStatusLineNC"] = { fg = p.muted, bg = p.bg0, sp = "NONE", bold = true },
  ["NeoTreeSymbolicLinkTarget"] = { fg = p.modified, bg = "NONE", sp = "NONE", italic = true },
  ["NeoTreeTitleBar"] = { fg = p.fg0, bg = p.bg0, sp = "NONE", bold = true },
  ["NeoTreeModified"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeoTreeTabActive"] = { fg = p.fg0, bg = p.bg0, sp = "NONE", bold = true },
  ["NeoTreeTabInactive"] = { fg = p.muted, bg = p.bg0, sp = "NONE" },
  ["NeoTreeTabSeparatorActive"] = { fg = p.bg2, bg = p.bg0, sp = "NONE" },
  ["NeoTreeTabSeparatorInactive"] = { fg = p.bg2, bg = p.bg0, sp = "NONE" },
  ["NeoTreeVertSplit"] = { fg = p.bg2, bg = p.bg0, sp = "NONE" },
  ["NeoTreeWinSeparator"] = { fg = p.bg2, bg = p.bg0, sp = "NONE" },
  ["NeotestAdapterName"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeotestDir"] = { fg = p.directory, bg = "NONE", sp = "NONE", bold = true },
  ["NeotestExpandMarker"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeotestFailed"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["NeotestFile"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["NeotestFocused"] = { fg = p.fg1, bg = "NONE", sp = p.fg0, bold = true, underline = true },
  ["NeotestIndent"] = { fg = p.bg2, bg = "NONE", sp = "NONE" },
  ["NeotestMarked"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["NeotestNamespace"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NeotestPassed"] = { fg = p.success, bg = "NONE", sp = "NONE", bold = true },
  ["NeotestRunning"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["NeotestSkipped"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["NeotestTarget"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["NeotestTest"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["NeotestUnknown"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NeotestWinSelect"] = { fg = p.info, bg = "NONE", sp = "NONE", bold = true },
  ["NvimTreeEmptyFolderName"] = { fg = p.directory, bg = "NONE", sp = "NONE" },
  ["NvimTreeFolderIcon"] = { fg = p.directory, bg = "NONE", sp = "NONE" },
  ["NvimTreeFolderName"] = { fg = p.directory, bg = "NONE", sp = "NONE" },
  ["NvimTreeGitDeleted"] = { fg = p.deleted, bg = "NONE", sp = "NONE" },
  ["NvimTreeGitDirty"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NvimTreeGitNew"] = { fg = p.hint, bg = "NONE", sp = "NONE" },
  ["NvimTreeImageFile"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["NvimTreeIndentMarker"] = { fg = p.bg2, bg = "NONE", sp = "NONE" },
  ["NvimTreeNormal"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["NvimTreeOpenedFile"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["NvimTreeOpenedFolderName"] = { fg = p.directory, bg = "NONE", sp = "NONE", bold = true },
  ["NvimTreeRootFolder"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["NvimTreeSpecialFile"] = { fg = p.modified, bg = "NONE", sp = "NONE", underline = true },
  ["NvimTreeStatuslineNc"] = { fg = p.muted, bg = p.bg0, sp = "NONE", bold = true },
  ["NvimTreeSymlink"] = { fg = p.modified, bg = "NONE", sp = "NONE", italic = true },
  ["NvimTreeWinSeparator"] = { fg = p.bg2, bg = p.bg0, sp = "NONE" },
  ["NotifyBackground"] = { link = "Normal" },
  ["NotifyDEBUGBorder"] = { link = "SnacksNotifierBorderDebug" },
  ["NotifyDEBUGIcon"] = { link = "SnacksNotifierIconDebug" },
  ["NotifyDEBUGTitle"] = { link = "SnacksNotifierTitleDebug" },
  ["NotifyERRORBorder"] = { link = "SnacksNotifierBorderError" },
  ["NotifyERRORIcon"] = { link = "SnacksNotifierIconError" },
  ["NotifyERRORTitle"] = { link = "SnacksNotifierTitleError" },
  ["NotifyINFOBorder"] = { link = "SnacksNotifierBorderInfo" },
  ["NotifyINFOIcon"] = { link = "SnacksNotifierIconInfo" },
  ["NotifyINFOTitle"] = { link = "SnacksNotifierTitleInfo" },
  ["NotifyTRACEBorder"] = { link = "SnacksNotifierBorderTrace" },
  ["NotifyTRACEIcon"] = { link = "SnacksNotifierIconTrace" },
  ["NotifyTRACETitle"] = { link = "SnacksNotifierTitleTrace" },
  ["NotifyWARNBorder"] = { link = "SnacksNotifierBorderWarn" },
  ["NotifyWARNIcon"] = { link = "SnacksNotifierIconWarn" },
  ["NotifyWARNTitle"] = { link = "SnacksNotifierTitleWarn" },
  ["ScrollbarCursor"] = { fg = p.bg0, bg = "NONE", sp = "NONE" },
  ["ScrollbarCursorHandle"] = { fg = p.bg0, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarError"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["ScrollbarErrorHandle"] = { fg = p.warning, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarGitAdd"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["ScrollbarGitAddHandle"] = { fg = p.link, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarGitChange"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["ScrollbarGitChangeHandle"] = { fg = p.warning, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarGitDelete"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["ScrollbarGitDeleteHandle"] = { fg = p.error, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarHandle"] = { fg = "NONE", bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarHint"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["ScrollbarHintHandle"] = { fg = p.link, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarInfo"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["ScrollbarInfoHandle"] = { fg = p.link, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarMisc"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["ScrollbarMiscHandle"] = { fg = p.warning, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarSearch"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["ScrollbarSearchHandle"] = { fg = p.modified, bg = p.bg1, sp = "NONE", blend = 0 },
  ["ScrollbarWarn"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["ScrollbarWarnHandle"] = { fg = p.error, bg = p.bg1, sp = "NONE", blend = 0 },
  ["SyntasticErrorSign"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["SyntasticWarningSign"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["TelescopeBorder"] = { fg = p.border, bg = p.bg_alt, sp = "NONE" },
  ["TelescopeMultiIcon"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeMultiSelection"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeNormal"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewBlock"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewCharDev"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewDate"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewDirectory"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewExecute"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewGroup"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewHyphen"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewLink"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewMatch"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewMessageFillchar"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewMessage"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewNormal"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewPipe"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewRead"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewSize"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewSocket"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewSticky"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewUser"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePreviewWrite"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopePromptBorder"] = { fg = p.border, bg = p.bg_alt, sp = "NONE" },
  ["TelescopePromptNormal"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsClass"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsComment"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsConstant"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsDiffUntracked"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsField"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsFunction"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsIdentifier"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsLineNr"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsMethod"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsNormal"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsNumber"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsOperator"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsSpecialComment"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsStruct"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeResultsVariable"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["TelescopeSelectionCaret"] = { fg = p.text_bright, bg = p.base16, sp = "NONE" },
  ["TelescopeTitle"] = { fg = p.link, bg = p.bg_alt, sp = "NONE" },
  ["TroubleCount"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["TroubleNormal"] = { link = "Normal" },
  ["TroubleNormalNC"] = { fg = p.muted, bg = p.bg0, sp = "NONE" },
  ["TroubleText"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["WhichKeyBorder"] = { fg = "NONE", bg = p.bg0, sp = "NONE" },
  ["WhichKeyDesc"] = { fg = p.link, bg = p.bg0, sp = "NONE" },
  ["WhichKeyFloat"] = { fg = "NONE", bg = p.bg0, sp = "NONE" },
  ["WhichKeyGroup"] = { fg = "NONE", bg = p.bg0, sp = "NONE" },
  ["WhichKey"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["WhichKeySeparator"] = { fg = p.modified, bg = p.bg0, sp = "NONE" },
  ["WhichKeyValue"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["AerialGuide"] = { fg = p.bg2, bg = "NONE", sp = "NONE" },
  ["AerialLine"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["FlashBackdrop"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["FlashCurrent"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["FlashLabel"] = { fg = p.info, bg = p.bg0, sp = "NONE", bold = true },
  ["FlashMatch"] = { fg = p.fg0, bg = "NONE", sp = "NONE", underline = true },
  ["HopNextKey"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true, underline = true },
  ["HopNextKey1"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["HopNextKey2"] = { fg = p.statement, bg = "NONE", sp = "NONE", bold = true, italic = true },
  ["HopUnmatched"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["LeapBackdrop"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["LeapLabel"] = { fg = p.bg0, bg = p.func, sp = "NONE", bold = true, nocombine = true },
  ["LeapMatch"] = { fg = p.modified, bg = "NONE", sp = p.modified, bold = true, underline = true, nocombine = true },
  ["NavicIconsArray"] = { fg = p.type, bg = "NONE", sp = "NONE" },
  ["NavicIconsBoolean"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["NavicIconsClass"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["NavicIconsConstant"] = { fg = p.constant, bg = "NONE", sp = "NONE" },
  ["NavicIconsConstructor"] = { fg = p.constructor, bg = "NONE", sp = "NONE" },
  ["NavicIconsEnum"] = { fg = p.type, bg = "NONE", sp = "NONE" },
  ["NavicIconsEnumMember"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["NavicIconsField"] = { fg = p.field, bg = "NONE", sp = "NONE" },
  ["NavicIconsFile"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["NavicIconsFunction"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["NavicIconsInterface"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["NavicIconsMethod"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["NavicIconsModule"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["NavicIconsNamespace"] = { fg = p.namespace, bg = "NONE", sp = "NONE" },
  ["NavicIconsNumber"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["NavicIconsObject"] = { fg = p.type, bg = "NONE", sp = "NONE" },
  ["NavicIconsOperator"] = { fg = p.operator, bg = "NONE", sp = "NONE" },
  ["NavicIconsPackage"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["NavicIconsProperty"] = { fg = p.property, bg = "NONE", sp = "NONE" },
  ["NavicIconsString"] = { fg = p.string, bg = "NONE", sp = "NONE" },
  ["NavicIconsStruct"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["NavicIconsTypeParameter"] = { fg = p.type, bg = "NONE", sp = "NONE" },
  ["NavicIconsVariable"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["NavicSeparator"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["NavicText"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["RenderMarkdownBullet"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["RenderMarkdownCode"] = { fg = "NONE", bg = p.bg1, sp = "NONE" },
  ["RenderMarkdownCodeInline"] = { fg = "NONE", bg = p.bg1, sp = "NONE" },
  ["RenderMarkdownError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["RenderMarkdownH1"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["RenderMarkdownH2"] = { fg = p.warning, bg = "NONE", sp = "NONE", bold = true },
  ["RenderMarkdownH3"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["RenderMarkdownH4"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["RenderMarkdownH5"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["RenderMarkdownH6"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["RenderMarkdownHint"] = { fg = p.hint, bg = "NONE", sp = "NONE" },
  ["RenderMarkdownInfo"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["RenderMarkdownSuccess"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["RenderMarkdownTableHead"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["RenderMarkdownTableRow"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["RenderMarkdownWarn"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["FocusedSymbol"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["OutlineCurrent"] = { fg = p.modified, bg = "NONE", sp = "NONE", bold = true },
  ["IlluminatedWordRead"] = { fg = "NONE", bg = p.bg1, sp = "NONE" },
  ["IlluminatedWordText"] = { fg = "NONE", bg = p.bg1, sp = "NONE" },
  ["IlluminatedWordWrite"] = { fg = "NONE", bg = p.bg1, sp = "NONE", bold = true },
  ["UfoFoldedEllipsis"] = { fg = p.bg0, bg = p.link, sp = "NONE", bold = true },
  ["UfoFoldedFg"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["RainbowDelimiterBlue"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["RainbowDelimiterCyan"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["RainbowDelimiterGreen"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["RainbowDelimiterOrange"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["RainbowDelimiterRed"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["RainbowDelimiterViolet"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["RainbowDelimiterYellow"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["MiniAnimateCursor"] = { fg = "NONE", bg = "NONE", sp = "NONE", reverse = true, nocombine = true },
  ["MiniAnimateNormalFloat"] = { fg = p.fg0, bg = p.panel, sp = "NONE" },
  ["MiniClueBorder"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["MiniClueDescGroup"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["MiniClueDescSingle"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["MiniClueNextKey"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["MiniClueNextKeyWithPostkeys"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["MiniClueSeparator"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["MiniClueTitle"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["MiniCompletionActiveParameter"] = { fg = "NONE", bg = "NONE", sp = p.fg0, underline = true },
  ["MiniCursorword"] = { fg = "NONE", bg = "NONE", sp = p.fg0, underline = true },
  ["MiniCursorwordCurrent"] = { fg = "NONE", bg = "NONE", sp = p.fg0, underline = true },
  ["MiniDepsChangeAdded"] = { fg = p.added, bg = "NONE", sp = "NONE" },
  ["MiniDepsChangeRemoved"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["MiniDepsHint"] = { fg = p.hint, bg = "NONE", sp = "NONE" },
  ["MiniDepsInfo"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["MiniDepsMsgBreaking"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["MiniDepsPlaceholder"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["MiniDepsTitle"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["MiniDepsTitleError"] = { fg = p.bg0, bg = p.error, sp = "NONE", bold = true },
  ["MiniDepsTitleSame"] = { fg = p.bg0, bg = p.modified, sp = "NONE", bold = true },
  ["MiniDepsTitleUpdate"] = { fg = p.bg0, bg = p.info, sp = "NONE", bold = true },
  ["MiniDiffOverAdd"] = { fg = p.bg0, bg = p.added, sp = "NONE" },
  ["MiniDiffOverChange"] = { fg = p.bg0, bg = p.modified, sp = "NONE", bold = true },
  ["MiniDiffOverContext"] = { fg = p.bg0, bg = p.warning, sp = "NONE" },
  ["MiniDiffOverDelete"] = { fg = p.bg0, bg = p.error, sp = "NONE", bold = true },
  ["MiniDiffSignAdd"] = { fg = p.added, bg = "NONE", sp = "NONE" },
  ["MiniDiffSignChange"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["MiniDiffSignDelete"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["MiniFilesBorder"] = { link = "FloatBorder" },
  ["MiniFilesBorderModified"] = { fg = p.modified, bg = p.bg0, sp = "NONE", bold = true },
  ["MiniFilesCursorLine"] = { fg = "NONE", bg = p.bg1, sp = "NONE" },
  ["MiniFilesDirectory"] = { fg = p.directory, bg = p.bg0, sp = "NONE" },
  ["MiniFilesFile"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["MiniFilesNormal"] = { link = "Normal" },
  ["MiniFilesTitle"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["MiniFilesTitleFocused"] = { fg = p.fg0, bg = p.bg0, sp = "NONE", bold = true },
  ["MiniHipatternsFixme"] = { fg = p.bg0, bg = p.error, sp = "NONE", bold = true },
  ["MiniHipatternsHack"] = { fg = p.bg0, bg = p.modified, sp = "NONE", bold = true },
  ["MiniHipatternsNote"] = { fg = p.bg0, bg = p.link, sp = "NONE", bold = true },
  ["MiniHipatternsTodo"] = { fg = p.bg0, bg = p.statement, sp = "NONE", bold = true },
  ["MiniIconsAzure"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["MiniIconsBlue"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["MiniIconsCyan"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["MiniIconsGreen"] = { fg = p.statement, bg = "NONE", sp = "NONE" },
  ["MiniIconsGrey"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["MiniIconsOrange"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["MiniIconsPurple"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["MiniIconsRed"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["MiniIconsYellow"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["MiniIndentscopeSymbol"] = { fg = p.bg2, bg = "NONE", sp = "NONE", nocombine = true },
  ["MiniJump"] = { fg = p.fg0, bg = p.modified, sp = "NONE" },
  ["MiniJump2dDim"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["MiniJump2dSpot"] = { fg = p.warning, bg = p.bg0, sp = "NONE", bold = true, underline = true },
  ["MiniJump2dSpotAhead"] = { fg = p.statement, bg = p.bg0, sp = "NONE" },
  ["MiniJump2dSpotUnique"] = { fg = p.link, bg = p.bg0, sp = "NONE", bold = true },
  ["MiniMapNormal"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["MiniMapSymbolCount"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["MiniMapSymbolLine"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["MiniMapSymbolView"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["MiniNotifyBorder"] = { link = "FloatBorder" },
  ["MiniNotifyNormal"] = { link = "Normal" },
  ["MiniNotifyTitle"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["MiniOperatorsExchangeFrom"] = { fg = p.fg1, bg = p.error, sp = "NONE", bold = true },
  ["MiniPickBorder"] = { link = "FloatBorder" },
  ["MiniPickBorderBusy"] = { fg = p.border, bg = p.panel, sp = "NONE", bold = true },
  ["MiniPickBorderText"] = { fg = p.modified, bg = p.bg0, sp = "NONE" },
  ["MiniPickHeader"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["MiniPickIconDirectory"] = { fg = p.directory, bg = p.bg0, sp = "NONE" },
  ["MiniPickIconFile"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["MiniPickMatchCurrent"] = { fg = p.fg1, bg = p.bg1, sp = "NONE", bold = true },
  ["MiniPickMatchMarked"] = { fg = p.fg1, bg = p.bg2, sp = "NONE" },
  ["MiniPickMatchRanges"] = { fg = p.match, bg = "NONE", sp = "NONE", bold = true },
  ["MiniPickNormal"] = { link = "Normal" },
  ["MiniPickPreviewLine"] = { fg = "NONE", bg = p.bg1, sp = "NONE" },
  ["MiniPickPreviewRegion"] = { fg = p.fg1, bg = p.error, sp = "NONE", bold = true },
  ["MiniPickPrompt"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["MiniPickPromptCaret"] = { fg = p.warning, bg = p.bg0, sp = "NONE" },
  ["MiniPickPromptPrefix"] = { fg = p.warning, bg = p.bg0, sp = "NONE" },
  ["MiniStarterCurrent"] = { fg = "NONE", bg = "NONE", sp = "NONE" },
  ["MiniStarterFooter"] = { fg = p.modified, bg = "NONE", sp = "NONE", italic = true },
  ["MiniStarterHeader"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["MiniStarterInactive"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["MiniStarterItem"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["MiniStarterItemBullet"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["MiniStarterItemPrefix"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["MiniStarterQuery"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["MiniStarterSection"] = { fg = p.warning, bg = "NONE", sp = "NONE", bold = true },
  ["MiniStatuslineDevinfo"] = { fg = p.muted, bg = p.panel, sp = "NONE" },
  ["MiniStatuslineFileinfo"] = { fg = p.muted, bg = p.panel, sp = "NONE" },
  ["MiniStatuslineFilename"] = { fg = p.fg0, bg = p.panel, sp = "NONE" },
  ["MiniStatuslineInactive"] = { fg = p.muted, bg = p.panel_deep, sp = "NONE" },
  ["MiniStatuslineModeCommand"] = { fg = p.bg0, bg = p.warning, sp = "NONE", bold = true },
  ["MiniStatuslineModeInsert"] = { fg = p.bg0, bg = p.success, sp = "NONE", bold = true },
  ["MiniStatuslineModeNormal"] = { fg = p.bg0, bg = p.link, sp = "NONE", bold = true },
  ["MiniStatuslineModeOther"] = { fg = p.bg0, bg = p.statement, sp = "NONE", bold = true },
  ["MiniStatuslineModeReplace"] = { fg = p.bg0, bg = p.error, sp = "NONE", bold = true },
  ["MiniStatuslineModeVisual"] = { fg = p.bg0, bg = p.modified, sp = "NONE", bold = true },
  ["MiniSurround"] = { fg = p.fg0, bg = p.modified, sp = "NONE" },
  ["MiniTablineCurrent"] = { fg = p.fg0, bg = p.bg0, sp = p.error, bold = true, italic = true, underline = true },
  ["MiniTablineFill"] = { fg = "NONE", bg = p.bg0, sp = "NONE" },
  ["MiniTablineHidden"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["MiniTablineModifiedCurrent"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true, italic = true },
  ["MiniTablineModifiedHidden"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["MiniTablineModifiedVisible"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["MiniTablineTabpagesection"] = { fg = p.muted, bg = p.bg0, sp = "NONE" },
  ["MiniTablineVisible"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["MiniTestEmphasis"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["MiniTestFail"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["MiniTestPass"] = { fg = p.success, bg = "NONE", sp = "NONE", bold = true },
  ["MiniTrailspace"] = { fg = "NONE", bg = p.error, sp = "NONE" },
  ["SnacksBackdrop"] = { fg = "NONE", bg = p.bg1, sp = "NONE", blend = 80 },
  ["SnacksDashboardDesc"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["SnacksDashboardDir"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["SnacksDashboardFile"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["SnacksDashboardFooter"] = { fg = p.modified, bg = "NONE", sp = "NONE", italic = true },
  ["SnacksDashboardHeader"] = { fg = p.link, bg = "NONE", sp = "NONE", bold = true },
  ["SnacksDashboardIcon"] = { fg = p.warning, bg = "NONE", sp = "NONE", bold = true },
  ["SnacksDashboardKey"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["SnacksDashboardNormal"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["SnacksDashboardSpecial"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["SnacksDashboardTerminal"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["SnacksDashboardTitle"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["SnacksIndent"] = { fg = p.bg1, bg = "NONE", sp = "NONE" },
  ["SnacksIndentScope"] = { fg = p.bg2, bg = "NONE", sp = "NONE" },
  ["SnacksNormal"] = { link = "Normal" },
  ["SnacksNormalNC"] = { link = "Normal" },
  ["SnacksNotifierBorderDebug"] = { fg = p.modified, bg = p.panel, sp = "NONE" },
  ["SnacksNotifierBorderError"] = { fg = p.error, bg = p.panel, sp = "NONE" },
  ["SnacksNotifierBorderInfo"] = { fg = p.info, bg = p.panel, sp = "NONE" },
  ["SnacksNotifierBorderTrace"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["SnacksNotifierBorderWarn"] = { fg = p.warning, bg = p.panel, sp = "NONE" },
  ["SnacksNotifierDebug"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierFooterDebug"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierFooterError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierFooterInfo"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierFooterTrace"] = { fg = p.border, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierFooterWarn"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierIconDebug"] = { fg = p.modified, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierIconError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierIconInfo"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierIconTrace"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierIconWarn"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierInfo"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierTitleDebug"] = { fg = p.modified, bg = "NONE", sp = "NONE", italic = true },
  ["SnacksNotifierTitleError"] = { fg = p.error, bg = "NONE", sp = "NONE", italic = true },
  ["SnacksNotifierTitleInfo"] = { fg = p.info, bg = "NONE", sp = "NONE", italic = true },
  ["SnacksNotifierTitleTrace"] = { fg = p.fg0, bg = "NONE", sp = "NONE", italic = true },
  ["SnacksNotifierTitleWarn"] = { fg = p.warning, bg = "NONE", sp = "NONE", italic = true },
  ["SnacksNotifierTrace"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["SnacksNotifierWarn"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["SnacksPicker"] = { link = "Normal" },
  ["SnacksPickerBorder"] = { link = "FloatBorder" },
  ["SnacksPickerInput"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["SnacksPickerInputBorder"] = { fg = p.border, bg = p.panel, sp = "NONE" },
  ["SnacksPickerInputTitle"] = { fg = p.fg0, bg = p.error, sp = "NONE", bold = true },
  ["SnacksPickerListTitle"] = { fg = p.bg0, bg = p.modified, sp = "NONE", bold = true },
  ["SnacksPickerMatch"] = { fg = p.match, bg = "NONE", sp = "NONE", bold = true },
  ["SnacksPickerPreviewTitle"] = { fg = p.bg0, bg = p.link, sp = "NONE", bold = true },
  ["SnacksPickerPrompt"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["SnacksPickerSelected"] = { fg = p.fg1, bg = p.bg1, sp = "NONE", bold = true },
  ["SnacksPickerTitle"] = { fg = p.bg0, bg = p.modified, sp = "NONE", bold = true },
  ["SnacksWinBar"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
  ["SnacksWinBarNC"] = { fg = p.error, bg = "NONE", sp = "NONE", bold = true },
}
