local p = require("retro82.palette")

return {
  ["DiagnosticDeprecated"] = { fg = "NONE", bg = "NONE", sp = p.deprecated, strikethrough = true },
  ["DiagnosticError"] = { fg = p.error, bg = "NONE", sp = "NONE" },
  ["DiagnosticHintFloating"] = { fg = p.hint, bg = "NONE", sp = "NONE" },
  ["DiagnosticHint"] = { fg = p.hint, bg = "NONE", sp = "NONE" },
  ["DiagnosticInfo"] = { fg = p.info, bg = "NONE", sp = "NONE" },
  ["DiagnosticOk"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["DiagnosticSignError"] = { fg = p.error, bg = p.bg0, sp = "NONE" },
  ["DiagnosticSignHint"] = { fg = p.hint, bg = p.bg0, sp = "NONE" },
  ["DiagnosticSignInfo"] = { fg = p.info, bg = p.bg0, sp = "NONE" },
  ["DiagnosticSignWarn"] = { fg = p.warning, bg = p.bg0, sp = "NONE" },
  ["DiagnosticUnderlineError"] = { fg = "NONE", bg = "NONE", sp = p.error, undercurl = true },
  ["DiagnosticUnderlineHint"] = { fg = "NONE", bg = "NONE", sp = p.hint, undercurl = true },
  ["DiagnosticUnderlineInfo"] = { fg = "NONE", bg = "NONE", sp = p.info, undercurl = true },
  ["DiagnosticUnderlineOk"] = { fg = "NONE", bg = "NONE", sp = p.success, undercurl = true },
  ["DiagnosticUnderlineWarn"] = { fg = "NONE", bg = "NONE", sp = p.warning, undercurl = true },
  ["DiagnosticUnnecessary"] = { fg = p.comment, bg = "NONE", sp = "NONE", underline = true },
  ["DiagnosticVirtualTextError"] = { fg = p.error, bg = p.surface_alt, sp = "NONE", bold = true },
  ["DiagnosticVirtualTextHint"] = { fg = p.hint, bg = p.surface_alt, sp = "NONE" },
  ["DiagnosticVirtualTextInfo"] = { fg = p.info, bg = p.surface_alt, sp = "NONE" },
  ["DiagnosticVirtualTextWarn"] = { fg = p.warning, bg = p.surface_alt, sp = "NONE", bold = true },
  ["DiagnosticVirtualTextWarning"] = { fg = p.warning, bg = p.surface_alt, sp = "NONE" },
  ["DiagnosticWarn"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["DiagnosticWarningFloating"] = { fg = p.text, bg = "NONE", sp = "NONE" },
  ["DiagnosticWarning"] = { fg = p.warning, bg = "NONE", sp = "NONE" },
  ["DiagnosticErrorFloating"] = { link = "DiagnosticError" },
  ["DiagnosticFloatingError"] = { link = "DiagnosticError" },
  ["DiagnosticFloatingHint"] = { link = "DiagnosticHint" },
  ["DiagnosticFloatingInfo"] = { link = "DiagnosticInfo" },
  ["DiagnosticFloatingOk"] = { link = "DiagnosticOk" },
  ["DiagnosticFloatingWarn"] = { link = "DiagnosticWarn" },
  ["DiagnosticFloatingWarning"] = { link = "DiagnosticWarning" },
  ["DiagnosticSignOk"] = { link = "DiagnosticOk" },
  ["DiagnosticVirtualTextOk"] = { link = "DiagnosticOk" },
  ["LspCodeLens"] = { link = "Comment" },
  ["@lsp.type.comment"] = { link = "Comment" },
  ["@lsp.type.decorator"] = { fg = p.annotation, bg = "NONE", sp = "NONE" },
  ["@lsp.type.enumMember"] = { fg = p.constant, bg = "NONE", sp = "NONE" },
  ["@lsp.type.function"] = { link = "Function" },
  ["@lsp.type.method"] = { link = "Function" },
  ["@lsp.type.namespace"] = { link = "@module" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@variable.member" },
  ["@lsp.type.type"] = { link = "Type" },
  ["@lsp.type.variable"] = { link = "Identifier" },
  ["@lsp.mod.defaultLibrary"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["@lsp.type.namespace.lua"] = { link = "@module" },
  ["@lsp.type.parameter.lua"] = { link = "@variable.parameter" },
  ["@lsp.type.property.lua"] = { link = "@variable.member" },
  ["@lsp.type.variable.lua"] = {},
  ["@lsp.typemod.variable.defaultLibrary.lua"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.function.defaultLibrary.lua"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.method.defaultLibrary.lua"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.property.defaultLibrary.lua"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.function.builtin"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.function.defaultLibrary"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["LspBorderBG"] = { fg = p.border, bg = p.bg0, sp = "NONE" },
  ["LspInlayHint"] = { fg = p.base1E, bg = "NONE", sp = "NONE", italic = true },
  ["LspFloatWinNormal"] = { fg = p.text, bg = p.bg_alt, sp = "NONE" },
  ["LspReferenceRead"] = { fg = p.info, bg = "NONE", sp = p.info, bold = true, undercurl = true },
  ["LspReferenceText"] = { fg = p.text_bright, bg = p.selection, sp = p.info, bold = true, undercurl = true },
  ["LspReferenceWrite"] = { fg = p.warning, bg = "NONE", sp = p.warning, bold = true, undercurl = true },
  ["LspSignatureActiveParameter"] = { fg = "NONE", bg = "NONE", sp = p.text_bright, bold = true, italic = true, underline = true },
}
