local p = require("retro82.palette")

return {
  ["gitCommitBranch"] = { fg = p.link, bg = "NONE", sp = "NONE" },
  ["gitCommitSelectedFile"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["gitCommitSelectedType"] = { fg = p.success, bg = "NONE", sp = "NONE" },
  ["gitCommitUnmergedFile"] = { fg = p.conflict, bg = "NONE", sp = "NONE" },
  ["gitCommitUnmergedType"] = { fg = p.conflict, bg = "NONE", sp = "NONE" },
  ["htmlArg"] = { fg = p.property, bg = "NONE", sp = "NONE" },
  ["htmlBold"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true },
  ["htmlBoldItalic"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true, underline = true },
  ["htmlBoldUnderline"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true, underline = true },
  ["htmlBoldUnderlineItalic"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true, underline = true },
  ["htmlH1"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true },
  ["htmlItalic"] = { fg = "NONE", bg = "NONE", sp = "NONE", underline = true },
  ["htmlTag"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["htmlTagName"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["htmlUnderline"] = { fg = "NONE", bg = "NONE", sp = "NONE", underline = true },
  ["htmlUnderlineItalic"] = { fg = "NONE", bg = "NONE", sp = "NONE", underline = true },
  ["lessVariable"] = { fg = p.special, bg = "NONE", sp = "NONE" },
  ["gitCommitDiscardedFile"] = { link = "gitCommitUnmergedFile" },
  ["gitCommitDiscardedType"] = { link = "gitCommitUnmergedType" },
  ["gitCommitFile"] = { link = "Directory" },
  ["gitCommitUntrackedFile"] = { link = "gitCommitUnmergedFile" },
  ["helpExample"] = { link = "String" },
  ["helpHeadline"] = { link = "Title" },
  ["helpHyperTextEntry"] = { link = "Underlined" },
  ["helpHyperTextJump"] = { link = "Underlined" },
  ["helpSectionDelim"] = { link = "Comment" },
  ["helpURL"] = { link = "Underlined" },
  ["htmlEndTag"] = { link = "htmlTag" },
  ["htmlLink"] = { link = "Underlined" },
  ["javaScriptBraces"] = { link = "Delimiter" },
  ["javaScript"] = { link = "Normal" },
  ["lessVariableValue"] = { link = "Normal" },
  ["markdownCodeBlock"] = { link = "String" },
  ["markdownCodeDelimiter"] = { link = "NonText" },
  ["markdownHeadingRule"] = { link = "NonText" },
  ["markdownLinkDelimiter"] = { link = "Delimiter" },
  ["markdownURLDelimiter"] = { link = "Delimiter" },
  ["phpDefine"] = { link = "Statement" },
  ["phpHereDoc"] = { link = "String" },
  ["phpVarSelector"] = { link = "phpIdentifier" },
  ["rubyConstant"] = { link = "Constant" },
  ["rubyDefine"] = { link = "Statement" },
  ["rubyInstanceVariable"] = { link = "Number" },
  ["rubyLocalVariableOrMethod"] = { link = "Identifier" },
  ["shDerefVar"] = { link = "shDerefSimple" },
  ["vimContinue"] = { link = "Delimiter" },
  ["vimHiAttrib"] = { link = "Constant" },
  ["vimSetSep"] = { link = "Delimiter" },
  ["xmlAttrib"] = { link = "xmlTag" },
  ["xmlEndTag"] = { link = "xmlTag" },
  ["xmlEqual"] = { link = "xmlTag" },
  ["xmlString"] = { link = "xmlTagName" },
  ["markdownBold"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true },
  ["markdownItalic"] = { fg = "NONE", bg = "NONE", sp = "NONE", underline = true },
  ["mustacheMarker"] = { fg = p.special, bg = "NONE", sp = "NONE" },
  ["mustachePartial"] = { fg = p.special, bg = "NONE", sp = "NONE" },
  ["mustacheSection"] = { fg = "NONE", bg = "NONE", sp = "NONE", bold = true },
  ["mustacheVariable"] = { fg = p.identifier, bg = "NONE", sp = "NONE" },
  ["mustacheVariableUnescape"] = { fg = p.special, bg = "NONE", sp = "NONE" },
  ["netrwClassify"] = { fg = p.muted, bg = "NONE", sp = "NONE", bold = true },
  ["netrwExe"] = { fg = p.keyword, bg = "NONE", sp = "NONE" },
  ["phpIdentifier"] = { fg = p.special, bg = "NONE", sp = "NONE" },
  ["phpSpecialFunction"] = { fg = p.builtin, bg = "NONE", sp = "NONE" },
  ["shDerefSimple"] = { fg = p.special, bg = "NONE", sp = "NONE" },
  ["xmlTag"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["xmlTagName"] = { fg = p.module, bg = "NONE", sp = "NONE" },
}
