# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#fdf0ed"

# Main text color
theme[main_fg]="#333333"

# Title color for boxes
theme[title]="#333333"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#da103f"

# Background color of selected item in processes box
theme[selected_bg]="#8a31b9"

# Foreground color of selected item in processes box
theme[selected_fg]="#fdf0ed"

# Color of inactive/disabled text
theme[inactive_fg]="#8a31b9"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#333333"

# Background color of the percentage meters
theme[meter_bg]="#8a31b9"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#333333"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#e73665"
theme[mem_box]="#1eb980"
theme[net_box]="#da103f"
theme[proc_box]="#da103f"

# Box divider line and small boxes line color
theme[div_line]="#8a31b9"

# Temperature graph color
theme[temp_start]="#1eb980"
theme[temp_mid]="#af5427"
theme[temp_end]="#da103f"

# CPU graph colors
theme[cpu_start]="#1d8991"
theme[cpu_mid]="#8a31b9"
theme[cpu_end]="#e73665"

# Mem/Disk free meter
theme[free_start]="#e73665"
theme[free_mid]="#8a31b9"
theme[free_end]="#1d8991"

# Mem/Disk cached meter
theme[cached_start]="#8a31b9"
theme[cached_mid]="#1d8991"
theme[cached_end]="#e73665"

# Mem/Disk available meter
theme[available_start]="#af5427"
theme[available_mid]="#da103f"
theme[available_end]="#da103f"

# Mem/Disk used meter
theme[used_start]="#1eb980"
theme[used_mid]="#1d8991"
theme[used_end]="#8a31b9"

# Download graph colors
theme[download_start]="#af5427"
theme[download_mid]="#da103f"
theme[download_end]="#da103f"

# Upload graph colors
theme[upload_start]="#1eb980"
theme[upload_mid]="#1d8991"
theme[upload_end]="#8a31b9"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#1d8991"
theme[process_mid]="#8a31b9"
theme[process_end]="#e73665"
