accent = "#0c060d"
cursor = "#fafafa"
foreground = "#fafafa"
background = "#0c060d"
selection_foreground = "#0c060d"
selection_background = "#fafafa"

color0 = "#0c060d"
color1 = "#6A5457"
color2 = "#B0413B"
color3 = "#DCA23E"
color4 = "#3F57A1"
color5 = "#90788B"
color6 = "#3EAFD3"
color7 = "#ccc2c2"
color8 = "#8e8787"
color9 = "#9f8589"
color10 = "#d4827d"
color11 = "#eccc94"
color12 = "#7b8ecb"
color13 = "#beb0bb"
color14 = "#91d1e6"
color15 = "#fafafa"
