return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#0c060d",
				bg = "#0c060d",
				dark_bg = "#09040a",
				darker_bg = "#070408",
				lighter_bg = "#1b151c",
				selection = "#fafafa",
				selection_background = "#fafafa",
				selection_foreground = "#0c060d",
				foreground = "#fafafa",
				fg = "#fafafa",
				light_fg = "#fafafa",
				bright_fg = "#fafafa",
				dark_fg = "#8f8c8f",
				muted = "#8e8787",
				cursor = "#fafafa",
				accent = "#3f57a1",
				red = "#6a5457",
				green = "#b0413b",
				yellow = "#dca23e",
				blue = "#3f57a1",
				purple = "#90788b",
				magenta = "#90788b",
				cyan = "#3eafd3",
				orange = "#9f8589",
				brown = "#7f6a6e",
				bright_red = "#9f8589",
				bright_green = "#d4827d",
				bright_yellow = "#eccc94",
				bright_blue = "#7b8ecb",
				bright_purple = "#beb0bb",
				bright_cyan = "#91d1e6",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
