return {
	{
		vgs_vendored = "aether.nvim",
		name = "aether",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				background = "#181c1f",
				bg = "#181c1f",
				dark_bg = "#121517",
				darker_bg = "#0e1113",
				lighter_bg = "#262a2c",
				selection = "#fdf9f8",
				selection_background = "#fdf9f8",
				selection_foreground = "#181c1f",
				foreground = "#fdf9f8",
				fg = "#fdf9f8",
				light_fg = "#fdfaf9",
				bright_fg = "#fdf9f8",
				dark_fg = "#969696",
				muted = "#b18d85",
				cursor = "#fdf9f8",
				accent = "#ed333b",
				red = "#9b584d",
				green = "#9f6769",
				yellow = "#bb6d6c",
				blue = "#b97670",
				purple = "#9a8c8a",
				magenta = "#9a8c8a",
				cyan = "#da7a6f",
				orange = "#ca887f",
				brown = "#a26d66",
				bright_red = "#ca887f",
				bright_green = "#c79d9f",
				bright_yellow = "#d7adad",
				bright_blue = "#d7b2ae",
				bright_purple = "#c4bcbb",
				bright_cyan = "#ecbeb9",
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "aether",
		},
	},
}
